// @generated by Template Base. Do not edit by hand.
import 'ant-design-vue/dist/reset.css'
import './styles.css'
import { createPinia } from 'pinia'
import { createApp } from 'vue'
import Antd from 'ant-design-vue'
import App from './App.vue'
import router from './router'

createApp(App).use(createPinia()).use(router).use(Antd).mount('#app')
