// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.moduleconfig.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.moduleconfig.base.entity.CfgDictionaryPublication;
import com.unique.unexamine.moduleconfig.base.mapper.CfgDictionaryPublicationMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class CfgDictionaryPublicationBaseService {
    private final CfgDictionaryPublicationMapper mapper;

    public CfgDictionaryPublicationBaseService(CfgDictionaryPublicationMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(CfgDictionaryPublication entity) {
        return mapper.insert(entity);
    }

    public CfgDictionaryPublication selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<CfgDictionaryPublication> selectList(Wrapper<CfgDictionaryPublication> query) {
        return mapper.selectList(query);
    }

    public int updateById(CfgDictionaryPublication entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
