// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.moduleconfig.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.moduleconfig.base.entity.CfgDictionaryItem;
import com.unique.unexamine.moduleconfig.base.mapper.CfgDictionaryItemMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class CfgDictionaryItemBaseService {
    private final CfgDictionaryItemMapper mapper;

    public CfgDictionaryItemBaseService(CfgDictionaryItemMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(CfgDictionaryItem entity) {
        return mapper.insert(entity);
    }

    public CfgDictionaryItem selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<CfgDictionaryItem> selectList(Wrapper<CfgDictionaryItem> query) {
        return mapper.selectList(query);
    }

    public int updateById(CfgDictionaryItem entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
