// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.moduleconfig.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.moduleconfig.base.entity.CfgQueryIndexField;
import com.unique.unexamine.moduleconfig.base.mapper.CfgQueryIndexFieldMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class CfgQueryIndexFieldBaseService {
    private final CfgQueryIndexFieldMapper mapper;

    public CfgQueryIndexFieldBaseService(CfgQueryIndexFieldMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(CfgQueryIndexField entity) {
        return mapper.insert(entity);
    }

    public CfgQueryIndexField selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<CfgQueryIndexField> selectList(Wrapper<CfgQueryIndexField> query) {
        return mapper.selectList(query);
    }

    public int updateById(CfgQueryIndexField entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
