// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.moduleconfig.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.moduleconfig.base.entity.CfgTenantExtensionVersion;
import com.unique.unexamine.moduleconfig.base.mapper.CfgTenantExtensionVersionMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class CfgTenantExtensionVersionBaseService {
    private final CfgTenantExtensionVersionMapper mapper;

    public CfgTenantExtensionVersionBaseService(CfgTenantExtensionVersionMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(CfgTenantExtensionVersion entity) {
        return mapper.insert(entity);
    }

    public CfgTenantExtensionVersion selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<CfgTenantExtensionVersion> selectList(Wrapper<CfgTenantExtensionVersion> query) {
        return mapper.selectList(query);
    }
}
