// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.moduleconfig.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.moduleconfig.base.entity.ConfiguredModule;
import com.unique.unexamine.moduleconfig.base.mapper.ConfiguredModuleMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class ConfiguredModuleBaseService {
    private final ConfiguredModuleMapper mapper;

    public ConfiguredModuleBaseService(ConfiguredModuleMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(ConfiguredModule entity) {
        return mapper.insert(entity);
    }

    public ConfiguredModule selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<ConfiguredModule> selectList(Wrapper<ConfiguredModule> query) {
        return mapper.selectList(query);
    }

    public int updateById(ConfiguredModule entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
