// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.moduleconfig.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.moduleconfig.base.entity.ConfiguredModuleAction;
import com.unique.unexamine.moduleconfig.base.mapper.ConfiguredModuleActionMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class ConfiguredModuleActionBaseService {
    private final ConfiguredModuleActionMapper mapper;

    public ConfiguredModuleActionBaseService(ConfiguredModuleActionMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(ConfiguredModuleAction entity) {
        return mapper.insert(entity);
    }

    public ConfiguredModuleAction selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<ConfiguredModuleAction> selectList(Wrapper<ConfiguredModuleAction> query) {
        return mapper.selectList(query);
    }

    public int updateById(ConfiguredModuleAction entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
