// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.moduleconfig.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.moduleconfig.base.entity.ConfiguredModulePage;
import com.unique.unexamine.moduleconfig.base.mapper.ConfiguredModulePageMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class ConfiguredModulePageBaseService {
    private final ConfiguredModulePageMapper mapper;

    public ConfiguredModulePageBaseService(ConfiguredModulePageMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(ConfiguredModulePage entity) {
        return mapper.insert(entity);
    }

    public ConfiguredModulePage selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<ConfiguredModulePage> selectList(Wrapper<ConfiguredModulePage> query) {
        return mapper.selectList(query);
    }

    public int updateById(ConfiguredModulePage entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
