from __future__ import annotations

import copy
import hashlib
import json
import sys
import tempfile
import unittest
from pathlib import Path


BASE_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(BASE_ROOT / "tools"))

from template_base.contract import ContractError, load_contract, require_generation_ready, validate_contract
from template_base.delivery import delivery_status
from template_base.generator import GenerationError, check_repeatable, generate_project


class TemplateBaseContractTest(unittest.TestCase):
    contract_path = BASE_ROOT / "examples" / "work-order" / "project.contract.json"

    def test_sample_contract_is_source_bound_and_valid(self) -> None:
        contract = load_contract(self.contract_path)
        self.assertEqual([], validate_contract(contract, self.contract_path))

    def test_unresolved_product_decision_blocks_generation(self) -> None:
        contract = copy.deepcopy(load_contract(self.contract_path))
        contract["unresolvedDecisions"] = [{"id": "DEC-1", "question": "谁可以删除？", "blocking": True}]
        with self.assertRaises(ContractError):
            require_generation_ready(contract, self.contract_path)

    def test_duplicate_field_is_rejected(self) -> None:
        contract = copy.deepcopy(load_contract(self.contract_path))
        contract["modules"][0]["fields"][2]["code"] = "orderNo"
        issues = validate_contract(contract, self.contract_path)
        self.assertTrue(any("duplicate value" in issue.message for issue in issues))

    def test_generation_is_repeatable_and_contains_separate_generated_boundaries(self) -> None:
        contract = load_contract(self.contract_path)
        result = check_repeatable(contract, self.contract_path)
        self.assertTrue(result["repeatable"])
        self.assertGreater(result["fileCount"], 20)
        with tempfile.TemporaryDirectory(prefix="template-base-test-") as directory:
            root = Path(directory)
            first = generate_project(contract, self.contract_path, root)
            second = generate_project(contract, self.contract_path, root)
            self.assertTrue(first["changed"])
            self.assertEqual([], second["changed"])
            self.assertEqual([], second["removed"])
            package = "io/templatebase/sample/workorder"
            entity = root / "backend" / "src" / "main" / "java" / package / "base" / "entity" / "WorkOrder.java"
            controller = root / "backend" / "src" / "main" / "java" / package / "manage" / "generated" / "workorder" / "WorkOrderController.java"
            self.assertIn("@generated by Template Base", entity.read_text(encoding="utf-8"))
            self.assertIn("@generated by Template Base", controller.read_text(encoding="utf-8"))
            self.assertNotIn("JdbcTemplate", controller.read_text(encoding="utf-8"))

    def test_generation_removes_only_unmodified_stale_generated_files(self) -> None:
        contract = load_contract(self.contract_path)
        with tempfile.TemporaryDirectory(prefix="template-base-stale-") as directory:
            root = Path(directory)
            generate_project(contract, self.contract_path, root)
            manifest_path = root / "generation-manifest.json"
            manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
            stale_path = root / "backend" / "stale-generated.txt"
            stale_path.write_text("generated-before\n", encoding="utf-8")
            manifest["generatedFiles"].append({
                "path": "backend/stale-generated.txt",
                "sha256": hashlib.sha256(stale_path.read_bytes()).hexdigest(),
            })
            manifest_path.write_text(
                json.dumps(manifest, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
                encoding="utf-8",
            )
            result = generate_project(contract, self.contract_path, root)
            self.assertEqual(["backend/stale-generated.txt"], result["removed"])
            self.assertFalse(stale_path.exists())

    def test_generation_refuses_to_overwrite_modified_generated_file(self) -> None:
        contract = load_contract(self.contract_path)
        with tempfile.TemporaryDirectory(prefix="template-base-dirty-") as directory:
            root = Path(directory)
            generate_project(contract, self.contract_path, root)
            target = root / "frontend" / "src" / "main.ts"
            target.write_text("// manual edit\n", encoding="utf-8")
            with self.assertRaisesRegex(GenerationError, "modified outside the generator"):
                generate_project(contract, self.contract_path, root)

    def test_release_never_passes_without_runtime_evidence_and_user_acceptance(self) -> None:
        contract = load_contract(self.contract_path)
        with tempfile.TemporaryDirectory(prefix="template-base-gates-") as directory:
            root = Path(directory)
            generated = root / "generated"
            generate_project(contract, self.contract_path, generated)
            status = delivery_status(self.contract_path, generated)
            self.assertFalse(status["engineeringReady"])
            self.assertFalse(status["userAccepted"])
            self.assertFalse(status["releaseReady"])
            self.assertEqual("GENERATED", status["computedPhase"])
            self.assertTrue(status["gates"]["realJourneySource"]["passed"])

    def test_release_requires_hash_bound_runtime_and_explicit_user_acceptance(self) -> None:
        contract = load_contract(self.contract_path)
        with tempfile.TemporaryDirectory(prefix="template-base-release-") as directory:
            root = Path(directory)
            generated = root / "generated"
            result = generate_project(contract, self.contract_path, generated)
            contract_hash = hashlib.sha256(self.contract_path.read_bytes()).hexdigest()
            manifest_path = generated / "generation-manifest.json"
            manifest_hash = hashlib.sha256(manifest_path.read_bytes()).hexdigest()
            evidence_path = root / "delivery-evidence.json"
            evidence_path.write_text(json.dumps({
                "schemaVersion": 1,
                "contractSha256": contract_hash,
                "generationManifestSha256": manifest_hash,
                "journeyMode": "browser-ui-to-api-to-mysql",
                "mocked": False,
                "checks": {name: True for name in (
                    "backendTests", "frontendBuild", "backendHealth", "frontendHealth", "browserJourney", "mysqlReadback"
                )},
            }), encoding="utf-8")
            acceptance_path = root / "user-acceptance.json"
            acceptance_path.write_text(json.dumps({
                "accepted": True,
                "recordedBy": "user",
                "projectId": result["manifest"]["projectId"],
                "contractSha256": contract_hash,
                "generationManifestSha256": manifest_hash,
                "acceptedBy": "example-user",
                "acceptedAt": "2026-08-11T00:00:00+08:00",
                "scope": "example contract and generated tree",
            }), encoding="utf-8")
            status = delivery_status(self.contract_path, generated, evidence_path, acceptance_path)
            self.assertTrue(status["engineeringReady"])
            self.assertTrue(status["userAccepted"])
            self.assertTrue(status["releaseReady"])
            self.assertEqual("RELEASE_READY", status["computedPhase"])


if __name__ == "__main__":
    unittest.main()
