// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.aiwork.base.service;

import com.baomidou.mybatisplus.extension.service.IService;
import com.unique.examine.aiwork.base.entity.AgentModelAuthorization;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

/**
 * Generated base service contract for AgentModelAuthorization.
 */
public interface AgentModelAuthorizationBaseService extends IService<AgentModelAuthorization> {

    Optional<AgentModelAuthorization> findById(Long id);

    List<AgentModelAuthorization> findAll();

    AgentModelAuthorization saveEntity(AgentModelAuthorization entity);

    boolean deleteByIds(Collection<Long> ids);
}
