// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.aiwork.base.service;

import com.baomidou.mybatisplus.extension.service.IService;
import com.unique.examine.aiwork.base.entity.AgentAuditLog;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

/**
 * Generated base service contract for AgentAuditLog.
 */
public interface AgentAuditLogBaseService extends IService<AgentAuditLog> {

    Optional<AgentAuditLog> findById(Long id);

    List<AgentAuditLog> findAll();

    AgentAuditLog saveEntity(AgentAuditLog entity);

    boolean deleteByIds(Collection<Long> ids);
}
