// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.aiwork.base.service;

import com.baomidou.mybatisplus.extension.service.IService;
import com.unique.examine.aiwork.base.entity.WorkDailyReportAutoSourceRule;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

/**
 * Generated base service contract for WorkDailyReportAutoSourceRule.
 */
public interface WorkDailyReportAutoSourceRuleBaseService extends IService<WorkDailyReportAutoSourceRule> {

    Optional<WorkDailyReportAutoSourceRule> findById(Long id);

    List<WorkDailyReportAutoSourceRule> findAll();

    WorkDailyReportAutoSourceRule saveEntity(WorkDailyReportAutoSourceRule entity);

    boolean deleteByIds(Collection<Long> ids);
}
