// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.aiwork.base.service;

import com.baomidou.mybatisplus.extension.service.IService;
import com.unique.examine.aiwork.base.entity.WorkProject;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

/**
 * Generated base service contract for WorkProject.
 */
public interface WorkProjectBaseService extends IService<WorkProject> {

    Optional<WorkProject> findById(Long id);

    List<WorkProject> findAll();

    WorkProject saveEntity(WorkProject entity);

    boolean deleteByIds(Collection<Long> ids);
}
