import { flushPromises, mount } from '@vue/test-utils'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import router from '@/router'
import { platformOpenApiApi } from '@/services/platformOpenApi'
import type { PlatformOpenApiApplication } from '@/types/platformOpenApi'
import PlatformOpenApiApplicationsView from '@/views/platform/admin/PlatformOpenApiApplicationsView.vue'

const application:PlatformOpenApiApplication={id:'app/9',serviceAccountId:'71',appKey:'platform_app_key_123456',name:'Platform task reader',status:'ACTIVE',scopes:['platform.task.read'],ipAllowlist:['127.0.0.1'],rateLimitPerMinute:120,credentialVersion:2,secretRef:'vault://must-never-render/plain-secret',version:4,createdAt:'2026-08-07T01:00:00Z',updatedAt:'2026-08-07T02:00:00Z'}
function envelope(data:unknown){return Promise.resolve(new Response(JSON.stringify({code:'OK',message:'',data,requestId:'r1',traceId:'t1',errors:[]}),{status:200,headers:{'Content-Type':'application/json'}}))}
function render(){return mount(PlatformOpenApiApplicationsView,{global:{stubs:{AdminPageHeader:{template:'<header><slot name="actions" /></header>'},KeyRound:true,Plus:true,RefreshCw:true,'a-alert':{props:['message','description'],template:'<div class="alert">{{message}} {{description}}</div>'},'a-button':{template:'<button @click="$emit(\'click\')"><slot /></button>'},'a-space':{template:'<div><slot /></div>'},'a-table':{props:['dataSource'],template:'<div><div v-for="record in dataSource" :key="record.id"><slot name="bodyCell" :column="{key:\'application\'}" :record="record"/><slot name="bodyCell" :column="{key:\'actions\'}" :record="record"/></div></div>'},'a-tag':{template:'<span><slot /></span>'},'a-modal':{props:['open'],template:'<div v-if="open"><slot /></div>'},'a-form':{template:'<form><slot /></form>'},'a-form-item':{template:'<div><slot /></div>'},'a-input':true,'a-textarea':true,'a-input-number':true}}})}

describe('platform OpenAPI administration',()=>{
  beforeEach(()=>{vi.restoreAllMocks();document.cookie='EXAMINE_CSRF=csrf-token; path=/'})
  afterEach(()=>vi.unstubAllGlobals())
  it('registers the isolated platform route behind its exact permission',()=>{const route=router.getRoutes().find(v=>v.name==='platform-admin-openapi-applications');expect(route?.path).toBe('/platform/admin/openapi-applications');expect(route?.meta.requiredPermissions).toEqual(['platform.openapi.application.manage'])})
  it('binds create, rotation, enable/disable and sanitized call-log APIs',async()=>{const fetchMock=vi.fn((_input:RequestInfo|URL,_init?:RequestInit)=>envelope({items:[],page:1,size:20,total:0}));vi.stubGlobal('fetch',fetchMock);await platformOpenApiApi.create({serviceAccountId:'71',name:'reader',secretRef:'vault://platform/v1',scopes:['platform.task.read'],ipAllowlist:['127.0.0.1'],rateLimitPerMinute:120});await platformOpenApiApi.rotate('app/9','vault://platform/v2',4);await platformOpenApiApi.status('app/9','disable',5,'incident');await platformOpenApiApi.status('app/9','enable',6,'recovered');await platformOpenApiApi.callLogs('app/9','SIGNATURE_REJECTED','GET',2,50);expect(fetchMock.mock.calls.map(c=>c[0])).toEqual(['/api/v1/platform/admin/openapi/applications','/api/v1/platform/admin/openapi/applications/app%2F9:rotate-secret-ref','/api/v1/platform/admin/openapi/applications/app%2F9:disable','/api/v1/platform/admin/openapi/applications/app%2F9:enable','/api/v1/platform/admin/openapi/applications/app%2F9/call-logs?resultCategory=SIGNATURE_REJECTED&requestMethod=GET&page=2&size=50']);expect(fetchMock.mock.calls.map(c=>(c[1] as RequestInit).method)).toEqual(['POST','POST','POST','POST',undefined]);expect(JSON.parse(String((fetchMock.mock.calls[1]![1] as RequestInit).body))).toEqual({secretRef:'vault://platform/v2',version:4});expect(JSON.parse(String((fetchMock.mock.calls[2]![1] as RequestInit).body))).toEqual({version:5,reason:'incident'})})
  it('renders identity and status without ever echoing the SecretRef',async()=>{vi.spyOn(platformOpenApiApi,'list').mockResolvedValue({items:[application],page:1,size:20,total:1});const wrapper=render();await flushPromises();expect(wrapper.text()).toContain(application.name);expect(wrapper.text()).toContain(application.appKey);expect(wrapper.text()).not.toContain('vault://');expect(wrapper.text()).not.toContain('plain-secret')})
  it('surfaces the list error state',async()=>{vi.spyOn(platformOpenApiApi,'list').mockRejectedValue(new Error('offline'));const wrapper=render();await flushPromises();expect(wrapper.get('.alert').text()).toContain('平台应用服务暂时不可用')})
})
