// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.foundation.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.foundation.base.entity.CoreSequence;
import com.unique.unexamine.foundation.base.mapper.CoreSequenceMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class CoreSequenceBaseService {
    private final CoreSequenceMapper mapper;

    public CoreSequenceBaseService(CoreSequenceMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(CoreSequence entity) {
        return mapper.insert(entity);
    }

    public CoreSequence selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<CoreSequence> selectList(Wrapper<CoreSequence> query) {
        return mapper.selectList(query);
    }

    public int updateById(CoreSequence entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
