// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.foundation.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.foundation.base.entity.CoreCacheEpoch;
import com.unique.unexamine.foundation.base.mapper.CoreCacheEpochMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class CoreCacheEpochBaseService {
    private final CoreCacheEpochMapper mapper;

    public CoreCacheEpochBaseService(CoreCacheEpochMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(CoreCacheEpoch entity) {
        return mapper.insert(entity);
    }

    public CoreCacheEpoch selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<CoreCacheEpoch> selectList(Wrapper<CoreCacheEpoch> query) {
        return mapper.selectList(query);
    }

    public int updateById(CoreCacheEpoch entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
