// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.foundation.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.foundation.base.entity.CoreEventOutbox;
import com.unique.unexamine.foundation.base.mapper.CoreEventOutboxMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class CoreEventOutboxBaseService {
    private final CoreEventOutboxMapper mapper;

    public CoreEventOutboxBaseService(CoreEventOutboxMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(CoreEventOutbox entity) {
        return mapper.insert(entity);
    }

    public CoreEventOutbox selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<CoreEventOutbox> selectList(Wrapper<CoreEventOutbox> query) {
        return mapper.selectList(query);
    }

    public int updateById(CoreEventOutbox entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
