// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.foundation.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.foundation.base.entity.CoreFeatureFlag;
import com.unique.unexamine.foundation.base.mapper.CoreFeatureFlagMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class CoreFeatureFlagBaseService {
    private final CoreFeatureFlagMapper mapper;

    public CoreFeatureFlagBaseService(CoreFeatureFlagMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(CoreFeatureFlag entity) {
        return mapper.insert(entity);
    }

    public CoreFeatureFlag selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<CoreFeatureFlag> selectList(Wrapper<CoreFeatureFlag> query) {
        return mapper.selectList(query);
    }

    public int updateById(CoreFeatureFlag entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
