// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.foundation.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.foundation.base.entity.CoreSetting;
import com.unique.unexamine.foundation.base.mapper.CoreSettingMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class CoreSettingBaseService {
    private final CoreSettingMapper mapper;

    public CoreSettingBaseService(CoreSettingMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(CoreSetting entity) {
        return mapper.insert(entity);
    }

    public CoreSetting selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<CoreSetting> selectList(Wrapper<CoreSetting> query) {
        return mapper.selectList(query);
    }

    public int updateById(CoreSetting entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
