// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.foundation.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.foundation.base.entity.CoreIdempotencyRecord;
import com.unique.unexamine.foundation.base.mapper.CoreIdempotencyRecordMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class CoreIdempotencyRecordBaseService {
    private final CoreIdempotencyRecordMapper mapper;

    public CoreIdempotencyRecordBaseService(CoreIdempotencyRecordMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(CoreIdempotencyRecord entity) {
        return mapper.insert(entity);
    }

    public CoreIdempotencyRecord selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<CoreIdempotencyRecord> selectList(Wrapper<CoreIdempotencyRecord> query) {
        return mapper.selectList(query);
    }

    public int updateById(CoreIdempotencyRecord entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
