// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.platform.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.platform.base.entity.PlatSsoProvider;
import com.unique.unexamine.platform.base.mapper.PlatSsoProviderMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class PlatSsoProviderBaseService {
    private final PlatSsoProviderMapper mapper;

    public PlatSsoProviderBaseService(PlatSsoProviderMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(PlatSsoProvider entity) {
        return mapper.insert(entity);
    }

    public PlatSsoProvider selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<PlatSsoProvider> selectList(Wrapper<PlatSsoProvider> query) {
        return mapper.selectList(query);
    }

    public int updateById(PlatSsoProvider entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
