// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.platform.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.platform.base.entity.PlatformAccount;
import com.unique.unexamine.platform.base.mapper.PlatformAccountMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class PlatformAccountBaseService {
    private final PlatformAccountMapper mapper;

    public PlatformAccountBaseService(PlatformAccountMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(PlatformAccount entity) {
        return mapper.insert(entity);
    }

    public PlatformAccount selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<PlatformAccount> selectList(Wrapper<PlatformAccount> query) {
        return mapper.selectList(query);
    }

    public int updateById(PlatformAccount entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
