// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.platform.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.platform.base.entity.PlatPasswordHistory;
import com.unique.unexamine.platform.base.mapper.PlatPasswordHistoryMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class PlatPasswordHistoryBaseService {
    private final PlatPasswordHistoryMapper mapper;

    public PlatPasswordHistoryBaseService(PlatPasswordHistoryMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(PlatPasswordHistory entity) {
        return mapper.insert(entity);
    }

    public PlatPasswordHistory selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<PlatPasswordHistory> selectList(Wrapper<PlatPasswordHistory> query) {
        return mapper.selectList(query);
    }
}
