// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.platform.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.platform.base.entity.PlatSsoProviderVersion;
import com.unique.unexamine.platform.base.mapper.PlatSsoProviderVersionMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class PlatSsoProviderVersionBaseService {
    private final PlatSsoProviderVersionMapper mapper;

    public PlatSsoProviderVersionBaseService(PlatSsoProviderVersionMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(PlatSsoProviderVersion entity) {
        return mapper.insert(entity);
    }

    public PlatSsoProviderVersion selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<PlatSsoProviderVersion> selectList(Wrapper<PlatSsoProviderVersion> query) {
        return mapper.selectList(query);
    }

    public int updateById(PlatSsoProviderVersion entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
