// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.runtimedata.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.runtimedata.base.entity.BizRecordOwnerHistory;
import com.unique.unexamine.runtimedata.base.mapper.BizRecordOwnerHistoryMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class BizRecordOwnerHistoryBaseService {
    private final BizRecordOwnerHistoryMapper mapper;

    public BizRecordOwnerHistoryBaseService(BizRecordOwnerHistoryMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(BizRecordOwnerHistory entity) {
        return mapper.insert(entity);
    }

    public BizRecordOwnerHistory selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<BizRecordOwnerHistory> selectList(Wrapper<BizRecordOwnerHistory> query) {
        return mapper.selectList(query);
    }

    public int updateById(BizRecordOwnerHistory entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
