// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.runtimedata.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.runtimedata.base.entity.BizRecordConversionResult;
import com.unique.unexamine.runtimedata.base.mapper.BizRecordConversionResultMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class BizRecordConversionResultBaseService {
    private final BizRecordConversionResultMapper mapper;

    public BizRecordConversionResultBaseService(BizRecordConversionResultMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(BizRecordConversionResult entity) {
        return mapper.insert(entity);
    }

    public BizRecordConversionResult selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<BizRecordConversionResult> selectList(Wrapper<BizRecordConversionResult> query) {
        return mapper.selectList(query);
    }

    public int updateById(BizRecordConversionResult entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
