// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.runtimedata.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.runtimedata.base.entity.BizRecordIndex;
import com.unique.unexamine.runtimedata.base.mapper.BizRecordIndexMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class BizRecordIndexBaseService {
    private final BizRecordIndexMapper mapper;

    public BizRecordIndexBaseService(BizRecordIndexMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(BizRecordIndex entity) {
        return mapper.insert(entity);
    }

    public BizRecordIndex selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<BizRecordIndex> selectList(Wrapper<BizRecordIndex> query) {
        return mapper.selectList(query);
    }

    public int updateById(BizRecordIndex entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
