// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.runtimedata.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.runtimedata.base.entity.BizRecordConversion;
import com.unique.unexamine.runtimedata.base.mapper.BizRecordConversionMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class BizRecordConversionBaseService {
    private final BizRecordConversionMapper mapper;

    public BizRecordConversionBaseService(BizRecordConversionMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(BizRecordConversion entity) {
        return mapper.insert(entity);
    }

    public BizRecordConversion selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<BizRecordConversion> selectList(Wrapper<BizRecordConversion> query) {
        return mapper.selectList(query);
    }

    public int updateById(BizRecordConversion entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
