// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.runtimedata.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.runtimedata.base.entity.BizRecordRelation;
import com.unique.unexamine.runtimedata.base.mapper.BizRecordRelationMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class BizRecordRelationBaseService {
    private final BizRecordRelationMapper mapper;

    public BizRecordRelationBaseService(BizRecordRelationMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(BizRecordRelation entity) {
        return mapper.insert(entity);
    }

    public BizRecordRelation selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<BizRecordRelation> selectList(Wrapper<BizRecordRelation> query) {
        return mapper.selectList(query);
    }

    public int updateById(BizRecordRelation entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
