// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.runtimedata.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.runtimedata.base.entity.BizTenantShareUsage;
import com.unique.unexamine.runtimedata.base.mapper.BizTenantShareUsageMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class BizTenantShareUsageBaseService {
    private final BizTenantShareUsageMapper mapper;

    public BizTenantShareUsageBaseService(BizTenantShareUsageMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(BizTenantShareUsage entity) {
        return mapper.insert(entity);
    }

    public BizTenantShareUsage selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<BizTenantShareUsage> selectList(Wrapper<BizTenantShareUsage> query) {
        return mapper.selectList(query);
    }

    public int updateById(BizTenantShareUsage entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
