// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.runtimedata.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.runtimedata.base.entity.BusinessRecord;
import com.unique.unexamine.runtimedata.base.mapper.BusinessRecordMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class BusinessRecordBaseService {
    private final BusinessRecordMapper mapper;

    public BusinessRecordBaseService(BusinessRecordMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(BusinessRecord entity) {
        return mapper.insert(entity);
    }

    public BusinessRecord selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<BusinessRecord> selectList(Wrapper<BusinessRecord> query) {
        return mapper.selectList(query);
    }

    public int updateById(BusinessRecord entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
