// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.app.base.service.impl;

import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.unique.examine.app.base.entity.OpenapiCallLog;
import com.unique.examine.app.base.mapper.OpenapiCallLogMapper;
import com.unique.examine.app.base.service.OpenapiCallLogBaseService;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

import org.springframework.stereotype.Service;

/**
 * Generated MyBatis-Plus base service implementation for OpenapiCallLog.
 */
@Service
public class OpenapiCallLogBaseServiceImpl extends ServiceImpl<OpenapiCallLogMapper, OpenapiCallLog> implements OpenapiCallLogBaseService {

    @Override
    public Optional<OpenapiCallLog> findById(Long id) {
        return Optional.ofNullable(getById(id));
    }

    @Override
    public List<OpenapiCallLog> findAll() {
        return list();
    }

    @Override
    public OpenapiCallLog saveEntity(OpenapiCallLog entity) {
        saveOrUpdate(entity);
        return entity;
    }

    @Override
    public boolean deleteByIds(Collection<Long> ids) {
        return ids != null && !ids.isEmpty() && removeBatchByIds(ids);
    }
}
