// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.app.base.service.impl;

import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.unique.examine.app.base.entity.OpenapiApp;
import com.unique.examine.app.base.mapper.OpenapiAppMapper;
import com.unique.examine.app.base.service.OpenapiAppBaseService;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

import org.springframework.stereotype.Service;

/**
 * Generated MyBatis-Plus base service implementation for OpenapiApp.
 */
@Service
public class OpenapiAppBaseServiceImpl extends ServiceImpl<OpenapiAppMapper, OpenapiApp> implements OpenapiAppBaseService {

    @Override
    public Optional<OpenapiApp> findById(Long id) {
        return Optional.ofNullable(getById(id));
    }

    @Override
    public List<OpenapiApp> findAll() {
        return list();
    }

    @Override
    public OpenapiApp saveEntity(OpenapiApp entity) {
        saveOrUpdate(entity);
        return entity;
    }

    @Override
    public boolean deleteByIds(Collection<Long> ids) {
        return ids != null && !ids.isEmpty() && removeBatchByIds(ids);
    }
}
