// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.module.base.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.unique.examine.module.base.entity.ModuleDefinition;

import org.apache.ibatis.annotations.Mapper;

/**
 * Generated mapper contract for table `un_module_definition`.
 */
@Mapper
public interface ModuleDefinitionMapper extends BaseMapper<ModuleDefinition> {

    String TABLE_NAME = ModuleDefinition.TABLE_NAME;
}
