// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.module.base.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.unique.examine.module.base.entity.ModuleDictType;

import org.apache.ibatis.annotations.Mapper;

/**
 * Generated mapper contract for table `un_module_dict_type`.
 */
@Mapper
public interface ModuleDictTypeMapper extends BaseMapper<ModuleDictType> {

    String TABLE_NAME = ModuleDictType.TABLE_NAME;
}
