// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.module.base.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.unique.examine.module.base.entity.ModuleDynamicDraft;

import org.apache.ibatis.annotations.Mapper;

/**
 * Generated mapper contract for table `un_module_dynamic_draft`.
 */
@Mapper
public interface ModuleDynamicDraftMapper extends BaseMapper<ModuleDynamicDraft> {

    String TABLE_NAME = ModuleDynamicDraft.TABLE_NAME;
}
