// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.module.base.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.unique.examine.module.base.entity.ModuleDynamicAttachment;

import org.apache.ibatis.annotations.Mapper;

/**
 * Generated mapper contract for table `un_module_dynamic_attachment`.
 */
@Mapper
public interface ModuleDynamicAttachmentMapper extends BaseMapper<ModuleDynamicAttachment> {

    String TABLE_NAME = ModuleDynamicAttachment.TABLE_NAME;
}
