// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.module.base.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.unique.examine.module.base.entity.ModuleDictItem;

import org.apache.ibatis.annotations.Mapper;

/**
 * Generated mapper contract for table `un_module_dict_item`.
 */
@Mapper
public interface ModuleDictItemMapper extends BaseMapper<ModuleDictItem> {

    String TABLE_NAME = ModuleDictItem.TABLE_NAME;
}
