// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.module.base.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.unique.examine.module.base.entity.ModuleDynamicIndex;

import org.apache.ibatis.annotations.Mapper;

/**
 * Generated mapper contract for table `un_module_dynamic_index`.
 */
@Mapper
public interface ModuleDynamicIndexMapper extends BaseMapper<ModuleDynamicIndex> {

    String TABLE_NAME = ModuleDynamicIndex.TABLE_NAME;
}
