// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.module.base.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.unique.examine.module.base.entity.ModuleListScene;

import org.apache.ibatis.annotations.Mapper;

/**
 * Generated mapper contract for table `un_module_list_scene`.
 */
@Mapper
public interface ModuleListSceneMapper extends BaseMapper<ModuleListScene> {

    String TABLE_NAME = ModuleListScene.TABLE_NAME;
}
