// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.module.base.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.unique.examine.module.base.entity.ModuleWorkConfig;

import org.apache.ibatis.annotations.Mapper;

/**
 * Generated mapper contract for table `un_module_work_config`.
 */
@Mapper
public interface ModuleWorkConfigMapper extends BaseMapper<ModuleWorkConfig> {

    String TABLE_NAME = ModuleWorkConfig.TABLE_NAME;
}
