// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.module.base.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.unique.examine.module.base.entity.ModuleDynamicRecord;

import org.apache.ibatis.annotations.Mapper;

/**
 * Generated mapper contract for table `un_module_dynamic_record`.
 */
@Mapper
public interface ModuleDynamicRecordMapper extends BaseMapper<ModuleDynamicRecord> {

    String TABLE_NAME = ModuleDynamicRecord.TABLE_NAME;
}
