// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.module.base.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.unique.examine.module.base.entity.ModulePrintTemplate;

import org.apache.ibatis.annotations.Mapper;

/**
 * Generated mapper contract for table `un_module_print_template`.
 */
@Mapper
public interface ModulePrintTemplateMapper extends BaseMapper<ModulePrintTemplate> {

    String TABLE_NAME = ModulePrintTemplate.TABLE_NAME;
}
