// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.flow.base.service.impl;

import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.unique.examine.flow.base.entity.FlowDefinition;
import com.unique.examine.flow.base.mapper.FlowDefinitionMapper;
import com.unique.examine.flow.base.service.FlowDefinitionBaseService;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

import org.springframework.stereotype.Service;

/**
 * Generated MyBatis-Plus base service implementation for FlowDefinition.
 */
@Service
public class FlowDefinitionBaseServiceImpl extends ServiceImpl<FlowDefinitionMapper, FlowDefinition> implements FlowDefinitionBaseService {

    @Override
    public Optional<FlowDefinition> findById(Long id) {
        return Optional.ofNullable(getById(id));
    }

    @Override
    public List<FlowDefinition> findAll() {
        return list();
    }

    @Override
    public FlowDefinition saveEntity(FlowDefinition entity) {
        saveOrUpdate(entity);
        return entity;
    }

    @Override
    public boolean deleteByIds(Collection<Long> ids) {
        return ids != null && !ids.isEmpty() && removeBatchByIds(ids);
    }
}
