// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.flow.base.service.impl;

import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.unique.examine.flow.base.entity.FlowApprovalActionLog;
import com.unique.examine.flow.base.mapper.FlowApprovalActionLogMapper;
import com.unique.examine.flow.base.service.FlowApprovalActionLogBaseService;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

import org.springframework.stereotype.Service;

/**
 * Generated MyBatis-Plus base service implementation for FlowApprovalActionLog.
 */
@Service
public class FlowApprovalActionLogBaseServiceImpl extends ServiceImpl<FlowApprovalActionLogMapper, FlowApprovalActionLog> implements FlowApprovalActionLogBaseService {

    @Override
    public Optional<FlowApprovalActionLog> findById(Long id) {
        return Optional.ofNullable(getById(id));
    }

    @Override
    public List<FlowApprovalActionLog> findAll() {
        return list();
    }

    @Override
    public FlowApprovalActionLog saveEntity(FlowApprovalActionLog entity) {
        saveOrUpdate(entity);
        return entity;
    }

    @Override
    public boolean deleteByIds(Collection<Long> ids) {
        if (ids == null || ids.isEmpty()) {
            return false;
        }
        return removeBatchByIds(ids);
    }
}
