// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.flow.base.service.impl;

import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.unique.examine.flow.base.entity.FlowNode;
import com.unique.examine.flow.base.mapper.FlowNodeMapper;
import com.unique.examine.flow.base.service.FlowNodeBaseService;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

import org.springframework.stereotype.Service;

/**
 * Generated MyBatis-Plus base service implementation for FlowNode.
 */
@Service
public class FlowNodeBaseServiceImpl extends ServiceImpl<FlowNodeMapper, FlowNode> implements FlowNodeBaseService {

    @Override
    public Optional<FlowNode> findById(Long id) {
        return Optional.ofNullable(getById(id));
    }

    @Override
    public List<FlowNode> findAll() {
        return list();
    }

    @Override
    public FlowNode saveEntity(FlowNode entity) {
        saveOrUpdate(entity);
        return entity;
    }

    @Override
    public boolean deleteByIds(Collection<Long> ids) {
        if (ids == null || ids.isEmpty()) {
            return false;
        }
        return removeBatchByIds(ids);
    }
}
