// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.flow.base.service.impl;

import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.unique.examine.flow.base.entity.FlowSnapshot;
import com.unique.examine.flow.base.mapper.FlowSnapshotMapper;
import com.unique.examine.flow.base.service.FlowSnapshotBaseService;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

import org.springframework.stereotype.Service;

/**
 * Generated MyBatis-Plus base service implementation for FlowSnapshot.
 */
@Service
public class FlowSnapshotBaseServiceImpl extends ServiceImpl<FlowSnapshotMapper, FlowSnapshot> implements FlowSnapshotBaseService {

    @Override
    public Optional<FlowSnapshot> findById(Long id) {
        return Optional.ofNullable(getById(id));
    }

    @Override
    public List<FlowSnapshot> findAll() {
        return list();
    }

    @Override
    public FlowSnapshot saveEntity(FlowSnapshot entity) {
        saveOrUpdate(entity);
        return entity;
    }

    @Override
    public boolean deleteByIds(Collection<Long> ids) {
        if (ids == null || ids.isEmpty()) {
            return false;
        }
        return removeBatchByIds(ids);
    }
}
