// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.flow.base.service.impl;

import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.unique.examine.flow.base.entity.FlowEdge;
import com.unique.examine.flow.base.mapper.FlowEdgeMapper;
import com.unique.examine.flow.base.service.FlowEdgeBaseService;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

import org.springframework.stereotype.Service;

/**
 * Generated MyBatis-Plus base service implementation for FlowEdge.
 */
@Service
public class FlowEdgeBaseServiceImpl extends ServiceImpl<FlowEdgeMapper, FlowEdge> implements FlowEdgeBaseService {

    @Override
    public Optional<FlowEdge> findById(Long id) {
        return Optional.ofNullable(getById(id));
    }

    @Override
    public List<FlowEdge> findAll() {
        return list();
    }

    @Override
    public FlowEdge saveEntity(FlowEdge entity) {
        saveOrUpdate(entity);
        return entity;
    }

    @Override
    public boolean deleteByIds(Collection<Long> ids) {
        return ids != null && !ids.isEmpty() && removeBatchByIds(ids);
    }
}
