// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.flow.base.service.impl;

import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.unique.examine.flow.base.entity.FlowSimulationLog;
import com.unique.examine.flow.base.mapper.FlowSimulationLogMapper;
import com.unique.examine.flow.base.service.FlowSimulationLogBaseService;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

import org.springframework.stereotype.Service;

/**
 * Generated MyBatis-Plus base service implementation for FlowSimulationLog.
 */
@Service
public class FlowSimulationLogBaseServiceImpl extends ServiceImpl<FlowSimulationLogMapper, FlowSimulationLog> implements FlowSimulationLogBaseService {

    @Override
    public Optional<FlowSimulationLog> findById(Long id) {
        return Optional.ofNullable(getById(id));
    }

    @Override
    public List<FlowSimulationLog> findAll() {
        return list();
    }

    @Override
    public FlowSimulationLog saveEntity(FlowSimulationLog entity) {
        saveOrUpdate(entity);
        return entity;
    }

    @Override
    public boolean deleteByIds(Collection<Long> ids) {
        return ids != null && !ids.isEmpty() && removeBatchByIds(ids);
    }
}
