// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.flow.base.service.impl;

import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.unique.examine.flow.base.entity.FlowInstance;
import com.unique.examine.flow.base.mapper.FlowInstanceMapper;
import com.unique.examine.flow.base.service.FlowInstanceBaseService;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

import org.springframework.stereotype.Service;

/**
 * Generated MyBatis-Plus base service implementation for FlowInstance.
 */
@Service
public class FlowInstanceBaseServiceImpl extends ServiceImpl<FlowInstanceMapper, FlowInstance> implements FlowInstanceBaseService {

    @Override
    public Optional<FlowInstance> findById(Long id) {
        return Optional.ofNullable(getById(id));
    }

    @Override
    public List<FlowInstance> findAll() {
        return list();
    }

    @Override
    public FlowInstance saveEntity(FlowInstance entity) {
        saveOrUpdate(entity);
        return entity;
    }

    @Override
    public boolean deleteByIds(Collection<Long> ids) {
        return ids != null && !ids.isEmpty() && removeBatchByIds(ids);
    }
}
