// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.work.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.work.base.entity.WorkLogTaskLink;
import com.unique.unexamine.work.base.mapper.WorkLogTaskLinkMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class WorkLogTaskLinkBaseService {
    private final WorkLogTaskLinkMapper mapper;

    public WorkLogTaskLinkBaseService(WorkLogTaskLinkMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(WorkLogTaskLink entity) {
        return mapper.insert(entity);
    }

    public WorkLogTaskLink selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<WorkLogTaskLink> selectList(Wrapper<WorkLogTaskLink> query) {
        return mapper.selectList(query);
    }

    public int updateById(WorkLogTaskLink entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
