// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.work.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.work.base.entity.WorkTask;
import com.unique.unexamine.work.base.mapper.WorkTaskMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class WorkTaskBaseService {
    private final WorkTaskMapper mapper;

    public WorkTaskBaseService(WorkTaskMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(WorkTask entity) {
        return mapper.insert(entity);
    }

    public WorkTask selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<WorkTask> selectList(Wrapper<WorkTask> query) {
        return mapper.selectList(query);
    }

    public int updateById(WorkTask entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
