// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.work.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.work.base.entity.WorkLog;
import com.unique.unexamine.work.base.mapper.WorkLogMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class WorkLogBaseService {
    private final WorkLogMapper mapper;

    public WorkLogBaseService(WorkLogMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(WorkLog entity) {
        return mapper.insert(entity);
    }

    public WorkLog selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<WorkLog> selectList(Wrapper<WorkLog> query) {
        return mapper.selectList(query);
    }

    public int updateById(WorkLog entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
