// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.work.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.work.base.entity.WorkTaskGroup;
import com.unique.unexamine.work.base.mapper.WorkTaskGroupMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class WorkTaskGroupBaseService {
    private final WorkTaskGroupMapper mapper;

    public WorkTaskGroupBaseService(WorkTaskGroupMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(WorkTaskGroup entity) {
        return mapper.insert(entity);
    }

    public WorkTaskGroup selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<WorkTaskGroup> selectList(Wrapper<WorkTaskGroup> query) {
        return mapper.selectList(query);
    }

    public int updateById(WorkTaskGroup entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
