// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.messagelog.base.service.impl;

import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.unique.examine.messagelog.base.entity.AuditLoginLog;
import com.unique.examine.messagelog.base.mapper.AuditLoginLogMapper;
import com.unique.examine.messagelog.base.service.AuditLoginLogBaseService;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

import org.springframework.stereotype.Service;

/**
 * Generated MyBatis-Plus base service implementation for AuditLoginLog.
 */
@Service
public class AuditLoginLogBaseServiceImpl extends ServiceImpl<AuditLoginLogMapper, AuditLoginLog> implements AuditLoginLogBaseService {

    @Override
    public Optional<AuditLoginLog> findById(Long id) {
        return Optional.ofNullable(getById(id));
    }

    @Override
    public List<AuditLoginLog> findAll() {
        return list();
    }

    @Override
    public AuditLoginLog saveEntity(AuditLoginLog entity) {
        saveOrUpdate(entity);
        return entity;
    }

    @Override
    public boolean deleteByIds(Collection<Long> ids) {
        if (ids == null || ids.isEmpty()) {
            return false;
        }
        return removeBatchByIds(ids);
    }
}
