// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.messagelog.base.service.impl;

import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.unique.examine.messagelog.base.entity.AuditBusinessLog;
import com.unique.examine.messagelog.base.mapper.AuditBusinessLogMapper;
import com.unique.examine.messagelog.base.service.AuditBusinessLogBaseService;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

import org.springframework.stereotype.Service;

/**
 * Generated MyBatis-Plus base service implementation for AuditBusinessLog.
 */
@Service
public class AuditBusinessLogBaseServiceImpl extends ServiceImpl<AuditBusinessLogMapper, AuditBusinessLog> implements AuditBusinessLogBaseService {

    @Override
    public Optional<AuditBusinessLog> findById(Long id) {
        return Optional.ofNullable(getById(id));
    }

    @Override
    public List<AuditBusinessLog> findAll() {
        return list();
    }

    @Override
    public AuditBusinessLog saveEntity(AuditBusinessLog entity) {
        saveOrUpdate(entity);
        return entity;
    }

    @Override
    public boolean deleteByIds(Collection<Long> ids) {
        return ids != null && !ids.isEmpty() && removeBatchByIds(ids);
    }
}
