// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.messagelog.base.service.impl;

import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.unique.examine.messagelog.base.entity.MessageDeliveryLog;
import com.unique.examine.messagelog.base.mapper.MessageDeliveryLogMapper;
import com.unique.examine.messagelog.base.service.MessageDeliveryLogBaseService;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

import org.springframework.stereotype.Service;

/**
 * Generated MyBatis-Plus base service implementation for MessageDeliveryLog.
 */
@Service
public class MessageDeliveryLogBaseServiceImpl extends ServiceImpl<MessageDeliveryLogMapper, MessageDeliveryLog> implements MessageDeliveryLogBaseService {

    @Override
    public Optional<MessageDeliveryLog> findById(Long id) {
        return Optional.ofNullable(getById(id));
    }

    @Override
    public List<MessageDeliveryLog> findAll() {
        return list();
    }

    @Override
    public MessageDeliveryLog saveEntity(MessageDeliveryLog entity) {
        saveOrUpdate(entity);
        return entity;
    }

    @Override
    public boolean deleteByIds(Collection<Long> ids) {
        if (ids == null || ids.isEmpty()) {
            return false;
        }
        return removeBatchByIds(ids);
    }
}
