// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.plat.base.service;

import com.baomidou.mybatisplus.extension.service.IService;
import com.unique.examine.plat.base.entity.PlatTenant;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

/**
 * Generated base service contract for PlatTenant.
 */
public interface PlatTenantBaseService extends IService<PlatTenant> {

    Optional<PlatTenant> findById(Long id);

    List<PlatTenant> findAll();

    PlatTenant saveEntity(PlatTenant entity);

    boolean deleteByIds(Collection<Long> ids);
}
