// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.plat.base.service;

import com.baomidou.mybatisplus.extension.service.IService;
import com.unique.examine.plat.base.entity.PlatRolePermission;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

/**
 * Generated base service contract for PlatRolePermission.
 */
public interface PlatRolePermissionBaseService extends IService<PlatRolePermission> {

    Optional<PlatRolePermission> findById(Long id);

    List<PlatRolePermission> findAll();

    PlatRolePermission saveEntity(PlatRolePermission entity);

    boolean deleteByIds(Collection<Long> ids);
}
