// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.plat.base.service;

import com.baomidou.mybatisplus.extension.service.IService;
import com.unique.examine.plat.base.entity.PlatPermissionPreviewLog;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

/**
 * Generated base service contract for PlatPermissionPreviewLog.
 */
public interface PlatPermissionPreviewLogBaseService extends IService<PlatPermissionPreviewLog> {

    Optional<PlatPermissionPreviewLog> findById(Long id);

    List<PlatPermissionPreviewLog> findAll();

    PlatPermissionPreviewLog saveEntity(PlatPermissionPreviewLog entity);

    boolean deleteByIds(Collection<Long> ids);
}
