// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.plat.base.service;

import com.baomidou.mybatisplus.extension.service.IService;
import com.unique.examine.plat.base.entity.PlatDepartment;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

/**
 * Generated base service contract for PlatDepartment.
 */
public interface PlatDepartmentBaseService extends IService<PlatDepartment> {

    Optional<PlatDepartment> findById(Long id);

    List<PlatDepartment> findAll();

    PlatDepartment saveEntity(PlatDepartment entity);

    boolean deleteByIds(Collection<Long> ids);
}
