// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.plat.base.service;

import com.baomidou.mybatisplus.extension.service.IService;
import com.unique.examine.plat.base.entity.PlatAccount;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

/**
 * Generated base service contract for PlatAccount.
 */
public interface PlatAccountBaseService extends IService<PlatAccount> {

    Optional<PlatAccount> findById(Long id);

    List<PlatAccount> findAll();

    PlatAccount saveEntity(PlatAccount entity);

    boolean deleteByIds(Collection<Long> ids);
}
