// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.plat.base.service;

import com.baomidou.mybatisplus.extension.service.IService;
import com.unique.examine.plat.base.entity.PlatPermissionVersion;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

/**
 * Generated base service contract for PlatPermissionVersion.
 */
public interface PlatPermissionVersionBaseService extends IService<PlatPermissionVersion> {

    Optional<PlatPermissionVersion> findById(Long id);

    List<PlatPermissionVersion> findAll();

    PlatPermissionVersion saveEntity(PlatPermissionVersion entity);

    boolean deleteByIds(Collection<Long> ids);
}
