// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.plat.base.service;

import com.baomidou.mybatisplus.extension.service.IService;
import com.unique.examine.plat.base.entity.PlatDataScopeRule;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

/**
 * Generated base service contract for PlatDataScopeRule.
 */
public interface PlatDataScopeRuleBaseService extends IService<PlatDataScopeRule> {

    Optional<PlatDataScopeRule> findById(Long id);

    List<PlatDataScopeRule> findAll();

    PlatDataScopeRule saveEntity(PlatDataScopeRule entity);

    boolean deleteByIds(Collection<Long> ids);
}
