// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.plat.base.service;

import com.baomidou.mybatisplus.extension.service.IService;
import com.unique.examine.plat.base.entity.PlatSsoBinding;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

/**
 * Generated base service contract for PlatSsoBinding.
 */
public interface PlatSsoBindingBaseService extends IService<PlatSsoBinding> {

    Optional<PlatSsoBinding> findById(Long id);

    List<PlatSsoBinding> findAll();

    PlatSsoBinding saveEntity(PlatSsoBinding entity);

    boolean deleteByIds(Collection<Long> ids);
}
