// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.plat.base.service;

import com.baomidou.mybatisplus.extension.service.IService;
import com.unique.examine.plat.base.entity.PlatIdentityProvider;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

/**
 * Generated base service contract for PlatIdentityProvider.
 */
public interface PlatIdentityProviderBaseService extends IService<PlatIdentityProvider> {

    Optional<PlatIdentityProvider> findById(Long id);

    List<PlatIdentityProvider> findAll();

    PlatIdentityProvider saveEntity(PlatIdentityProvider entity);

    boolean deleteByIds(Collection<Long> ids);
}
