package com.unique.examine.web;

import com.fasterxml.jackson.databind.ObjectMapper;import com.unique.examine.core.context.ContextType;import com.unique.examine.core.id.IdService;import com.unique.examine.plat.api.AuthenticatedSession;import com.unique.examine.plat.platform.*;
import org.flywaydb.core.Flyway;import org.junit.jupiter.api.Test;import org.springframework.beans.factory.support.StaticListableBeanFactory;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.jdbc.datasource.DriverManagerDataSource;import org.testcontainers.containers.MySQLContainer;import org.testcontainers.junit.jupiter.Container;import org.testcontainers.junit.jupiter.Testcontainers;import org.testcontainers.utility.DockerImageName;
import java.nio.file.*;import java.sql.Timestamp;import java.time.Instant;import java.util.Set;import static org.assertj.core.api.Assertions.assertThat;

@Testcontainers
class PlatformFlowDashboardIntegrationTest {
 @Container static final MySQLContainer<?> MYSQL=new MySQLContainer<>(DockerImageName.parse("mysql:8.0.44")).withDatabaseName("platform_flow_dashboard").withUsername("platform_fd").withPassword("test-password").withCommand("--log-bin-trust-function-creators=1");
 @Test void publishesRunsReadsBackAndRestoresWithoutSyntheticSystemScope(){Flyway.configure().dataSource(MYSQL.getJdbcUrl(),MYSQL.getUsername(),MYSQL.getPassword()).locations("filesystem:"+migrationRoot().toString().replace('\\','/')).load().migrate();var jdbc=new JdbcTemplate(new DriverManagerDataSource(MYSQL.getJdbcUrl(),MYSQL.getUsername(),MYSQL.getPassword()));var now=Timestamp.from(Instant.parse("2026-08-07T00:00:00Z"));jdbc.update("INSERT INTO un_plat_account(id,account_code,username,username_normalized,display_name,status,created_at,updated_at,version) VALUES(1,'platform-fd','platform-fd','platform-fd','Platform FD','ACTIVE',?,?,0)",now,now);var json=new ObjectMapper();var service=new PlatformFlowDashboardService(jdbc,json,new IdService(),new StaticListableBeanFactory().getBeanProvider(com.unique.examine.core.ai.PlatformOperationsQueryFacade.ServiceHealthProvider.class));var flowDraft=json.createObjectNode();flowDraft.putArray("steps").add("VALIDATE").add("RETURN_RESULT");var flow=service.createFlow(1,new PlatformFlowDashboardRequests.Create("PLATFORM_OPS","Platform operations",null,flowDraft));assertThat(service.checkFlow(Long.parseLong(flow.id())).valid()).isTrue();var published=service.publishFlow(1,Long.parseLong(flow.id()),flow.version());var instance=service.start(1,Long.parseLong(flow.id()),json.createObjectNode().put("request","run"));assertThat(instance.status()).isEqualTo("COMPLETED");assertThat(instance.result().path("executedStepCount").asInt()).isEqualTo(2);assertThat(published.versionNumber()).isEqualTo(1);
 var dashboardDraft=json.createObjectNode();dashboardDraft.putArray("statistics").add("FLOW_RUNS");dashboardDraft.putArray("quickEntries").add("FLOW");dashboardDraft.put("includeHealth",false);var dashboard=service.createDashboard(1,new PlatformFlowDashboardRequests.Create("PLATFORM_HOME","Platform home",null,dashboardDraft));assertThat(service.checkDashboard(Long.parseLong(dashboard.id())).valid()).isTrue();service.publishDashboard(1,Long.parseLong(dashboard.id()),dashboard.version());var session=new AuthenticatedSession(9,1,ContextType.PLATFORM,null,null,null,1,Set.of("platform.dashboard.view","platform.flow.read"));var runtime=service.runtime(session);assertThat(runtime.statistics()).singleElement().satisfies(v->{assertThat(v.code()).isEqualTo("FLOW_RUNS");assertThat(v.value()).isEqualTo(1);});assertThat(runtime.quickEntries()).singleElement().satisfies(v->assertThat(v.path()).isEqualTo("/platform/flows"));assertThat(runtime.health()).isEmpty();var current=service.dashboards().getFirst();var changed=json.createObjectNode();changed.putArray("statistics");changed.putArray("quickEntries");changed.put("includeHealth",false);var saved=service.saveDashboard(1,Long.parseLong(dashboard.id()),new PlatformFlowDashboardRequests.Save("Changed",null,changed,current.version()));var restored=service.restoreDashboard(1,Long.parseLong(dashboard.id()),1,saved.version());assertThat(restored.name()).isEqualTo("Platform home");assertThat(restored.draft().path("statistics").get(0).asText()).isEqualTo("FLOW_RUNS");assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name IN ('un_platform_flow_definition','un_platform_dashboard') AND column_name IN ('system_id','tenant_id')",Integer.class)).isZero();}
 private static Path migrationRoot(){for(var p=Path.of("").toAbsolutePath();p!=null;p=p.getParent()){var c=p.resolve("sql").resolve("migration");if(Files.isDirectory(c))return c;}throw new IllegalStateException("migration root missing");}
}
