package com.unique.examine.openapi.service;

import com.unique.examine.core.api.PlatformOpenApiPrincipalFacade;import com.unique.examine.core.error.BusinessException;import com.unique.examine.core.id.IdService;
import com.unique.examine.openapi.api.*;import com.unique.examine.openapi.domain.*;import com.unique.examine.openapi.repository.PlatformOpenApiRepository;import com.unique.examine.openapi.secret.SecretRefResolver;
import org.springframework.http.HttpStatus;import org.springframework.transaction.annotation.Transactional;
import java.security.SecureRandom;import java.time.*;import java.util.*;

public class PlatformOpenApiApplicationService {
    private final PlatformOpenApiRepository repository;private final PlatformOpenApiPrincipalFacade principals;private final SecretRefResolver secrets;private final IdService ids;private final Clock clock;private final SecureRandom random=new SecureRandom();
    public PlatformOpenApiApplicationService(PlatformOpenApiRepository repository,PlatformOpenApiPrincipalFacade principals,SecretRefResolver secrets,IdService ids,Clock clock){this.repository=repository;this.principals=principals;this.secrets=secrets;this.ids=ids;this.clock=clock;}
    @Transactional public PlatformOpenApiViews.Application create(PlatformOpenApiAdminSession s,PlatformOpenApiRequests.Create r){var account=id(r.serviceAccountId(),"serviceAccountId");var scopes=scopes(r.scopes());requirePrincipal(account,scopes);validateSecret(r.secretRef());var now=clock.instant();var id=ids.nextId();var app=new PlatformOpenApiApplication(id,account,key(),r.name(),PlatformOpenApiApplication.Status.ACTIVE,scopes,ips(r.ipAllowlist()),rate(r.rateLimitPerMinute()),1,now,s.accountId(),now,s.accountId(),0);repository.insertApplication(app);repository.insertCredential(new OpenApiCredential(ids.nextId(),id,1,r.secretRef().strip(),OpenApiCredential.Status.ACTIVE,now,null,now,s.accountId()));return PlatformOpenApiViews.Application.from(repository.find(id).orElseThrow());}
    @Transactional(readOnly=true) public PlatformOpenApiViews.ApplicationPage list(PlatformOpenApiAdminSession s,int page,int size){page(page,size);return new PlatformOpenApiViews.ApplicationPage(repository.list((page-1)*size,size).stream().map(PlatformOpenApiViews.Application::from).toList(),page,size,repository.count());}
    @Transactional(readOnly=true) public PlatformOpenApiViews.Application detail(PlatformOpenApiAdminSession s,long id){return PlatformOpenApiViews.Application.from(find(id));}
    @Transactional public PlatformOpenApiViews.Application policy(PlatformOpenApiAdminSession s,long id,PlatformOpenApiRequests.Policy r){var old=find(id);requireVersion(r.version(),old.application().version());var account=id(r.serviceAccountId(),"serviceAccountId");var scopes=scopes(r.scopes());requirePrincipal(account,scopes);var a=old.application();var next=new PlatformOpenApiApplication(a.id(),account,a.appKey(),r.name(),a.status(),scopes,ips(r.ipAllowlist()),rate(r.rateLimitPerMinute()),a.currentCredentialVersion(),a.createdAt(),a.createdBy(),clock.instant(),s.accountId(),a.version()+1);if(!repository.updatePolicy(next,a.version()))conflict();return PlatformOpenApiViews.Application.from(find(id));}
    @Transactional public PlatformOpenApiViews.Application rotate(PlatformOpenApiAdminSession s,long id,PlatformOpenApiRequests.Rotate r){var old=find(id);var a=old.application();requireVersion(r.version(),a.version());validateSecret(r.secretRef());var now=clock.instant();var revoked=new OpenApiCredential(old.credential().id(),id,old.credential().credentialVersion(),old.credential().secretRef(),OpenApiCredential.Status.REVOKED,old.credential().activatedAt(),now,old.credential().createdAt(),old.credential().createdBy());var next=new OpenApiCredential(ids.nextId(),id,a.currentCredentialVersion()+1,r.secretRef().strip(),OpenApiCredential.Status.ACTIVE,now,null,now,s.accountId());var updated=new PlatformOpenApiApplication(a.id(),a.serviceAccountId(),a.appKey(),a.name(),a.status(),a.scopes(),a.ipAllowlist(),a.rateLimitPerMinute(),next.credentialVersion(),a.createdAt(),a.createdBy(),now,s.accountId(),a.version()+1);if(!repository.rotateCredential(updated,revoked,next,a.version()))conflict();return PlatformOpenApiViews.Application.from(find(id));}
    @Transactional public PlatformOpenApiViews.Application status(PlatformOpenApiAdminSession s,long id,PlatformOpenApiRequests.Status r,PlatformOpenApiApplication.Status target){var old=find(id);requireVersion(r.version(),old.application().version());if(r.reason()==null||r.reason().isBlank()||r.reason().strip().length()>500)throw bad("reason is required");if(!repository.updateStatus(id,target,s.accountId(),clock.instant(),old.application().version()))conflict();return PlatformOpenApiViews.Application.from(find(id));}
    @Transactional(readOnly=true) public PlatformOpenApiViews.CallLogPage logs(PlatformOpenApiAdminSession s,long id,String category,String method,int page,int size){find(id);page(page,size);category=enumValue(category,OpenApiCallLog.ResultCategory.class);method="ALL".equalsIgnoreCase(method)?"ALL":enumValue(method,Method.class);var total=repository.countCallLogs(id,category,method);return new PlatformOpenApiViews.CallLogPage(repository.listCallLogs(id,category,method,(page-1)*size,size).stream().map(PlatformOpenApiViews.CallLog::from).toList(),page,size,total);}
    private PlatformOpenApiRepository.ApplicationBundle find(long id){if(id<=0)throw bad("applicationId is invalid");return repository.find(id).orElseThrow(()->new BusinessException("PLATFORM_OPENAPI_APP_NOT_FOUND","Platform OpenAPI application was not found",HttpStatus.NOT_FOUND));}
    private void requirePrincipal(long account,Set<String> scopes){var p=principals.resolve(account);if(p==null||!p.accountActive())throw bad("Service account is inactive");if(!p.permissions().containsAll(scopes))throw new BusinessException("PLATFORM_OPENAPI_SCOPE_EXCEEDS_ACCOUNT","Scopes exceed service account permissions",HttpStatus.BAD_REQUEST);}
    private void validateSecret(String ref){if(ref==null||ref.isBlank()||ref.length()>512||!ref.matches("^[A-Za-z][A-Za-z0-9+.-]{1,31}:[^\\s]+$"))throw bad("secretRef is invalid");var value=secrets.resolve(ref.strip()).orElseThrow(()->bad("secretRef cannot be resolved"));Arrays.fill(value,(byte)0);}
    private String key(){var b=new byte[32];random.nextBytes(b);return Base64.getUrlEncoder().withoutPadding().encodeToString(b);}
    private static long id(String v,String n){try{var x=Long.parseLong(v);if(x<=0)throw new Exception();return x;}catch(Exception e){throw bad(n+" is invalid");}}
    private static Set<String> scopes(Set<String> v){if(v==null||v.isEmpty()||!v.equals(Set.of("platform.task.read")))throw bad("Only platform.task.read is currently supported");return Set.copyOf(v);}
    private static List<String> ips(List<String> v){return v==null?List.of():List.copyOf(v);}
    private static int rate(Integer v){if(v==null||v<1||v>60000)throw bad("rateLimitPerMinute is invalid");return v;}
    private static void page(int p,int s){if(p<1||p>10000||s<1||s>100)throw bad("page is invalid");}
    private static void requireVersion(Long v,long actual){if(v==null||v!=actual)conflict();}
    private static void conflict(){throw new BusinessException("PLATFORM_OPENAPI_VERSION_CONFLICT","Application changed concurrently",HttpStatus.CONFLICT);}
    private static BusinessException bad(String m){return new BusinessException("PLATFORM_OPENAPI_INVALID_REQUEST",m,HttpStatus.BAD_REQUEST);}
    private static <E extends Enum<E>> String enumValue(String v,Class<E> type){try{return Enum.valueOf(type,v.toUpperCase(Locale.ROOT)).name();}catch(Exception e){throw bad("filter is invalid");}}
    private enum Method{GET,HEAD,POST,PUT,PATCH,DELETE,OPTIONS}
}
