// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.plat.base.entity;

import java.time.LocalDateTime;
import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;

/**
 * Generated entity for table `un_plat_identity_provider`.
 */
@TableName("un_plat_identity_provider")
public class PlatIdentityProvider {

    public static final String TABLE_NAME = "un_plat_identity_provider";

    /**
     * Column `id`.
     */
    @TableId(value = "id", type = IdType.AUTO)
    private Long id;

    /**
     * Column `provider_code`.
     */
    private String providerCode;

    /**
     * Column `provider_name`.
     */
    private String providerName;

    /**
     * Column `protocol`.
     */
    private String protocol;

    /**
     * Column `issuer`.
     */
    private String issuer;

    /**
     * Column `client_id`.
     */
    private String clientId;

    /**
     * Column `secret_ref_id`.
     */
    private String secretRefId;

    /**
     * Column `cert_ref_id`.
     */
    private String certRefId;

    /**
     * Column `domain_whitelist`.
     */
    private String domainWhitelist;

    /**
     * Column `jit_policy`.
     */
    private String jitPolicy;

    /**
     * Column `mfa_policy`.
     */
    private String mfaPolicy;

    /**
     * Column `status`.
     */
    private Integer status;

    /**
     * Column `created_at`.
     */
    private LocalDateTime createdAt;

    /**
     * Column `updated_at`.
     */
    private LocalDateTime updatedAt;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getProviderCode() {
        return providerCode;
    }

    public void setProviderCode(String providerCode) {
        this.providerCode = providerCode;
    }

    public String getProviderName() {
        return providerName;
    }

    public void setProviderName(String providerName) {
        this.providerName = providerName;
    }

    public String getProtocol() {
        return protocol;
    }

    public void setProtocol(String protocol) {
        this.protocol = protocol;
    }

    public String getIssuer() {
        return issuer;
    }

    public void setIssuer(String issuer) {
        this.issuer = issuer;
    }

    public String getClientId() {
        return clientId;
    }

    public void setClientId(String clientId) {
        this.clientId = clientId;
    }

    public String getSecretRefId() {
        return secretRefId;
    }

    public void setSecretRefId(String secretRefId) {
        this.secretRefId = secretRefId;
    }

    public String getCertRefId() {
        return certRefId;
    }

    public void setCertRefId(String certRefId) {
        this.certRefId = certRefId;
    }

    public String getDomainWhitelist() {
        return domainWhitelist;
    }

    public void setDomainWhitelist(String domainWhitelist) {
        this.domainWhitelist = domainWhitelist;
    }

    public String getJitPolicy() {
        return jitPolicy;
    }

    public void setJitPolicy(String jitPolicy) {
        this.jitPolicy = jitPolicy;
    }

    public String getMfaPolicy() {
        return mfaPolicy;
    }

    public void setMfaPolicy(String mfaPolicy) {
        this.mfaPolicy = mfaPolicy;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

}
