// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.plat.base.entity;

import java.time.LocalDateTime;
import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;

/**
 * Generated entity for table `un_plat_data_scope_rule`.
 */
@TableName("un_plat_data_scope_rule")
public class PlatDataScopeRule {

    public static final String TABLE_NAME = "un_plat_data_scope_rule";

    /**
     * Column `id`.
     */
    @TableId(value = "id", type = IdType.AUTO)
    private Long id;

    /**
     * Column `role_id`.
     */
    private Long roleId;

    /**
     * Column `system_id`.
     */
    private Long systemId;

    /**
     * Column `tenant_id`.
     */
    private Long tenantId;

    /**
     * Column `module_id`.
     */
    private Long moduleId;

    /**
     * Column `scope_type`.
     */
    private String scopeType;

    /**
     * Column `scope_expression`.
     */
    private String scopeExpression;

    /**
     * Column `created_at`.
     */
    private LocalDateTime createdAt;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getRoleId() {
        return roleId;
    }

    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    public Long getSystemId() {
        return systemId;
    }

    public void setSystemId(Long systemId) {
        this.systemId = systemId;
    }

    public Long getTenantId() {
        return tenantId;
    }

    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    public Long getModuleId() {
        return moduleId;
    }

    public void setModuleId(Long moduleId) {
        this.moduleId = moduleId;
    }

    public String getScopeType() {
        return scopeType;
    }

    public void setScopeType(String scopeType) {
        this.scopeType = scopeType;
    }

    public String getScopeExpression() {
        return scopeExpression;
    }

    public void setScopeExpression(String scopeExpression) {
        this.scopeExpression = scopeExpression;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

}
