// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.plat.base.entity;

import java.time.LocalDateTime;
import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;

/**
 * Generated entity for table `un_plat_system_sso_policy`.
 */
@TableName("un_plat_system_sso_policy")
public class PlatSystemSsoPolicy {

    public static final String TABLE_NAME = "un_plat_system_sso_policy";

    /**
     * Column `id`.
     */
    @TableId(value = "id", type = IdType.AUTO)
    private Long id;

    /**
     * Column `system_id`.
     */
    private Long systemId;

    /**
     * Column `tenant_id`.
     */
    private Long tenantId;

    /**
     * Column `enabled_provider_ids`.
     */
    private String enabledProviderIds;

    /**
     * Column `tenant_domains`.
     */
    private String tenantDomains;

    /**
     * Column `org_mapping`.
     */
    private String orgMapping;

    /**
     * Column `employee_binding`.
     */
    private String employeeBinding;

    /**
     * Column `jit_member_policy`.
     */
    private String jitMemberPolicy;

    /**
     * Column `no_member_feedback`.
     */
    private String noMemberFeedback;

    /**
     * Column `status`.
     */
    private Integer status;

    /**
     * Column `updated_at`.
     */
    private LocalDateTime updatedAt;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getSystemId() {
        return systemId;
    }

    public void setSystemId(Long systemId) {
        this.systemId = systemId;
    }

    public Long getTenantId() {
        return tenantId;
    }

    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    public String getEnabledProviderIds() {
        return enabledProviderIds;
    }

    public void setEnabledProviderIds(String enabledProviderIds) {
        this.enabledProviderIds = enabledProviderIds;
    }

    public String getTenantDomains() {
        return tenantDomains;
    }

    public void setTenantDomains(String tenantDomains) {
        this.tenantDomains = tenantDomains;
    }

    public String getOrgMapping() {
        return orgMapping;
    }

    public void setOrgMapping(String orgMapping) {
        this.orgMapping = orgMapping;
    }

    public String getEmployeeBinding() {
        return employeeBinding;
    }

    public void setEmployeeBinding(String employeeBinding) {
        this.employeeBinding = employeeBinding;
    }

    public String getJitMemberPolicy() {
        return jitMemberPolicy;
    }

    public void setJitMemberPolicy(String jitMemberPolicy) {
        this.jitMemberPolicy = jitMemberPolicy;
    }

    public String getNoMemberFeedback() {
        return noMemberFeedback;
    }

    public void setNoMemberFeedback(String noMemberFeedback) {
        this.noMemberFeedback = noMemberFeedback;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

}
