// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.messagelog.base.entity;

import java.time.LocalDateTime;
import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;

/**
 * Generated entity for table `un_audit_login_log`.
 */
@TableName("un_audit_login_log")
public class AuditLoginLog {

    public static final String TABLE_NAME = "un_audit_login_log";

    /**
     * Column `id`.
     */
    @TableId(value = "id", type = IdType.AUTO)
    private Long id;

    /**
     * Column `account_id`.
     */
    private Long accountId;

    /**
     * Column `system_id`.
     */
    private Long systemId;

    /**
     * Column `tenant_id`.
     */
    private Long tenantId;

    /**
     * Column `identity_provider`.
     */
    private String identityProvider;

    /**
     * Column `external_user_id`.
     */
    private String externalUserId;

    /**
     * Column `auth_method`.
     */
    private String authMethod;

    /**
     * Column `mfa_result`.
     */
    private String mfaResult;

    /**
     * Column `account_binding_result`.
     */
    private String accountBindingResult;

    /**
     * Column `member_mapping_result`.
     */
    private String memberMappingResult;

    /**
     * Column `login_result`.
     */
    private String loginResult;

    /**
     * Column `failure_reason`.
     */
    private String failureReason;

    /**
     * Column `ip`.
     */
    private String ip;

    /**
     * Column `device`.
     */
    private String device;

    /**
     * Column `request_id`.
     */
    private String requestId;

    /**
     * Column `trace_id`.
     */
    private String traceId;

    /**
     * Column `created_at`.
     */
    private LocalDateTime createdAt;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getAccountId() {
        return accountId;
    }

    public void setAccountId(Long accountId) {
        this.accountId = accountId;
    }

    public Long getSystemId() {
        return systemId;
    }

    public void setSystemId(Long systemId) {
        this.systemId = systemId;
    }

    public Long getTenantId() {
        return tenantId;
    }

    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    public String getIdentityProvider() {
        return identityProvider;
    }

    public void setIdentityProvider(String identityProvider) {
        this.identityProvider = identityProvider;
    }

    public String getExternalUserId() {
        return externalUserId;
    }

    public void setExternalUserId(String externalUserId) {
        this.externalUserId = externalUserId;
    }

    public String getAuthMethod() {
        return authMethod;
    }

    public void setAuthMethod(String authMethod) {
        this.authMethod = authMethod;
    }

    public String getMfaResult() {
        return mfaResult;
    }

    public void setMfaResult(String mfaResult) {
        this.mfaResult = mfaResult;
    }

    public String getAccountBindingResult() {
        return accountBindingResult;
    }

    public void setAccountBindingResult(String accountBindingResult) {
        this.accountBindingResult = accountBindingResult;
    }

    public String getMemberMappingResult() {
        return memberMappingResult;
    }

    public void setMemberMappingResult(String memberMappingResult) {
        this.memberMappingResult = memberMappingResult;
    }

    public String getLoginResult() {
        return loginResult;
    }

    public void setLoginResult(String loginResult) {
        this.loginResult = loginResult;
    }

    public String getFailureReason() {
        return failureReason;
    }

    public void setFailureReason(String failureReason) {
        this.failureReason = failureReason;
    }

    public String getIp() {
        return ip;
    }

    public void setIp(String ip) {
        this.ip = ip;
    }

    public String getDevice() {
        return device;
    }

    public void setDevice(String device) {
        this.device = device;
    }

    public String getRequestId() {
        return requestId;
    }

    public void setRequestId(String requestId) {
        this.requestId = requestId;
    }

    public String getTraceId() {
        return traceId;
    }

    public void setTraceId(String traceId) {
        this.traceId = traceId;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

}
