// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.messagelog.base.entity;

import java.time.LocalDateTime;
import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;

/**
 * Generated entity for table `un_audit_business_log`.
 */
@TableName("un_audit_business_log")
public class AuditBusinessLog {

    public static final String TABLE_NAME = "un_audit_business_log";

    /**
     * Column `id`.
     */
    @TableId(value = "id", type = IdType.AUTO)
    private Long id;

    /**
     * Column `log_type`.
     */
    private String logType;

    /**
     * Column `scope`.
     */
    private String scope;

    /**
     * Column `system_id`.
     */
    private Long systemId;

    /**
     * Column `tenant_id`.
     */
    private Long tenantId;

    /**
     * Column `operator_id`.
     */
    private Long operatorId;

    /**
     * Column `action_code`.
     */
    private String actionCode;

    /**
     * Column `object_type`.
     */
    private String objectType;

    /**
     * Column `object_id`.
     */
    private String objectId;

    /**
     * Column `result`.
     */
    private String result;

    /**
     * Column `request_id`.
     */
    private String requestId;

    /**
     * Column `trace_id`.
     */
    private String traceId;

    /**
     * Column `audit_log_id`.
     */
    private String auditLogId;

    /**
     * Column `ip`.
     */
    private String ip;

    /**
     * Column `device`.
     */
    private String device;

    /**
     * Column `field_diff`.
     */
    private String fieldDiff;

    /**
     * Column `permission_snapshot`.
     */
    private String permissionSnapshot;

    /**
     * Column `desensitize_result`.
     */
    private String desensitizeResult;

    /**
     * Column `failure_reason`.
     */
    private String failureReason;

    /**
     * Column `created_at`.
     */
    private LocalDateTime createdAt;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getLogType() {
        return logType;
    }

    public void setLogType(String logType) {
        this.logType = logType;
    }

    public String getScope() {
        return scope;
    }

    public void setScope(String scope) {
        this.scope = scope;
    }

    public Long getSystemId() {
        return systemId;
    }

    public void setSystemId(Long systemId) {
        this.systemId = systemId;
    }

    public Long getTenantId() {
        return tenantId;
    }

    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    public Long getOperatorId() {
        return operatorId;
    }

    public void setOperatorId(Long operatorId) {
        this.operatorId = operatorId;
    }

    public String getActionCode() {
        return actionCode;
    }

    public void setActionCode(String actionCode) {
        this.actionCode = actionCode;
    }

    public String getObjectType() {
        return objectType;
    }

    public void setObjectType(String objectType) {
        this.objectType = objectType;
    }

    public String getObjectId() {
        return objectId;
    }

    public void setObjectId(String objectId) {
        this.objectId = objectId;
    }

    public String getResult() {
        return result;
    }

    public void setResult(String result) {
        this.result = result;
    }

    public String getRequestId() {
        return requestId;
    }

    public void setRequestId(String requestId) {
        this.requestId = requestId;
    }

    public String getTraceId() {
        return traceId;
    }

    public void setTraceId(String traceId) {
        this.traceId = traceId;
    }

    public String getAuditLogId() {
        return auditLogId;
    }

    public void setAuditLogId(String auditLogId) {
        this.auditLogId = auditLogId;
    }

    public String getIp() {
        return ip;
    }

    public void setIp(String ip) {
        this.ip = ip;
    }

    public String getDevice() {
        return device;
    }

    public void setDevice(String device) {
        this.device = device;
    }

    public String getFieldDiff() {
        return fieldDiff;
    }

    public void setFieldDiff(String fieldDiff) {
        this.fieldDiff = fieldDiff;
    }

    public String getPermissionSnapshot() {
        return permissionSnapshot;
    }

    public void setPermissionSnapshot(String permissionSnapshot) {
        this.permissionSnapshot = permissionSnapshot;
    }

    public String getDesensitizeResult() {
        return desensitizeResult;
    }

    public void setDesensitizeResult(String desensitizeResult) {
        this.desensitizeResult = desensitizeResult;
    }

    public String getFailureReason() {
        return failureReason;
    }

    public void setFailureReason(String failureReason) {
        this.failureReason = failureReason;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

}
