import type {
  AccountStatus,
  AppStatus,
  DataScopeType,
  DynamicFieldType,
  ExportJobStatus,
  FieldStatus,
  FileStatus,
  FilterOperator,
  FlowInstanceStatus,
  FlowTaskStatus,
  FlowTemplateStatus,
  ModuleStatus,
  OpenApiClientStatus,
  RecordStatus,
  SortDirection,
  SystemStatus,
  TenantStatus,
  VersionStatus,
} from "./types";

export const DYNAMIC_FIELD_TYPES = [
  "TEXT",
  "TEXTAREA",
  "NUMBER",
  "MONEY",
  "DATE",
  "DATETIME",
  "SELECT",
  "MULTI_SELECT",
  "SWITCH",
  "MEMBER",
  "DEPT",
  "ATTACHMENT",
  "IMAGE",
  "AUTO_NO",
  "RELATION",
  "SUB_TABLE",
  "ADDRESS",
  "TAG",
  "JSON",
] as const satisfies readonly DynamicFieldType[];

export const FILTER_OPERATORS = [
  "EQ",
  "NE",
  "LIKE",
  "IN",
  "BETWEEN",
  "GT",
  "GE",
  "LT",
  "LE",
  "IS_NULL",
  "NOT_NULL",
] as const satisfies readonly FilterOperator[];

export const SORT_DIRECTIONS = ["ASC", "DESC"] as const satisfies readonly SortDirection[];
export const DATA_SCOPE_TYPES = ["SELF", "DEPT", "DEPT_TREE", "ALL", "CUSTOM"] as const satisfies readonly DataScopeType[];

export const STATUS_VALUES = {
  accountStatus: ["NORMAL", "DISABLED", "LOCKED"] as const satisfies readonly AccountStatus[],
  systemStatus: ["DRAFT", "ENABLED", "DISABLED", "ARCHIVED"] as const satisfies readonly SystemStatus[],
  tenantStatus: ["ENABLED", "DISABLED"] as const satisfies readonly TenantStatus[],
  appStatus: ["DRAFT", "ENABLED", "DISABLED", "ARCHIVED"] as const satisfies readonly AppStatus[],
  moduleStatus: ["DRAFT", "PUBLISHED", "DISABLED", "ARCHIVED"] as const satisfies readonly ModuleStatus[],
  fieldStatus: ["DRAFT", "ENABLED", "DISABLED", "DELETED"] as const satisfies readonly FieldStatus[],
  versionStatus: ["DRAFT", "PUBLISHED", "DISCARDED"] as const satisfies readonly VersionStatus[],
  recordStatus: [
    "DRAFT",
    "SUBMITTED",
    "IN_APPROVAL",
    "APPROVED",
    "REJECTED",
    "WITHDRAWN",
    "ARCHIVED",
    "DELETED",
  ] as const satisfies readonly RecordStatus[],
  flowTemplateStatus: ["DRAFT", "PUBLISHED", "DISABLED"] as const satisfies readonly FlowTemplateStatus[],
  flowInstanceStatus: ["IN_APPROVAL", "APPROVED", "REJECTED", "WITHDRAWN", "TERMINATED"] as const satisfies readonly FlowInstanceStatus[],
  flowTaskStatus: ["PENDING", "DONE", "CANCELED", "TRANSFERRED", "RETURNED"] as const satisfies readonly FlowTaskStatus[],
  fileStatus: ["TEMP", "REFERENCED", "DELETED", "EXPIRED"] as const satisfies readonly FileStatus[],
  exportJobStatus: ["QUEUED", "PROCESSING", "SUCCESS", "FAILED", "CANCELED"] as const satisfies readonly ExportJobStatus[],
  openApiClientStatus: ["DRAFT", "ENABLED", "DISABLED", "EXPIRED"] as const satisfies readonly OpenApiClientStatus[],
} as const;

export const IDEMPOTENCY_REQUIRED_API_IDS = [
  "PLAT-002",
  "APP-002",
  "MOD-002",
  "FIELD-002",
  "MOD-006",
  "UI-008",
  "RUN-004",
  "RUN-006",
  "RUN-008",
  "FLOW-005",
  "FLOW-009",
  "FLOW-010",
  "FLOW-013",
  "FLOW-015",
  "FLOW-016",
  "FILE-001",
  "EXP-004",
  "EXP-007",
  "EXP-008",
  "OPM-002",
  "OPM-005",
  "OPN-003",
  "OPN-004",
  "OPN-005",
  "OPN-006",
] as const;

export type IdempotencyRequiredApiId = (typeof IDEMPOTENCY_REQUIRED_API_IDS)[number];
