// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.plat.base.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.unique.examine.plat.base.entity.PlatPermissionVersion;

import org.apache.ibatis.annotations.Mapper;

/**
 * Generated mapper contract for table `un_plat_permission_version`.
 */
@Mapper
public interface PlatPermissionVersionMapper extends BaseMapper<PlatPermissionVersion> {

    String TABLE_NAME = PlatPermissionVersion.TABLE_NAME;
}
