// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.plat.base.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.unique.examine.plat.base.entity.PlatAccountMemberBinding;

import org.apache.ibatis.annotations.Mapper;

/**
 * Generated mapper contract for table `un_plat_account_member_binding`.
 */
@Mapper
public interface PlatAccountMemberBindingMapper extends BaseMapper<PlatAccountMemberBinding> {

    String TABLE_NAME = PlatAccountMemberBinding.TABLE_NAME;
}
