// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.plat.base.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.unique.examine.plat.base.entity.PlatRoleFieldPermission;

import org.apache.ibatis.annotations.Mapper;

/**
 * Generated mapper contract for table `un_plat_role_field_permission`.
 */
@Mapper
public interface PlatRoleFieldPermissionMapper extends BaseMapper<PlatRoleFieldPermission> {

    String TABLE_NAME = PlatRoleFieldPermission.TABLE_NAME;
}
