// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.plat.base.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.unique.examine.plat.base.entity.PlatRoleMember;

import org.apache.ibatis.annotations.Mapper;

/**
 * Generated mapper contract for table `un_plat_role_member`.
 */
@Mapper
public interface PlatRoleMemberMapper extends BaseMapper<PlatRoleMember> {

    String TABLE_NAME = PlatRoleMember.TABLE_NAME;
}
