// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.plat.base.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.unique.examine.plat.base.entity.PlatRole;

import org.apache.ibatis.annotations.Mapper;

/**
 * Generated mapper contract for table `un_plat_role`.
 */
@Mapper
public interface PlatRoleMapper extends BaseMapper<PlatRole> {

    String TABLE_NAME = PlatRole.TABLE_NAME;
}
