// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.plat.base.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.unique.examine.plat.base.entity.PlatTenant;

import org.apache.ibatis.annotations.Mapper;

/**
 * Generated mapper contract for table `un_plat_tenant`.
 */
@Mapper
public interface PlatTenantMapper extends BaseMapper<PlatTenant> {

    String TABLE_NAME = PlatTenant.TABLE_NAME;
}
