// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.plat.base.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.unique.examine.plat.base.entity.PlatAccount;

import org.apache.ibatis.annotations.Mapper;

/**
 * Generated mapper contract for table `un_plat_account`.
 */
@Mapper
public interface PlatAccountMapper extends BaseMapper<PlatAccount> {

    String TABLE_NAME = PlatAccount.TABLE_NAME;
}
