// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.plat.base.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.unique.examine.plat.base.entity.PlatDenyPolicy;

import org.apache.ibatis.annotations.Mapper;

/**
 * Generated mapper contract for table `un_plat_deny_policy`.
 */
@Mapper
public interface PlatDenyPolicyMapper extends BaseMapper<PlatDenyPolicy> {

    String TABLE_NAME = PlatDenyPolicy.TABLE_NAME;
}
