// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.app.base.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.unique.examine.app.base.entity.OpenapiCallLog;

import org.apache.ibatis.annotations.Mapper;

/**
 * Generated mapper contract for table `un_openapi_call_log`.
 */
@Mapper
public interface OpenapiCallLogMapper extends BaseMapper<OpenapiCallLog> {

    String TABLE_NAME = OpenapiCallLog.TABLE_NAME;
}
