// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.operations.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.operations.base.entity.OpsBackup;
import com.unique.unexamine.operations.base.mapper.OpsBackupMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class OpsBackupBaseService {
    private final OpsBackupMapper mapper;

    public OpsBackupBaseService(OpsBackupMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(OpsBackup entity) {
        return mapper.insert(entity);
    }

    public OpsBackup selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<OpsBackup> selectList(Wrapper<OpsBackup> query) {
        return mapper.selectList(query);
    }

    public int updateById(OpsBackup entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
