// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.operations.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.operations.base.entity.OpsDeployment;
import com.unique.unexamine.operations.base.mapper.OpsDeploymentMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class OpsDeploymentBaseService {
    private final OpsDeploymentMapper mapper;

    public OpsDeploymentBaseService(OpsDeploymentMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(OpsDeployment entity) {
        return mapper.insert(entity);
    }

    public OpsDeployment selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<OpsDeployment> selectList(Wrapper<OpsDeployment> query) {
        return mapper.selectList(query);
    }

    public int updateById(OpsDeployment entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
