// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.operations.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.operations.base.entity.OpsRestoreDrill;
import com.unique.unexamine.operations.base.mapper.OpsRestoreDrillMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class OpsRestoreDrillBaseService {
    private final OpsRestoreDrillMapper mapper;

    public OpsRestoreDrillBaseService(OpsRestoreDrillMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(OpsRestoreDrill entity) {
        return mapper.insert(entity);
    }

    public OpsRestoreDrill selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<OpsRestoreDrill> selectList(Wrapper<OpsRestoreDrill> query) {
        return mapper.selectList(query);
    }

    public int updateById(OpsRestoreDrill entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
