// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.operations.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.operations.base.entity.OpsSecretRotation;
import com.unique.unexamine.operations.base.mapper.OpsSecretRotationMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class OpsSecretRotationBaseService {
    private final OpsSecretRotationMapper mapper;

    public OpsSecretRotationBaseService(OpsSecretRotationMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(OpsSecretRotation entity) {
        return mapper.insert(entity);
    }

    public OpsSecretRotation selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<OpsSecretRotation> selectList(Wrapper<OpsSecretRotation> query) {
        return mapper.selectList(query);
    }

    public int updateById(OpsSecretRotation entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
