// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.operations.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.operations.base.entity.OpsSecretRef;
import com.unique.unexamine.operations.base.mapper.OpsSecretRefMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class OpsSecretRefBaseService {
    private final OpsSecretRefMapper mapper;

    public OpsSecretRefBaseService(OpsSecretRefMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(OpsSecretRef entity) {
        return mapper.insert(entity);
    }

    public OpsSecretRef selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<OpsSecretRef> selectList(Wrapper<OpsSecretRef> query) {
        return mapper.selectList(query);
    }

    public int updateById(OpsSecretRef entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
