// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.operations.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.operations.base.entity.OpsUpgrade;
import com.unique.unexamine.operations.base.mapper.OpsUpgradeMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class OpsUpgradeBaseService {
    private final OpsUpgradeMapper mapper;

    public OpsUpgradeBaseService(OpsUpgradeMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(OpsUpgrade entity) {
        return mapper.insert(entity);
    }

    public OpsUpgrade selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<OpsUpgrade> selectList(Wrapper<OpsUpgrade> query) {
        return mapper.selectList(query);
    }

    public int updateById(OpsUpgrade entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
