// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.operations.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.operations.base.entity.OpsVerificationFinding;
import com.unique.unexamine.operations.base.mapper.OpsVerificationFindingMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class OpsVerificationFindingBaseService {
    private final OpsVerificationFindingMapper mapper;

    public OpsVerificationFindingBaseService(OpsVerificationFindingMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(OpsVerificationFinding entity) {
        return mapper.insert(entity);
    }

    public OpsVerificationFinding selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<OpsVerificationFinding> selectList(Wrapper<OpsVerificationFinding> query) {
        return mapper.selectList(query);
    }

    public int updateById(OpsVerificationFinding entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
