// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.operations.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.operations.base.entity.OpsVerificationRun;
import com.unique.unexamine.operations.base.mapper.OpsVerificationRunMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class OpsVerificationRunBaseService {
    private final OpsVerificationRunMapper mapper;

    public OpsVerificationRunBaseService(OpsVerificationRunMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(OpsVerificationRun entity) {
        return mapper.insert(entity);
    }

    public OpsVerificationRun selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<OpsVerificationRun> selectList(Wrapper<OpsVerificationRun> query) {
        return mapper.selectList(query);
    }

    public int updateById(OpsVerificationRun entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
