// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.notification.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.notification.base.entity.MsgDelivery;
import com.unique.unexamine.notification.base.mapper.MsgDeliveryMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class MsgDeliveryBaseService {
    private final MsgDeliveryMapper mapper;

    public MsgDeliveryBaseService(MsgDeliveryMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(MsgDelivery entity) {
        return mapper.insert(entity);
    }

    public MsgDelivery selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<MsgDelivery> selectList(Wrapper<MsgDelivery> query) {
        return mapper.selectList(query);
    }

    public int updateById(MsgDelivery entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
