// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.notification.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.notification.base.entity.MsgRecipient;
import com.unique.unexamine.notification.base.mapper.MsgRecipientMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class MsgRecipientBaseService {
    private final MsgRecipientMapper mapper;

    public MsgRecipientBaseService(MsgRecipientMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(MsgRecipient entity) {
        return mapper.insert(entity);
    }

    public MsgRecipient selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<MsgRecipient> selectList(Wrapper<MsgRecipient> query) {
        return mapper.selectList(query);
    }

    public int updateById(MsgRecipient entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
