// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.notification.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.notification.base.entity.MsgTemplate;
import com.unique.unexamine.notification.base.mapper.MsgTemplateMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class MsgTemplateBaseService {
    private final MsgTemplateMapper mapper;

    public MsgTemplateBaseService(MsgTemplateMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(MsgTemplate entity) {
        return mapper.insert(entity);
    }

    public MsgTemplate selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<MsgTemplate> selectList(Wrapper<MsgTemplate> query) {
        return mapper.selectList(query);
    }

    public int updateById(MsgTemplate entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
