// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.core.base.service.impl;

import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.unique.examine.core.base.entity.OpsApiCachePolicy;
import com.unique.examine.core.base.mapper.OpsApiCachePolicyMapper;
import com.unique.examine.core.base.service.OpsApiCachePolicyBaseService;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

import org.springframework.stereotype.Service;

/**
 * Generated MyBatis-Plus base service implementation for OpsApiCachePolicy.
 */
@Service
public class OpsApiCachePolicyBaseServiceImpl extends ServiceImpl<OpsApiCachePolicyMapper, OpsApiCachePolicy> implements OpsApiCachePolicyBaseService {

    @Override
    public Optional<OpsApiCachePolicy> findById(Long id) {
        return Optional.ofNullable(getById(id));
    }

    @Override
    public List<OpsApiCachePolicy> findAll() {
        return list();
    }

    @Override
    public OpsApiCachePolicy saveEntity(OpsApiCachePolicy entity) {
        saveOrUpdate(entity);
        return entity;
    }

    @Override
    public boolean deleteByIds(Collection<Long> ids) {
        return ids != null && !ids.isEmpty() && removeBatchByIds(ids);
    }
}
