// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.core.base.service.impl;

import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.unique.examine.core.base.entity.OpsDeployment;
import com.unique.examine.core.base.mapper.OpsDeploymentMapper;
import com.unique.examine.core.base.service.OpsDeploymentBaseService;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

import org.springframework.stereotype.Service;

/**
 * Generated MyBatis-Plus base service implementation for OpsDeployment.
 */
@Service
public class OpsDeploymentBaseServiceImpl extends ServiceImpl<OpsDeploymentMapper, OpsDeployment> implements OpsDeploymentBaseService {

    @Override
    public Optional<OpsDeployment> findById(Long id) {
        return Optional.ofNullable(getById(id));
    }

    @Override
    public List<OpsDeployment> findAll() {
        return list();
    }

    @Override
    public OpsDeployment saveEntity(OpsDeployment entity) {
        saveOrUpdate(entity);
        return entity;
    }

    @Override
    public boolean deleteByIds(Collection<Long> ids) {
        return ids != null && !ids.isEmpty() && removeBatchByIds(ids);
    }
}
