// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.core.base.service.impl;

import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.unique.examine.core.base.entity.OpsFeatureFlag;
import com.unique.examine.core.base.mapper.OpsFeatureFlagMapper;
import com.unique.examine.core.base.service.OpsFeatureFlagBaseService;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

import org.springframework.stereotype.Service;

/**
 * Generated MyBatis-Plus base service implementation for OpsFeatureFlag.
 */
@Service
public class OpsFeatureFlagBaseServiceImpl extends ServiceImpl<OpsFeatureFlagMapper, OpsFeatureFlag> implements OpsFeatureFlagBaseService {

    @Override
    public Optional<OpsFeatureFlag> findById(Long id) {
        return Optional.ofNullable(getById(id));
    }

    @Override
    public List<OpsFeatureFlag> findAll() {
        return list();
    }

    @Override
    public OpsFeatureFlag saveEntity(OpsFeatureFlag entity) {
        saveOrUpdate(entity);
        return entity;
    }

    @Override
    public boolean deleteByIds(Collection<Long> ids) {
        return ids != null && !ids.isEmpty() && removeBatchByIds(ids);
    }
}
