// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.core.base.service.impl;

import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.unique.examine.core.base.entity.OpsHealthCheck;
import com.unique.examine.core.base.mapper.OpsHealthCheckMapper;
import com.unique.examine.core.base.service.OpsHealthCheckBaseService;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

import org.springframework.stereotype.Service;

/**
 * Generated MyBatis-Plus base service implementation for OpsHealthCheck.
 */
@Service
public class OpsHealthCheckBaseServiceImpl extends ServiceImpl<OpsHealthCheckMapper, OpsHealthCheck> implements OpsHealthCheckBaseService {

    @Override
    public Optional<OpsHealthCheck> findById(Long id) {
        return Optional.ofNullable(getById(id));
    }

    @Override
    public List<OpsHealthCheck> findAll() {
        return list();
    }

    @Override
    public OpsHealthCheck saveEntity(OpsHealthCheck entity) {
        saveOrUpdate(entity);
        return entity;
    }

    @Override
    public boolean deleteByIds(Collection<Long> ids) {
        if (ids == null || ids.isEmpty()) {
            return false;
        }
        return removeBatchByIds(ids);
    }
}
