// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.core.base.service.impl;

import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.unique.examine.core.base.entity.OpsQuota;
import com.unique.examine.core.base.mapper.OpsQuotaMapper;
import com.unique.examine.core.base.service.OpsQuotaBaseService;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

import org.springframework.stereotype.Service;

/**
 * Generated MyBatis-Plus base service implementation for OpsQuota.
 */
@Service
public class OpsQuotaBaseServiceImpl extends ServiceImpl<OpsQuotaMapper, OpsQuota> implements OpsQuotaBaseService {

    @Override
    public Optional<OpsQuota> findById(Long id) {
        return Optional.ofNullable(getById(id));
    }

    @Override
    public List<OpsQuota> findAll() {
        return list();
    }

    @Override
    public OpsQuota saveEntity(OpsQuota entity) {
        saveOrUpdate(entity);
        return entity;
    }

    @Override
    public boolean deleteByIds(Collection<Long> ids) {
        if (ids == null || ids.isEmpty()) {
            return false;
        }
        return removeBatchByIds(ids);
    }
}
