// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.core.base.service.impl;

import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.unique.examine.core.base.entity.SysAsyncTaskFile;
import com.unique.examine.core.base.mapper.SysAsyncTaskFileMapper;
import com.unique.examine.core.base.service.SysAsyncTaskFileBaseService;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

import org.springframework.stereotype.Service;

/**
 * Generated MyBatis-Plus base service implementation for SysAsyncTaskFile.
 */
@Service
public class SysAsyncTaskFileBaseServiceImpl extends ServiceImpl<SysAsyncTaskFileMapper, SysAsyncTaskFile> implements SysAsyncTaskFileBaseService {

    @Override
    public Optional<SysAsyncTaskFile> findById(Long id) {
        return Optional.ofNullable(getById(id));
    }

    @Override
    public List<SysAsyncTaskFile> findAll() {
        return list();
    }

    @Override
    public SysAsyncTaskFile saveEntity(SysAsyncTaskFile entity) {
        saveOrUpdate(entity);
        return entity;
    }

    @Override
    public boolean deleteByIds(Collection<Long> ids) {
        return ids != null && !ids.isEmpty() && removeBatchByIds(ids);
    }
}
