// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.core.base.service.impl;

import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.unique.examine.core.base.entity.SysIdempotencyKey;
import com.unique.examine.core.base.mapper.SysIdempotencyKeyMapper;
import com.unique.examine.core.base.service.SysIdempotencyKeyBaseService;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

import org.springframework.stereotype.Service;

/**
 * Generated MyBatis-Plus base service implementation for SysIdempotencyKey.
 */
@Service
public class SysIdempotencyKeyBaseServiceImpl extends ServiceImpl<SysIdempotencyKeyMapper, SysIdempotencyKey> implements SysIdempotencyKeyBaseService {

    @Override
    public Optional<SysIdempotencyKey> findById(Long id) {
        return Optional.ofNullable(getById(id));
    }

    @Override
    public List<SysIdempotencyKey> findAll() {
        return list();
    }

    @Override
    public SysIdempotencyKey saveEntity(SysIdempotencyKey entity) {
        saveOrUpdate(entity);
        return entity;
    }

    @Override
    public boolean deleteByIds(Collection<Long> ids) {
        return ids != null && !ids.isEmpty() && removeBatchByIds(ids);
    }
}
