// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.core.base.service.impl;

import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.unique.examine.core.base.entity.SysSecretRotationJob;
import com.unique.examine.core.base.mapper.SysSecretRotationJobMapper;
import com.unique.examine.core.base.service.SysSecretRotationJobBaseService;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

import org.springframework.stereotype.Service;

/**
 * Generated MyBatis-Plus base service implementation for SysSecretRotationJob.
 */
@Service
public class SysSecretRotationJobBaseServiceImpl extends ServiceImpl<SysSecretRotationJobMapper, SysSecretRotationJob> implements SysSecretRotationJobBaseService {

    @Override
    public Optional<SysSecretRotationJob> findById(Long id) {
        return Optional.ofNullable(getById(id));
    }

    @Override
    public List<SysSecretRotationJob> findAll() {
        return list();
    }

    @Override
    public SysSecretRotationJob saveEntity(SysSecretRotationJob entity) {
        saveOrUpdate(entity);
        return entity;
    }

    @Override
    public boolean deleteByIds(Collection<Long> ids) {
        return ids != null && !ids.isEmpty() && removeBatchByIds(ids);
    }
}
