###
POST http://localhost:9099/adminFile/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary
Admin-Token: 42aec31a-2fe1-40e6-bd56-b3384d28f5b9

--WebAppBoundary
Content-Disposition: form-data; name="batchId"
Content-Type: text/plain

d0eec9ab6e8a462f8c708257660304d7
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="zh-CN.languagePack.xls"
Content-Type: application/vnd.ms-excel

< D:\download\zh-CN.languagePack.xls
--WebAppBoundary--

####################################
### admin相关
####################################
###
POST http://localhost:9099/moduleAdmin/doLogin
Content-Type: application/json

{"username": "admin","password": "123123aa","deviceType": "0","loginType": "0"}


###
POST http://localhost:9099/moduleAdmin/auth
Content-Type: application/json
satoken: e0c88891-6716-4e1b-84ef-675a09a14c52

{}


###
GET http://localhost:9099/user/isLogin
Content-Type: application/json

####################################
### module相关
####################################
###
POST http://localhost:9099/moduleField/queryFieldAdd?type=1&moduleId=4
Content-Type: application/json
satoken: 42aec31a-2fe1-40e6-bd56-b3384d28f5b9


###
POST http://localhost:9099/module/queryPageList
Content-Type: application/json
satoken: 42aec31a-2fe1-40e6-bd56-b3384d28f5b9

{"keyword":"","moduleId":4,"page":1,"limit":10,"pageType":0}

###
POST http://localhost:9099/module/queryPageListTree
Content-Type: application/json
satoken: 42aec31a-2fe1-40e6-bd56-b3384d28f5b9

{"keyword":"","moduleId":4,"page":1,"limit":10,"pageType":0}



####################################
### 模块数据
####################################
###
POST http://localhost:9099/moduleRecord/add
Content-Type: application/json
satoken: 42aec31a-2fe1-40e6-bd56-b3384d28f5b9

{
  "moduleId": 4,
  "entity": {"num": "11111","name": "x11111","fielddecimal1": "5000","owner_user_id": "5000"},
  "fieldList": [{"id":"12","moduleId":"4","fieldName":"fielddecimal1","name":"金额","type":6,"value":5000}]
}

###
POST http://localhost:9099/moduleRecord/update
Content-Type: application/json
satoken: 42aec31a-2fe1-40e6-bd56-b3384d28f5b9

{
  "moduleId": 4,
  "entity": {"id": "1798543235782676480","num": "11111234","name": "x1111123"},
  "fieldList": [{"id":"12","moduleId":"4","fieldName":"fielddecimal1","name":"金额","type":6,"value":50001}]
}
###
POST http://localhost:9099/moduleRecord/queryById/1801153956043427840
Content-Type: application/json
satoken: 42aec31a-2fe1-40e6-bd56-b3384d28f5b9

{}

###
POST http://localhost:9099/moduleRecord/information/2
Content-Type: application/json
satoken: 42aec31a-2fe1-40e6-bd56-b3384d28f5b9

{}
###
POST http://localhost:9099/moduleRecord/queryPageList
Content-Type: application/json
satoken: 42aec31a-2fe1-40e6-bd56-b3384d28f5b9

{"keyword":"","moduleId":4,"page":1,"limit":10,"pageType":0}


####
#POST http://localhost:9099/moduleRecord/queryFieldAdd?type=1
#Content-Type: application/json
#satoken: 42aec31a-2fe1-40e6-bd56-b3384d28f5b9
#
#{}
####################################
### 用户使用业务相关
####################################
###
POST http://localhost:9099/moduleFieldUser/queryFieldHead?moduleId=7
Content-Type: application/json
satoken: 42aec31a-2fe1-40e6-bd56-b3384d28f5b9

{}

###
POST http://localhost:9099/moduleFieldUser/queryFieldSearch?moduleId=4
Content-Type: application/json
satoken: 42aec31a-2fe1-40e6-bd56-b3384d28f5b9

{}

####################################
### 审批相关
####################################
###
POST http://localhost:9099/examine/queryPageList
Content-Type: application/json
satoken: 42aec31a-2fe1-40e6-bd56-b3384d28f5b9

{"keyword":"","moduleId":4,"page":1,"limit":10,"pageType":0}