###
POST http://{{host}}/adminFile/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary
Admin-Token: {{token}}

--WebAppBoundary
Content-Disposition: form-data; name="batchId"
Content-Type: text/plain

d0eec9ab6e8a462f8c708257660304d7
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="zh-CN.languagePack.xls"
Content-Type: application/vnd.ms-excel

< D:\download\zh-CN.languagePack.xls
--WebAppBoundary--

####################################
### admin相关
####################################
###
POST http://{{host}}/user/doLogin
Content-Type: application/json

{"username": "admin","password": "123123aa","deviceType": "0","loginType": "0"}


###
GET http://{{host}}/user/isLogin
Content-Type: application/json

####################################
### module相关
####################################
###
POST http://{{host}}/moduleField/queryFieldAdd?type=1&moduleId=4
Content-Type: application/json
satoken: {{token}}


###
POST http://{{host}}/module/queryPageList
Content-Type: application/json
satoken: {{token}}

{"keyword":"","moduleId":4,"page":1,"limit":10,"pageType":0}



####################################
### 模块数据
####################################
###
POST http://{{host}}/moduleRecord/add
Content-Type: application/json
satoken: {{token}}

{
  "moduleId": 4,
  "entity": {"num": "11111","name": "x11111","fielddecimal1": "5000","owner_user_id": "5000"},
  "fieldList": [{"id":"12","moduleId":"4","fieldName":"fielddecimal1","name":"金额","type":6,"value":5000}]
}

###
POST http://{{host}}/moduleRecord/update
Content-Type: application/json
satoken: {{token}}

{
  "moduleId": 4,
  "entity": {"id": "1798543235782676480","num": "11111234","name": "x1111123"},
  "fieldList": [{"id":"12","moduleId":"4","fieldName":"fielddecimal1","name":"金额","type":6,"value":50001}]
}
###
POST http://{{host}}/moduleRecord/queryById/2
Content-Type: application/json
satoken: {{token}}

{}

###
POST http://{{host}}/moduleRecord/information/2
Content-Type: application/json
satoken: {{token}}

{}
###
POST http://{{host}}/moduleRecord/queryPageList
Content-Type: application/json
satoken: {{token}}

{"keyword":"","moduleId":7,"page":1,"limit":10,"pageType":0}


####
#POST http://{{host}}/moduleRecord/queryFieldAdd?type=1
#Content-Type: application/json
#satoken: {{token}}
#
#{}



####################################
### 审批相关
####################################
###
POST http://{{host}}/examine/queryPageList
Content-Type: application/json
satoken: {{token}}

{"keyword":"","moduleId":4,"page":1,"limit":10,"pageType":0}