// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.authentication.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.authentication.base.entity.AuthorizationFieldPolicy;
import com.unique.unexamine.authentication.base.mapper.AuthorizationFieldPolicyMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class AuthorizationFieldPolicyBaseService {
    private final AuthorizationFieldPolicyMapper mapper;

    public AuthorizationFieldPolicyBaseService(AuthorizationFieldPolicyMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(AuthorizationFieldPolicy entity) {
        return mapper.insert(entity);
    }

    public AuthorizationFieldPolicy selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<AuthorizationFieldPolicy> selectList(Wrapper<AuthorizationFieldPolicy> query) {
        return mapper.selectList(query);
    }

    public int updateById(AuthorizationFieldPolicy entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
