// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.authentication.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.authentication.base.entity.AuthorizationPermissionVersion;
import com.unique.unexamine.authentication.base.mapper.AuthorizationPermissionVersionMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class AuthorizationPermissionVersionBaseService {
    private final AuthorizationPermissionVersionMapper mapper;

    public AuthorizationPermissionVersionBaseService(AuthorizationPermissionVersionMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(AuthorizationPermissionVersion entity) {
        return mapper.insert(entity);
    }

    public AuthorizationPermissionVersion selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<AuthorizationPermissionVersion> selectList(Wrapper<AuthorizationPermissionVersion> query) {
        return mapper.selectList(query);
    }

    public int updateById(AuthorizationPermissionVersion entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
