-- Initial baseline: module actions for import preview/execution and permission-scoped export.

CREATE TABLE `exchange_mapping` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `system_id` BIGINT NOT NULL,
  `owner_tenant_id` BIGINT NOT NULL,
  `module_id` BIGINT NOT NULL,
  `code` VARCHAR(100) NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  `mapping_type` VARCHAR(32) NOT NULL,
  `column_mapping_json` JSON NOT NULL,
  `validation_policy_json` JSON NOT NULL,
  `conflict_policy_json` JSON NOT NULL,
  `status` VARCHAR(32) NOT NULL,
  `created_by_member_id` BIGINT NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `version` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_exchange_mapping_code` (`owner_tenant_id`, `module_id`, `code`),
  CONSTRAINT `fk_exchange_mapping_module` FOREIGN KEY (`system_id`, `module_id`) REFERENCES `cfg_module` (`system_id`, `id`),
  CONSTRAINT `fk_exchange_mapping_tenant` FOREIGN KEY (`system_id`, `owner_tenant_id`) REFERENCES `sys_tenant` (`system_id`, `id`),
  CONSTRAINT `fk_exchange_mapping_creator` FOREIGN KEY (`system_id`, `created_by_member_id`) REFERENCES `sys_member` (`system_id`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `exchange_import_batch` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `system_id` BIGINT NOT NULL,
  `tenant_id` BIGINT NOT NULL,
  `module_id` BIGINT NOT NULL,
  `mapping_id` BIGINT NOT NULL,
  `source_file_id` BIGINT NOT NULL,
  `job_id` BIGINT NULL,
  `mode` VARCHAR(32) NOT NULL,
  `status` VARCHAR(32) NOT NULL,
  `total_rows` BIGINT NOT NULL DEFAULT 0,
  `valid_rows` BIGINT NOT NULL DEFAULT 0,
  `success_rows` BIGINT NOT NULL DEFAULT 0,
  `failed_rows` BIGINT NOT NULL DEFAULT 0,
  `authorization_snapshot_json` JSON NOT NULL,
  `summary_json` JSON NULL,
  `created_by_member_id` BIGINT NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `started_at` DATETIME(3) NULL,
  `finished_at` DATETIME(3) NULL,
  `version` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_exchange_import_context` (`tenant_id`, `module_id`, `created_at`),
  KEY `idx_exchange_import_status` (`status`, `created_at`),
  CONSTRAINT `fk_exchange_import_tenant` FOREIGN KEY (`system_id`, `tenant_id`) REFERENCES `sys_tenant` (`system_id`, `id`),
  CONSTRAINT `fk_exchange_import_module` FOREIGN KEY (`system_id`, `module_id`) REFERENCES `cfg_module` (`system_id`, `id`),
  CONSTRAINT `fk_exchange_import_mapping` FOREIGN KEY (`mapping_id`) REFERENCES `exchange_mapping` (`id`),
  CONSTRAINT `fk_exchange_import_file` FOREIGN KEY (`source_file_id`) REFERENCES `file_object` (`id`),
  CONSTRAINT `fk_exchange_import_job` FOREIGN KEY (`job_id`) REFERENCES `job_background` (`id`),
  CONSTRAINT `fk_exchange_import_creator` FOREIGN KEY (`system_id`, `created_by_member_id`) REFERENCES `sys_member` (`system_id`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `exchange_import_row` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `batch_id` BIGINT NOT NULL,
  `row_number` BIGINT NOT NULL,
  `raw_json` JSON NOT NULL,
  `normalized_json` JSON NULL,
  `status` VARCHAR(32) NOT NULL,
  `target_record_id` BIGINT NULL,
  `error_json` JSON NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `version` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_exchange_import_row` (`batch_id`, `row_number`),
  KEY `idx_exchange_import_row_status` (`batch_id`, `status`, `row_number`),
  CONSTRAINT `fk_exchange_import_row_batch` FOREIGN KEY (`batch_id`) REFERENCES `exchange_import_batch` (`id`),
  CONSTRAINT `fk_exchange_import_row_record` FOREIGN KEY (`target_record_id`) REFERENCES `biz_record` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `exchange_export_batch` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `system_id` BIGINT NOT NULL,
  `tenant_id` BIGINT NOT NULL,
  `module_id` BIGINT NOT NULL,
  `mapping_id` BIGINT NULL,
  `job_id` BIGINT NULL,
  `filter_snapshot_json` JSON NOT NULL,
  `authorization_snapshot_json` JSON NOT NULL,
  `selected_fields_json` JSON NOT NULL,
  `status` VARCHAR(32) NOT NULL,
  `total_rows` BIGINT NOT NULL DEFAULT 0,
  `exported_rows` BIGINT NOT NULL DEFAULT 0,
  `result_file_id` BIGINT NULL,
  `error_message` VARCHAR(2000) NULL,
  `created_by_member_id` BIGINT NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `started_at` DATETIME(3) NULL,
  `finished_at` DATETIME(3) NULL,
  `version` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_exchange_export_context` (`tenant_id`, `module_id`, `created_at`),
  KEY `idx_exchange_export_status` (`status`, `created_at`),
  CONSTRAINT `fk_exchange_export_tenant` FOREIGN KEY (`system_id`, `tenant_id`) REFERENCES `sys_tenant` (`system_id`, `id`),
  CONSTRAINT `fk_exchange_export_module` FOREIGN KEY (`system_id`, `module_id`) REFERENCES `cfg_module` (`system_id`, `id`),
  CONSTRAINT `fk_exchange_export_mapping` FOREIGN KEY (`mapping_id`) REFERENCES `exchange_mapping` (`id`),
  CONSTRAINT `fk_exchange_export_job` FOREIGN KEY (`job_id`) REFERENCES `job_background` (`id`),
  CONSTRAINT `fk_exchange_export_file` FOREIGN KEY (`result_file_id`) REFERENCES `file_object` (`id`),
  CONSTRAINT `fk_exchange_export_creator` FOREIGN KEY (`system_id`, `created_by_member_id`) REFERENCES `sys_member` (`system_id`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
