// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.aiwork.base.entity;

import java.time.LocalDateTime;
import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;

/**
 * Generated entity for table `un_agent_confirmation`.
 */
@TableName("un_agent_confirmation")
public class AgentConfirmation {

    public static final String TABLE_NAME = "un_agent_confirmation";

    /**
     * Column `id`.
     */
    @TableId(value = "id", type = IdType.AUTO)
    private Long id;

    /**
     * Column `confirmation_id`.
     */
    private String confirmationId;

    /**
     * Column `confirm_type`.
     */
    private String confirmType;

    /**
     * Column `status`.
     */
    private String status;

    /**
     * Column `source_conversation`.
     */
    private String sourceConversation;

    /**
     * Column `diff_payload`.
     */
    private String diffPayload;

    /**
     * Column `permission_snapshot_id`.
     */
    private String permissionSnapshotId;

    /**
     * Column `confirmed_by`.
     */
    private Long confirmedBy;

    /**
     * Column `confirmed_at`.
     */
    private LocalDateTime confirmedAt;

    /**
     * Column `audit_log_id`.
     */
    private String auditLogId;

    /**
     * Column `trace_id`.
     */
    private String traceId;

    /**
     * Column `created_at`.
     */
    private LocalDateTime createdAt;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getConfirmationId() {
        return confirmationId;
    }

    public void setConfirmationId(String confirmationId) {
        this.confirmationId = confirmationId;
    }

    public String getConfirmType() {
        return confirmType;
    }

    public void setConfirmType(String confirmType) {
        this.confirmType = confirmType;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getSourceConversation() {
        return sourceConversation;
    }

    public void setSourceConversation(String sourceConversation) {
        this.sourceConversation = sourceConversation;
    }

    public String getDiffPayload() {
        return diffPayload;
    }

    public void setDiffPayload(String diffPayload) {
        this.diffPayload = diffPayload;
    }

    public String getPermissionSnapshotId() {
        return permissionSnapshotId;
    }

    public void setPermissionSnapshotId(String permissionSnapshotId) {
        this.permissionSnapshotId = permissionSnapshotId;
    }

    public Long getConfirmedBy() {
        return confirmedBy;
    }

    public void setConfirmedBy(Long confirmedBy) {
        this.confirmedBy = confirmedBy;
    }

    public LocalDateTime getConfirmedAt() {
        return confirmedAt;
    }

    public void setConfirmedAt(LocalDateTime confirmedAt) {
        this.confirmedAt = confirmedAt;
    }

    public String getAuditLogId() {
        return auditLogId;
    }

    public void setAuditLogId(String auditLogId) {
        this.auditLogId = auditLogId;
    }

    public String getTraceId() {
        return traceId;
    }

    public void setTraceId(String traceId) {
        this.traceId = traceId;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

}
