// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.aiwork.base.entity;

import java.time.LocalDateTime;
import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;

/**
 * Generated entity for table `un_work_daily_report_source`.
 */
@TableName("un_work_daily_report_source")
public class WorkDailyReportSource {

    public static final String TABLE_NAME = "un_work_daily_report_source";

    /**
     * Column `id`.
     */
    @TableId(value = "id", type = IdType.AUTO)
    private Long id;

    /**
     * Column `report_id`.
     */
    private Long reportId;

    /**
     * Column `draft_no`.
     */
    private String draftNo;

    /**
     * Column `source_type`.
     */
    private String sourceType;

    /**
     * Column `source_id`.
     */
    private String sourceId;

    /**
     * Column `source_snapshot`.
     */
    private String sourceSnapshot;

    /**
     * Column `permission_snapshot_id`.
     */
    private String permissionSnapshotId;

    /**
     * Column `selected`.
     */
    private Integer selected;

    /**
     * Column `created_at`.
     */
    private LocalDateTime createdAt;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getReportId() {
        return reportId;
    }

    public void setReportId(Long reportId) {
        this.reportId = reportId;
    }

    public String getDraftNo() {
        return draftNo;
    }

    public void setDraftNo(String draftNo) {
        this.draftNo = draftNo;
    }

    public String getSourceType() {
        return sourceType;
    }

    public void setSourceType(String sourceType) {
        this.sourceType = sourceType;
    }

    public String getSourceId() {
        return sourceId;
    }

    public void setSourceId(String sourceId) {
        this.sourceId = sourceId;
    }

    public String getSourceSnapshot() {
        return sourceSnapshot;
    }

    public void setSourceSnapshot(String sourceSnapshot) {
        this.sourceSnapshot = sourceSnapshot;
    }

    public String getPermissionSnapshotId() {
        return permissionSnapshotId;
    }

    public void setPermissionSnapshotId(String permissionSnapshotId) {
        this.permissionSnapshotId = permissionSnapshotId;
    }

    public Integer getSelected() {
        return selected;
    }

    public void setSelected(Integer selected) {
        this.selected = selected;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

}
