// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.aiwork.base.entity;

import java.time.LocalDateTime;
import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;

/**
 * Generated entity for table `un_work_daily_report_auto_source_rule`.
 */
@TableName("un_work_daily_report_auto_source_rule")
public class WorkDailyReportAutoSourceRule {

    public static final String TABLE_NAME = "un_work_daily_report_auto_source_rule";

    /**
     * Column `id`.
     */
    @TableId(value = "id", type = IdType.AUTO)
    private Long id;

    /**
     * Column `system_id`.
     */
    private Long systemId;

    /**
     * Column `tenant_id`.
     */
    private Long tenantId;

    /**
     * Column `source_types`.
     */
    private String sourceTypes;

    /**
     * Column `task_scope`.
     */
    private String taskScope;

    /**
     * Column `todo_scope`.
     */
    private String todoScope;

    /**
     * Column `message_scope`.
     */
    private String messageScope;

    /**
     * Column `log_scope`.
     */
    private String logScope;

    /**
     * Column `approval_scope`.
     */
    private String approvalScope;

    /**
     * Column `permission_policy`.
     */
    private String permissionPolicy;

    /**
     * Column `manual_confirm_required`.
     */
    private Integer manualConfirmRequired;

    /**
     * Column `updated_at`.
     */
    private LocalDateTime updatedAt;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getSystemId() {
        return systemId;
    }

    public void setSystemId(Long systemId) {
        this.systemId = systemId;
    }

    public Long getTenantId() {
        return tenantId;
    }

    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    public String getSourceTypes() {
        return sourceTypes;
    }

    public void setSourceTypes(String sourceTypes) {
        this.sourceTypes = sourceTypes;
    }

    public String getTaskScope() {
        return taskScope;
    }

    public void setTaskScope(String taskScope) {
        this.taskScope = taskScope;
    }

    public String getTodoScope() {
        return todoScope;
    }

    public void setTodoScope(String todoScope) {
        this.todoScope = todoScope;
    }

    public String getMessageScope() {
        return messageScope;
    }

    public void setMessageScope(String messageScope) {
        this.messageScope = messageScope;
    }

    public String getLogScope() {
        return logScope;
    }

    public void setLogScope(String logScope) {
        this.logScope = logScope;
    }

    public String getApprovalScope() {
        return approvalScope;
    }

    public void setApprovalScope(String approvalScope) {
        this.approvalScope = approvalScope;
    }

    public String getPermissionPolicy() {
        return permissionPolicy;
    }

    public void setPermissionPolicy(String permissionPolicy) {
        this.permissionPolicy = permissionPolicy;
    }

    public Integer getManualConfirmRequired() {
        return manualConfirmRequired;
    }

    public void setManualConfirmRequired(Integer manualConfirmRequired) {
        this.manualConfirmRequired = manualConfirmRequired;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

}
