// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.aiwork.base.entity;

import java.time.LocalDateTime;
import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;

/**
 * Generated entity for table `un_work_kanban_config`.
 */
@TableName("un_work_kanban_config")
public class WorkKanbanConfig {

    public static final String TABLE_NAME = "un_work_kanban_config";

    /**
     * Column `id`.
     */
    @TableId(value = "id", type = IdType.AUTO)
    private Long id;

    /**
     * Column `system_id`.
     */
    private Long systemId;

    /**
     * Column `tenant_id`.
     */
    private Long tenantId;

    /**
     * Column `task_type`.
     */
    private String taskType;

    /**
     * Column `column_field_id`.
     */
    private Long columnFieldId;

    /**
     * Column `swimlane_field_id`.
     */
    private Long swimlaneFieldId;

    /**
     * Column `group_field_id`.
     */
    private Long groupFieldId;

    /**
     * Column `card_fields`.
     */
    private String cardFields;

    /**
     * Column `published_version`.
     */
    private String publishedVersion;

    /**
     * Column `updated_at`.
     */
    private LocalDateTime updatedAt;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getSystemId() {
        return systemId;
    }

    public void setSystemId(Long systemId) {
        this.systemId = systemId;
    }

    public Long getTenantId() {
        return tenantId;
    }

    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    public String getTaskType() {
        return taskType;
    }

    public void setTaskType(String taskType) {
        this.taskType = taskType;
    }

    public Long getColumnFieldId() {
        return columnFieldId;
    }

    public void setColumnFieldId(Long columnFieldId) {
        this.columnFieldId = columnFieldId;
    }

    public Long getSwimlaneFieldId() {
        return swimlaneFieldId;
    }

    public void setSwimlaneFieldId(Long swimlaneFieldId) {
        this.swimlaneFieldId = swimlaneFieldId;
    }

    public Long getGroupFieldId() {
        return groupFieldId;
    }

    public void setGroupFieldId(Long groupFieldId) {
        this.groupFieldId = groupFieldId;
    }

    public String getCardFields() {
        return cardFields;
    }

    public void setCardFields(String cardFields) {
        this.cardFields = cardFields;
    }

    public String getPublishedVersion() {
        return publishedVersion;
    }

    public void setPublishedVersion(String publishedVersion) {
        this.publishedVersion = publishedVersion;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

}
