// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.upload.base.service.impl;

import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.unique.examine.upload.base.entity.UploadFileVersion;
import com.unique.examine.upload.base.mapper.UploadFileVersionMapper;
import com.unique.examine.upload.base.service.UploadFileVersionBaseService;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

import org.springframework.stereotype.Service;

/**
 * Generated MyBatis-Plus base service implementation for UploadFileVersion.
 */
@Service
public class UploadFileVersionBaseServiceImpl extends ServiceImpl<UploadFileVersionMapper, UploadFileVersion> implements UploadFileVersionBaseService {

    @Override
    public Optional<UploadFileVersion> findById(Long id) {
        return Optional.ofNullable(getById(id));
    }

    @Override
    public List<UploadFileVersion> findAll() {
        return list();
    }

    @Override
    public UploadFileVersion saveEntity(UploadFileVersion entity) {
        saveOrUpdate(entity);
        return entity;
    }

    @Override
    public boolean deleteByIds(Collection<Long> ids) {
        return ids != null && !ids.isEmpty() && removeBatchByIds(ids);
    }
}
