// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.upload.base.service.impl;

import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.unique.examine.upload.base.entity.UploadFileRecycle;
import com.unique.examine.upload.base.mapper.UploadFileRecycleMapper;
import com.unique.examine.upload.base.service.UploadFileRecycleBaseService;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

import org.springframework.stereotype.Service;

/**
 * Generated MyBatis-Plus base service implementation for UploadFileRecycle.
 */
@Service
public class UploadFileRecycleBaseServiceImpl extends ServiceImpl<UploadFileRecycleMapper, UploadFileRecycle> implements UploadFileRecycleBaseService {

    @Override
    public Optional<UploadFileRecycle> findById(Long id) {
        return Optional.ofNullable(getById(id));
    }

    @Override
    public List<UploadFileRecycle> findAll() {
        return list();
    }

    @Override
    public UploadFileRecycle saveEntity(UploadFileRecycle entity) {
        saveOrUpdate(entity);
        return entity;
    }

    @Override
    public boolean deleteByIds(Collection<Long> ids) {
        return ids != null && !ids.isEmpty() && removeBatchByIds(ids);
    }
}
