// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.flow.base.entity;

import java.time.LocalDateTime;
import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;

/**
 * Generated entity for table `un_flow_approval_action_log`.
 */
@TableName("un_flow_approval_action_log")
public class FlowApprovalActionLog {

    public static final String TABLE_NAME = "un_flow_approval_action_log";

    /**
     * Column `id`.
     */
    @TableId(value = "id", type = IdType.AUTO)
    private Long id;

    /**
     * Column `instance_id`.
     */
    private Long instanceId;

    /**
     * Column `task_id`.
     */
    private Long taskId;

    /**
     * Column `action_code`.
     */
    private String actionCode;

    /**
     * Column `action_result`.
     */
    private String actionResult;

    /**
     * Column `action_reason`.
     */
    private String actionReason;

    /**
     * Column `operator_member_id`.
     */
    private Long operatorMemberId;

    /**
     * Column `next_node_payload`.
     */
    private String nextNodePayload;

    /**
     * Column `idempotency_key`.
     */
    private String idempotencyKey;

    /**
     * Column `trace_id`.
     */
    private String traceId;

    /**
     * Column `audit_log_id`.
     */
    private String auditLogId;

    /**
     * Column `operated_at`.
     */
    private LocalDateTime operatedAt;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getInstanceId() {
        return instanceId;
    }

    public void setInstanceId(Long instanceId) {
        this.instanceId = instanceId;
    }

    public Long getTaskId() {
        return taskId;
    }

    public void setTaskId(Long taskId) {
        this.taskId = taskId;
    }

    public String getActionCode() {
        return actionCode;
    }

    public void setActionCode(String actionCode) {
        this.actionCode = actionCode;
    }

    public String getActionResult() {
        return actionResult;
    }

    public void setActionResult(String actionResult) {
        this.actionResult = actionResult;
    }

    public String getActionReason() {
        return actionReason;
    }

    public void setActionReason(String actionReason) {
        this.actionReason = actionReason;
    }

    public Long getOperatorMemberId() {
        return operatorMemberId;
    }

    public void setOperatorMemberId(Long operatorMemberId) {
        this.operatorMemberId = operatorMemberId;
    }

    public String getNextNodePayload() {
        return nextNodePayload;
    }

    public void setNextNodePayload(String nextNodePayload) {
        this.nextNodePayload = nextNodePayload;
    }

    public String getIdempotencyKey() {
        return idempotencyKey;
    }

    public void setIdempotencyKey(String idempotencyKey) {
        this.idempotencyKey = idempotencyKey;
    }

    public String getTraceId() {
        return traceId;
    }

    public void setTraceId(String traceId) {
        this.traceId = traceId;
    }

    public String getAuditLogId() {
        return auditLogId;
    }

    public void setAuditLogId(String auditLogId) {
        this.auditLogId = auditLogId;
    }

    public LocalDateTime getOperatedAt() {
        return operatedAt;
    }

    public void setOperatedAt(LocalDateTime operatedAt) {
        this.operatedAt = operatedAt;
    }

}
