// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.flow.base.entity;

import java.time.LocalDateTime;
import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;

/**
 * Generated entity for table `un_flow_approval_task`.
 */
@TableName("un_flow_approval_task")
public class FlowApprovalTask {

    public static final String TABLE_NAME = "un_flow_approval_task";

    /**
     * Column `id`.
     */
    @TableId(value = "id", type = IdType.AUTO)
    private Long id;

    /**
     * Column `instance_id`.
     */
    private Long instanceId;

    /**
     * Column `task_no`.
     */
    private String taskNo;

    /**
     * Column `node_id`.
     */
    private String nodeId;

    /**
     * Column `node_name`.
     */
    private String nodeName;

    /**
     * Column `assignee_member_id`.
     */
    private Long assigneeMemberId;

    /**
     * Column `status`.
     */
    private String status;

    /**
     * Column `action_result`.
     */
    private String actionResult;

    /**
     * Column `action_reason`.
     */
    private String actionReason;

    /**
     * Column `field_permission_snapshot`.
     */
    private String fieldPermissionSnapshot;

    /**
     * Column `due_at`.
     */
    private LocalDateTime dueAt;

    /**
     * Column `operated_at`.
     */
    private LocalDateTime operatedAt;

    /**
     * Column `idempotency_key`.
     */
    private String idempotencyKey;

    /**
     * Column `trace_id`.
     */
    private String traceId;

    /**
     * Column `created_at`.
     */
    private LocalDateTime createdAt;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getInstanceId() {
        return instanceId;
    }

    public void setInstanceId(Long instanceId) {
        this.instanceId = instanceId;
    }

    public String getTaskNo() {
        return taskNo;
    }

    public void setTaskNo(String taskNo) {
        this.taskNo = taskNo;
    }

    public String getNodeId() {
        return nodeId;
    }

    public void setNodeId(String nodeId) {
        this.nodeId = nodeId;
    }

    public String getNodeName() {
        return nodeName;
    }

    public void setNodeName(String nodeName) {
        this.nodeName = nodeName;
    }

    public Long getAssigneeMemberId() {
        return assigneeMemberId;
    }

    public void setAssigneeMemberId(Long assigneeMemberId) {
        this.assigneeMemberId = assigneeMemberId;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getActionResult() {
        return actionResult;
    }

    public void setActionResult(String actionResult) {
        this.actionResult = actionResult;
    }

    public String getActionReason() {
        return actionReason;
    }

    public void setActionReason(String actionReason) {
        this.actionReason = actionReason;
    }

    public String getFieldPermissionSnapshot() {
        return fieldPermissionSnapshot;
    }

    public void setFieldPermissionSnapshot(String fieldPermissionSnapshot) {
        this.fieldPermissionSnapshot = fieldPermissionSnapshot;
    }

    public LocalDateTime getDueAt() {
        return dueAt;
    }

    public void setDueAt(LocalDateTime dueAt) {
        this.dueAt = dueAt;
    }

    public LocalDateTime getOperatedAt() {
        return operatedAt;
    }

    public void setOperatedAt(LocalDateTime operatedAt) {
        this.operatedAt = operatedAt;
    }

    public String getIdempotencyKey() {
        return idempotencyKey;
    }

    public void setIdempotencyKey(String idempotencyKey) {
        this.idempotencyKey = idempotencyKey;
    }

    public String getTraceId() {
        return traceId;
    }

    public void setTraceId(String traceId) {
        this.traceId = traceId;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

}
