// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.flow.base.entity;

import java.time.LocalDateTime;
import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;

/**
 * Generated entity for table `un_flow_node`.
 */
@TableName("un_flow_node")
public class FlowNode {

    public static final String TABLE_NAME = "un_flow_node";

    /**
     * Column `id`.
     */
    @TableId(value = "id", type = IdType.AUTO)
    private Long id;

    /**
     * Column `flow_id`.
     */
    private Long flowId;

    /**
     * Column `node_key`.
     */
    private String nodeKey;

    /**
     * Column `node_type`.
     */
    private String nodeType;

    /**
     * Column `node_name`.
     */
    private String nodeName;

    /**
     * Column `position_payload`.
     */
    private String positionPayload;

    /**
     * Column `property_payload`.
     */
    private String propertyPayload;

    /**
     * Column `status`.
     */
    private Integer status;

    /**
     * Column `created_at`.
     */
    private LocalDateTime createdAt;

    /**
     * Column `updated_at`.
     */
    private LocalDateTime updatedAt;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getFlowId() {
        return flowId;
    }

    public void setFlowId(Long flowId) {
        this.flowId = flowId;
    }

    public String getNodeKey() {
        return nodeKey;
    }

    public void setNodeKey(String nodeKey) {
        this.nodeKey = nodeKey;
    }

    public String getNodeType() {
        return nodeType;
    }

    public void setNodeType(String nodeType) {
        this.nodeType = nodeType;
    }

    public String getNodeName() {
        return nodeName;
    }

    public void setNodeName(String nodeName) {
        this.nodeName = nodeName;
    }

    public String getPositionPayload() {
        return positionPayload;
    }

    public void setPositionPayload(String positionPayload) {
        this.positionPayload = positionPayload;
    }

    public String getPropertyPayload() {
        return propertyPayload;
    }

    public void setPropertyPayload(String propertyPayload) {
        this.propertyPayload = propertyPayload;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

}
