-- @generated by Template Base. Change database-model.json and regenerate.

SET NAMES utf8mb4;

CREATE TABLE `cfg_module_group` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `system_id` BIGINT NOT NULL,
  `owner_tenant_id` BIGINT NOT NULL,
  `code` VARCHAR(100) NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  `sort_order` INT NOT NULL DEFAULT 0,
  `status` VARCHAR(32) NOT NULL,
  `created_by_member_id` BIGINT NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `version` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_cfg_module_group_code` (`owner_tenant_id`, `code`),
  UNIQUE KEY `uk_cfg_module_group_owner_id` (`owner_tenant_id`, `id`),
  KEY `idx_cfg_module_group_system` (`system_id`, `owner_tenant_id`, `sort_order`),
  CONSTRAINT `fk_cfg_module_group_system` FOREIGN KEY (`system_id`) REFERENCES `sys_system` (`id`),
  CONSTRAINT `fk_cfg_module_group_tenant` FOREIGN KEY (`system_id`, `owner_tenant_id`) REFERENCES `sys_tenant` (`system_id`, `id`),
  CONSTRAINT `fk_cfg_module_group_creator` FOREIGN KEY (`system_id`, `created_by_member_id`) REFERENCES `sys_member` (`system_id`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `cfg_module` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `system_id` BIGINT NOT NULL,
  `owner_tenant_id` BIGINT NOT NULL,
  `group_id` BIGINT NOT NULL,
  `code` VARCHAR(100) NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  `status` VARCHAR(32) NOT NULL,
  `draft_revision` INT NOT NULL DEFAULT 1,
  `created_by_member_id` BIGINT NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `version` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_cfg_module_code` (`owner_tenant_id`, `code`),
  UNIQUE KEY `uk_cfg_module_system_id` (`system_id`, `id`),
  UNIQUE KEY `uk_cfg_module_owner_id` (`owner_tenant_id`, `id`),
  KEY `idx_cfg_module_group` (`group_id`, `status`),
  CONSTRAINT `fk_cfg_module_tenant` FOREIGN KEY (`system_id`, `owner_tenant_id`) REFERENCES `sys_tenant` (`system_id`, `id`),
  CONSTRAINT `fk_cfg_module_group` FOREIGN KEY (`owner_tenant_id`, `group_id`) REFERENCES `cfg_module_group` (`owner_tenant_id`, `id`),
  CONSTRAINT `fk_cfg_module_creator` FOREIGN KEY (`system_id`, `created_by_member_id`) REFERENCES `sys_member` (`system_id`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `cfg_module_field` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `system_id` BIGINT NOT NULL,
  `owner_tenant_id` BIGINT NOT NULL,
  `module_id` BIGINT NOT NULL,
  `code` VARCHAR(100) NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  `field_type` VARCHAR(64) NOT NULL,
  `required` TINYINT NOT NULL DEFAULT 0,
  `sort_order` INT NOT NULL DEFAULT 0,
  `status` VARCHAR(32) NOT NULL,
  `config_json` JSON NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `version` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_cfg_module_field_code` (`module_id`, `code`),
  KEY `idx_cfg_module_field_order` (`module_id`, `status`, `sort_order`),
  CONSTRAINT `fk_cfg_module_field_module` FOREIGN KEY (`system_id`, `module_id`) REFERENCES `cfg_module` (`system_id`, `id`),
  CONSTRAINT `fk_cfg_module_field_tenant` FOREIGN KEY (`system_id`, `owner_tenant_id`) REFERENCES `sys_tenant` (`system_id`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `cfg_module_page` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `system_id` BIGINT NOT NULL,
  `owner_tenant_id` BIGINT NOT NULL,
  `module_id` BIGINT NOT NULL,
  `page_type` VARCHAR(32) NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  `layout_json` JSON NOT NULL,
  `status` VARCHAR(32) NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `version` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_cfg_module_page_type` (`module_id`, `page_type`),
  CONSTRAINT `fk_cfg_module_page_module` FOREIGN KEY (`system_id`, `module_id`) REFERENCES `cfg_module` (`system_id`, `id`),
  CONSTRAINT `fk_cfg_module_page_tenant` FOREIGN KEY (`system_id`, `owner_tenant_id`) REFERENCES `sys_tenant` (`system_id`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `cfg_module_action` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `system_id` BIGINT NOT NULL,
  `owner_tenant_id` BIGINT NOT NULL,
  `module_id` BIGINT NOT NULL,
  `code` VARCHAR(64) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `location` VARCHAR(64) NOT NULL,
  `sort_order` INT NOT NULL DEFAULT 0,
  `status` VARCHAR(32) NOT NULL,
  `config_json` JSON NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `version` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_cfg_module_action_code` (`module_id`, `code`),
  KEY `idx_cfg_module_action_location` (`module_id`, `location`, `sort_order`),
  CONSTRAINT `fk_cfg_module_action_module` FOREIGN KEY (`system_id`, `module_id`) REFERENCES `cfg_module` (`system_id`, `id`),
  CONSTRAINT `fk_cfg_module_action_tenant` FOREIGN KEY (`system_id`, `owner_tenant_id`) REFERENCES `sys_tenant` (`system_id`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `cfg_module_version` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `system_id` BIGINT NOT NULL,
  `owner_tenant_id` BIGINT NOT NULL,
  `module_id` BIGINT NOT NULL,
  `version_number` INT NOT NULL,
  `draft_revision` INT NOT NULL,
  `snapshot_json` JSON NOT NULL,
  `published_by_member_id` BIGINT NOT NULL,
  `published_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_cfg_module_version_number` (`module_id`, `version_number`),
  UNIQUE KEY `uk_cfg_module_version_revision` (`module_id`, `draft_revision`),
  UNIQUE KEY `uk_cfg_module_version_module_id` (`module_id`, `id`),
  KEY `idx_cfg_module_version_tenant` (`system_id`, `owner_tenant_id`, `published_at`),
  CONSTRAINT `fk_cfg_module_version_module` FOREIGN KEY (`system_id`, `module_id`) REFERENCES `cfg_module` (`system_id`, `id`),
  CONSTRAINT `fk_cfg_module_version_tenant` FOREIGN KEY (`system_id`, `owner_tenant_id`) REFERENCES `sys_tenant` (`system_id`, `id`),
  CONSTRAINT `fk_cfg_module_version_publisher` FOREIGN KEY (`system_id`, `published_by_member_id`) REFERENCES `sys_member` (`system_id`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

DELIMITER $$
CREATE TRIGGER `trg_cfg_module_version_immutable_update`
BEFORE UPDATE ON `cfg_module_version` FOR EACH ROW
BEGIN
  SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'cfg_module_version is immutable';
END$$
CREATE TRIGGER `trg_cfg_module_version_immutable_delete`
BEFORE DELETE ON `cfg_module_version` FOR EACH ROW
BEGIN
  SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'cfg_module_version is immutable';
END$$
DELIMITER ;

CREATE TABLE `cfg_module_publication` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `system_id` BIGINT NOT NULL,
  `owner_tenant_id` BIGINT NOT NULL,
  `module_id` BIGINT NOT NULL,
  `current_version_id` BIGINT NOT NULL,
  `updated_by_member_id` BIGINT NOT NULL,
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `version` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_cfg_module_publication_module` (`module_id`),
  KEY `idx_cfg_module_publication_tenant` (`system_id`, `owner_tenant_id`),
  CONSTRAINT `fk_cfg_module_publication_module` FOREIGN KEY (`system_id`, `module_id`) REFERENCES `cfg_module` (`system_id`, `id`),
  CONSTRAINT `fk_cfg_module_publication_version` FOREIGN KEY (`module_id`, `current_version_id`) REFERENCES `cfg_module_version` (`module_id`, `id`),
  CONSTRAINT `fk_cfg_module_publication_tenant` FOREIGN KEY (`system_id`, `owner_tenant_id`) REFERENCES `sys_tenant` (`system_id`, `id`),
  CONSTRAINT `fk_cfg_module_publication_updater` FOREIGN KEY (`system_id`, `updated_by_member_id`) REFERENCES `sys_member` (`system_id`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `biz_record` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `system_id` BIGINT NOT NULL,
  `tenant_id` BIGINT NOT NULL,
  `module_id` BIGINT NOT NULL,
  `created_config_version_id` BIGINT NOT NULL,
  `updated_config_version_id` BIGINT NOT NULL,
  `record_number` VARCHAR(100) NULL,
  `title` VARCHAR(500) NOT NULL,
  `status` VARCHAR(64) NOT NULL,
  `owner_member_id` BIGINT NULL,
  `department_id` BIGINT NULL,
  `created_by_member_id` BIGINT NOT NULL,
  `updated_by_member_id` BIGINT NOT NULL,
  `archived` TINYINT NOT NULL DEFAULT 0,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `version` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_biz_record_number` (`tenant_id`, `module_id`, `record_number`),
  KEY `idx_biz_record_list` (`tenant_id`, `module_id`, `deleted`, `updated_at`),
  KEY `idx_biz_record_owner` (`tenant_id`, `module_id`, `owner_member_id`),
  KEY `idx_biz_record_department` (`tenant_id`, `module_id`, `department_id`),
  CONSTRAINT `fk_biz_record_tenant` FOREIGN KEY (`system_id`, `tenant_id`) REFERENCES `sys_tenant` (`system_id`, `id`),
  CONSTRAINT `fk_biz_record_module` FOREIGN KEY (`system_id`, `module_id`) REFERENCES `cfg_module` (`system_id`, `id`),
  CONSTRAINT `fk_biz_record_created_config_version` FOREIGN KEY (`module_id`, `created_config_version_id`) REFERENCES `cfg_module_version` (`module_id`, `id`),
  CONSTRAINT `fk_biz_record_updated_config_version` FOREIGN KEY (`module_id`, `updated_config_version_id`) REFERENCES `cfg_module_version` (`module_id`, `id`),
  CONSTRAINT `fk_biz_record_owner` FOREIGN KEY (`system_id`, `owner_member_id`) REFERENCES `sys_member` (`system_id`, `id`),
  CONSTRAINT `fk_biz_record_department` FOREIGN KEY (`tenant_id`, `department_id`) REFERENCES `sys_department` (`tenant_id`, `id`),
  CONSTRAINT `fk_biz_record_creator` FOREIGN KEY (`system_id`, `created_by_member_id`) REFERENCES `sys_member` (`system_id`, `id`),
  CONSTRAINT `fk_biz_record_updater` FOREIGN KEY (`system_id`, `updated_by_member_id`) REFERENCES `sys_member` (`system_id`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `biz_record_participant` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `system_id` BIGINT NOT NULL,
  `tenant_id` BIGINT NOT NULL,
  `record_id` BIGINT NOT NULL,
  `system_member_id` BIGINT NOT NULL,
  `created_by_member_id` BIGINT NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_biz_record_participant` (`record_id`, `system_member_id`),
  KEY `idx_biz_record_participant_member` (`tenant_id`, `system_member_id`, `record_id`),
  CONSTRAINT `fk_biz_record_participant_record` FOREIGN KEY (`record_id`) REFERENCES `biz_record` (`id`),
  CONSTRAINT `fk_biz_record_participant_tenant_member` FOREIGN KEY (`tenant_id`, `system_member_id`) REFERENCES `sys_tenant_member` (`tenant_id`, `system_member_id`),
  CONSTRAINT `fk_biz_record_participant_creator` FOREIGN KEY (`system_id`, `created_by_member_id`) REFERENCES `sys_member` (`system_id`, `id`),
  CONSTRAINT `fk_biz_record_participant_tenant` FOREIGN KEY (`system_id`, `tenant_id`) REFERENCES `sys_tenant` (`system_id`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `biz_record_value` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `record_id` BIGINT NOT NULL,
  `field_id` BIGINT NOT NULL,
  `field_code` VARCHAR(100) NOT NULL,
  `value_type` VARCHAR(32) NOT NULL,
  `value_text` TEXT NULL,
  `value_number` DECIMAL(24, 8) NULL,
  `value_date` DATE NULL,
  `value_datetime` DATETIME(3) NULL,
  `value_boolean` TINYINT NULL,
  `value_reference_id` BIGINT NULL,
  `value_json` JSON NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_biz_record_value_field` (`record_id`, `field_id`),
  KEY `idx_biz_record_value_text` (`field_id`, `value_type`),
  KEY `idx_biz_record_value_reference` (`field_id`, `value_reference_id`),
  CONSTRAINT `fk_biz_record_value_record` FOREIGN KEY (`record_id`) REFERENCES `biz_record` (`id`),
  CONSTRAINT `fk_biz_record_value_field` FOREIGN KEY (`field_id`) REFERENCES `cfg_module_field` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
