// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.core.base.service;

import com.baomidou.mybatisplus.extension.service.IService;
import com.unique.examine.core.base.entity.OpsBackupRestore;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

/**
 * Generated base service contract for OpsBackupRestore.
 */
public interface OpsBackupRestoreBaseService extends IService<OpsBackupRestore> {

    Optional<OpsBackupRestore> findById(Long id);

    List<OpsBackupRestore> findAll();

    OpsBackupRestore saveEntity(OpsBackupRestore entity);

    boolean deleteByIds(Collection<Long> ids);
}
