// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.core.base.service;

import com.baomidou.mybatisplus.extension.service.IService;
import com.unique.examine.core.base.entity.OpsFeatureFlag;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

/**
 * Generated base service contract for OpsFeatureFlag.
 */
public interface OpsFeatureFlagBaseService extends IService<OpsFeatureFlag> {

    Optional<OpsFeatureFlag> findById(Long id);

    List<OpsFeatureFlag> findAll();

    OpsFeatureFlag saveEntity(OpsFeatureFlag entity);

    boolean deleteByIds(Collection<Long> ids);
}
