// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.core.base.service;

import com.baomidou.mybatisplus.extension.service.IService;
import com.unique.examine.core.base.entity.SysIdempotencyKey;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

/**
 * Generated base service contract for SysIdempotencyKey.
 */
public interface SysIdempotencyKeyBaseService extends IService<SysIdempotencyKey> {

    Optional<SysIdempotencyKey> findById(Long id);

    List<SysIdempotencyKey> findAll();

    SysIdempotencyKey saveEntity(SysIdempotencyKey entity);

    boolean deleteByIds(Collection<Long> ids);
}
