// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.system.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.system.base.entity.SystemTenantMember;
import com.unique.unexamine.system.base.mapper.SystemTenantMemberMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class SystemTenantMemberBaseService {
    private final SystemTenantMemberMapper mapper;

    public SystemTenantMemberBaseService(SystemTenantMemberMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(SystemTenantMember entity) {
        return mapper.insert(entity);
    }

    public SystemTenantMember selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<SystemTenantMember> selectList(Wrapper<SystemTenantMember> query) {
        return mapper.selectList(query);
    }

    public int updateById(SystemTenantMember entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
