// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.system.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.system.base.entity.SystemDefinition;
import com.unique.unexamine.system.base.mapper.SystemDefinitionMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class SystemDefinitionBaseService {
    private final SystemDefinitionMapper mapper;

    public SystemDefinitionBaseService(SystemDefinitionMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(SystemDefinition entity) {
        return mapper.insert(entity);
    }

    public SystemDefinition selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<SystemDefinition> selectList(Wrapper<SystemDefinition> query) {
        return mapper.selectList(query);
    }

    public int updateById(SystemDefinition entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
