// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.ai.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.ai.base.entity.AiAgentTool;
import com.unique.unexamine.ai.base.mapper.AiAgentToolMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class AiAgentToolBaseService {
    private final AiAgentToolMapper mapper;

    public AiAgentToolBaseService(AiAgentToolMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(AiAgentTool entity) {
        return mapper.insert(entity);
    }

    public AiAgentTool selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<AiAgentTool> selectList(Wrapper<AiAgentTool> query) {
        return mapper.selectList(query);
    }

    public int updateById(AiAgentTool entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
