// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.ai.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.ai.base.entity.AiModel;
import com.unique.unexamine.ai.base.mapper.AiModelMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class AiModelBaseService {
    private final AiModelMapper mapper;

    public AiModelBaseService(AiModelMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(AiModel entity) {
        return mapper.insert(entity);
    }

    public AiModel selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<AiModel> selectList(Wrapper<AiModel> query) {
        return mapper.selectList(query);
    }

    public int updateById(AiModel entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
