// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.ai.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.ai.base.entity.AiPendingWrite;
import com.unique.unexamine.ai.base.mapper.AiPendingWriteMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class AiPendingWriteBaseService {
    private final AiPendingWriteMapper mapper;

    public AiPendingWriteBaseService(AiPendingWriteMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(AiPendingWrite entity) {
        return mapper.insert(entity);
    }

    public AiPendingWrite selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<AiPendingWrite> selectList(Wrapper<AiPendingWrite> query) {
        return mapper.selectList(query);
    }

    public int updateById(AiPendingWrite entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
