// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.ai.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.ai.base.entity.AiSystemModelGrant;
import com.unique.unexamine.ai.base.mapper.AiSystemModelGrantMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class AiSystemModelGrantBaseService {
    private final AiSystemModelGrantMapper mapper;

    public AiSystemModelGrantBaseService(AiSystemModelGrantMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(AiSystemModelGrant entity) {
        return mapper.insert(entity);
    }

    public AiSystemModelGrant selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<AiSystemModelGrant> selectList(Wrapper<AiSystemModelGrant> query) {
        return mapper.selectList(query);
    }

    public int updateById(AiSystemModelGrant entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
