// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.core.base.entity;

import java.time.LocalDateTime;
import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;

/**
 * Generated entity for table `un_ops_api_cache_policy`.
 */
@TableName("un_ops_api_cache_policy")
public class OpsApiCachePolicy {

    public static final String TABLE_NAME = "un_ops_api_cache_policy";

    /**
     * Column `id`.
     */
    @TableId(value = "id", type = IdType.AUTO)
    private Long id;

    /**
     * Column `policy_code`.
     */
    private String policyCode;

    /**
     * Column `cache_domain`.
     */
    private String cacheDomain;

    /**
     * Column `key_rule`.
     */
    private String keyRule;

    /**
     * Column `invalidation_rule`.
     */
    private String invalidationRule;

    /**
     * Column `status`.
     */
    private Integer status;

    /**
     * Column `updated_at`.
     */
    private LocalDateTime updatedAt;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPolicyCode() {
        return policyCode;
    }

    public void setPolicyCode(String policyCode) {
        this.policyCode = policyCode;
    }

    public String getCacheDomain() {
        return cacheDomain;
    }

    public void setCacheDomain(String cacheDomain) {
        this.cacheDomain = cacheDomain;
    }

    public String getKeyRule() {
        return keyRule;
    }

    public void setKeyRule(String keyRule) {
        this.keyRule = keyRule;
    }

    public String getInvalidationRule() {
        return invalidationRule;
    }

    public void setInvalidationRule(String invalidationRule) {
        this.invalidationRule = invalidationRule;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

}
