// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.core.base.entity;

import java.time.LocalDateTime;
import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;

/**
 * Generated entity for table `un_sys_async_task`.
 */
@TableName("un_sys_async_task")
public class SysAsyncTask {

    public static final String TABLE_NAME = "un_sys_async_task";

    /**
     * Column `id`.
     */
    @TableId(value = "id", type = IdType.AUTO)
    private Long id;

    /**
     * Column `task_id`.
     */
    private String taskId;

    /**
     * Column `biz_type`.
     */
    private String bizType;

    /**
     * Column `idempotency_key`.
     */
    private String idempotencyKey;

    /**
     * Column `status`.
     */
    private String status;

    /**
     * Column `progress`.
     */
    private Integer progress;

    /**
     * Column `retryable`.
     */
    private Integer retryable;

    /**
     * Column `cancelable`.
     */
    private Integer cancelable;

    /**
     * Column `rollback_supported`.
     */
    private Integer rollbackSupported;

    /**
     * Column `result_file_id`.
     */
    private String resultFileId;

    /**
     * Column `error_file_id`.
     */
    private String errorFileId;

    /**
     * Column `failure_reason`.
     */
    private String failureReason;

    /**
     * Column `partial_success_count`.
     */
    private Integer partialSuccessCount;

    /**
     * Column `partial_failure_count`.
     */
    private Integer partialFailureCount;

    /**
     * Column `trace_id`.
     */
    private String traceId;

    /**
     * Column `audit_log_id`.
     */
    private String auditLogId;

    /**
     * Column `created_by`.
     */
    private Long createdBy;

    /**
     * Column `created_at`.
     */
    private LocalDateTime createdAt;

    /**
     * Column `updated_at`.
     */
    private LocalDateTime updatedAt;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTaskId() {
        return taskId;
    }

    public void setTaskId(String taskId) {
        this.taskId = taskId;
    }

    public String getBizType() {
        return bizType;
    }

    public void setBizType(String bizType) {
        this.bizType = bizType;
    }

    public String getIdempotencyKey() {
        return idempotencyKey;
    }

    public void setIdempotencyKey(String idempotencyKey) {
        this.idempotencyKey = idempotencyKey;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Integer getProgress() {
        return progress;
    }

    public void setProgress(Integer progress) {
        this.progress = progress;
    }

    public Integer getRetryable() {
        return retryable;
    }

    public void setRetryable(Integer retryable) {
        this.retryable = retryable;
    }

    public Integer getCancelable() {
        return cancelable;
    }

    public void setCancelable(Integer cancelable) {
        this.cancelable = cancelable;
    }

    public Integer getRollbackSupported() {
        return rollbackSupported;
    }

    public void setRollbackSupported(Integer rollbackSupported) {
        this.rollbackSupported = rollbackSupported;
    }

    public String getResultFileId() {
        return resultFileId;
    }

    public void setResultFileId(String resultFileId) {
        this.resultFileId = resultFileId;
    }

    public String getErrorFileId() {
        return errorFileId;
    }

    public void setErrorFileId(String errorFileId) {
        this.errorFileId = errorFileId;
    }

    public String getFailureReason() {
        return failureReason;
    }

    public void setFailureReason(String failureReason) {
        this.failureReason = failureReason;
    }

    public Integer getPartialSuccessCount() {
        return partialSuccessCount;
    }

    public void setPartialSuccessCount(Integer partialSuccessCount) {
        this.partialSuccessCount = partialSuccessCount;
    }

    public Integer getPartialFailureCount() {
        return partialFailureCount;
    }

    public void setPartialFailureCount(Integer partialFailureCount) {
        this.partialFailureCount = partialFailureCount;
    }

    public String getTraceId() {
        return traceId;
    }

    public void setTraceId(String traceId) {
        this.traceId = traceId;
    }

    public String getAuditLogId() {
        return auditLogId;
    }

    public void setAuditLogId(String auditLogId) {
        this.auditLogId = auditLogId;
    }

    public Long getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

}
