// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.core.base.entity;

import java.time.LocalDateTime;
import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;

/**
 * Generated entity for table `un_sys_secret_ref`.
 */
@TableName("un_sys_secret_ref")
public class SysSecretRef {

    public static final String TABLE_NAME = "un_sys_secret_ref";

    /**
     * Column `id`.
     */
    @TableId(value = "id", type = IdType.AUTO)
    private Long id;

    /**
     * Column `secret_ref_id`.
     */
    private String secretRefId;

    /**
     * Column `ref_type`.
     */
    private String refType;

    /**
     * Column `display_name`.
     */
    private String displayName;

    /**
     * Column `version_no`.
     */
    private String versionNo;

    /**
     * Column `expires_at`.
     */
    private LocalDateTime expiresAt;

    /**
     * Column `rotation_status`.
     */
    private String rotationStatus;

    /**
     * Column `last_used_at`.
     */
    private LocalDateTime lastUsedAt;

    /**
     * Column `storage_ref`.
     */
    private String storageRef;

    /**
     * Column `created_at`.
     */
    private LocalDateTime createdAt;

    /**
     * Column `updated_at`.
     */
    private LocalDateTime updatedAt;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSecretRefId() {
        return secretRefId;
    }

    public void setSecretRefId(String secretRefId) {
        this.secretRefId = secretRefId;
    }

    public String getRefType() {
        return refType;
    }

    public void setRefType(String refType) {
        this.refType = refType;
    }

    public String getDisplayName() {
        return displayName;
    }

    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    public String getVersionNo() {
        return versionNo;
    }

    public void setVersionNo(String versionNo) {
        this.versionNo = versionNo;
    }

    public LocalDateTime getExpiresAt() {
        return expiresAt;
    }

    public void setExpiresAt(LocalDateTime expiresAt) {
        this.expiresAt = expiresAt;
    }

    public String getRotationStatus() {
        return rotationStatus;
    }

    public void setRotationStatus(String rotationStatus) {
        this.rotationStatus = rotationStatus;
    }

    public LocalDateTime getLastUsedAt() {
        return lastUsedAt;
    }

    public void setLastUsedAt(LocalDateTime lastUsedAt) {
        this.lastUsedAt = lastUsedAt;
    }

    public String getStorageRef() {
        return storageRef;
    }

    public void setStorageRef(String storageRef) {
        this.storageRef = storageRef;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

}
