// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.print.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.print.base.entity.PrintTemplate;
import com.unique.unexamine.print.base.mapper.PrintTemplateMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class PrintTemplateBaseService {
    private final PrintTemplateMapper mapper;

    public PrintTemplateBaseService(PrintTemplateMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(PrintTemplate entity) {
        return mapper.insert(entity);
    }

    public PrintTemplate selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<PrintTemplate> selectList(Wrapper<PrintTemplate> query) {
        return mapper.selectList(query);
    }

    public int updateById(PrintTemplate entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
