CREATE TABLE un_sys_idempotency (
    id BIGINT NOT NULL,
    scope_type VARCHAR(32) NOT NULL,
    scope_key VARCHAR(128) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    request_hash CHAR(64) NOT NULL,
    status VARCHAR(24) NOT NULL,
    response_http_status INT NULL,
    response_code VARCHAR(64) NULL,
    response_body MEDIUMTEXT NULL,
    locked_until DATETIME(3) NULL,
    expires_at DATETIME(3) NOT NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_sys_idempotency_scope_key (scope_type, scope_key, idempotency_key),
    KEY idx_sys_idempotency_expiry (expires_at),
    CONSTRAINT ck_sys_idempotency_status CHECK (status IN ('PROCESSING', 'COMPLETED', 'FAILED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE un_sys_outbox_event (
    id BIGINT NOT NULL,
    event_type VARCHAR(96) NOT NULL,
    event_version INT NOT NULL,
    aggregate_type VARCHAR(64) NOT NULL,
    aggregate_id VARCHAR(64) NOT NULL,
    system_id BIGINT NULL,
    tenant_id BIGINT NULL,
    dedupe_key VARCHAR(160) NOT NULL,
    payload_json JSON NOT NULL,
    trace_id VARCHAR(64) NOT NULL,
    status VARCHAR(24) NOT NULL,
    available_at DATETIME(3) NOT NULL,
    lease_until DATETIME(3) NULL,
    attempt_count INT NOT NULL DEFAULT 0,
    last_error VARCHAR(1000) NULL,
    published_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_sys_outbox_dedupe (dedupe_key),
    KEY idx_sys_outbox_dispatch (status, available_at, lease_until),
    CONSTRAINT ck_sys_outbox_status CHECK (status IN ('PENDING', 'PROCESSING', 'PUBLISHED', 'DEAD'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE un_sys_job (
    id BIGINT NOT NULL,
    job_type VARCHAR(64) NOT NULL,
    owner_type VARCHAR(64) NOT NULL,
    owner_id VARCHAR(64) NULL,
    system_id BIGINT NULL,
    tenant_id BIGINT NULL,
    requested_by BIGINT NULL,
    status VARCHAR(24) NOT NULL,
    progress_percent INT NOT NULL DEFAULT 0,
    input_json JSON NULL,
    result_json JSON NULL,
    result_file_id BIGINT NULL,
    attempt_count INT NOT NULL DEFAULT 0,
    max_attempts INT NOT NULL DEFAULT 3,
    available_at DATETIME(3) NOT NULL,
    lease_until DATETIME(3) NULL,
    last_error VARCHAR(1000) NULL,
    started_at DATETIME(3) NULL,
    finished_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    KEY idx_sys_job_queue (status, available_at, lease_until),
    KEY idx_sys_job_owner (owner_type, owner_id, created_at),
    CONSTRAINT ck_sys_job_status CHECK (status IN ('QUEUED', 'RUNNING', 'SUCCEEDED', 'PARTIAL', 'FAILED', 'CANCELLED')),
    CONSTRAINT ck_sys_job_progress CHECK (progress_percent BETWEEN 0 AND 100),
    CONSTRAINT ck_sys_job_attempts CHECK (attempt_count >= 0 AND max_attempts > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE un_audit_security (
    id BIGINT NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    account_id BIGINT NULL,
    account_hint VARCHAR(160) NULL,
    system_id BIGINT NULL,
    tenant_id BIGINT NULL,
    source_type VARCHAR(24) NOT NULL,
    remote_address VARCHAR(64) NULL,
    user_agent VARCHAR(500) NULL,
    request_id VARCHAR(64) NOT NULL,
    trace_id VARCHAR(64) NOT NULL,
    result VARCHAR(24) NOT NULL,
    failure_code VARCHAR(64) NULL,
    detail_json JSON NULL,
    created_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    KEY idx_audit_security_account (account_id, created_at),
    KEY idx_audit_security_request (request_id),
    KEY idx_audit_security_created (created_at),
    CONSTRAINT ck_audit_security_result CHECK (result IN ('SUCCESS', 'DENIED', 'FAILED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE un_audit_operation (
    id BIGINT NOT NULL,
    operation_type VARCHAR(64) NOT NULL,
    aggregate_type VARCHAR(64) NOT NULL,
    aggregate_id VARCHAR(64) NULL,
    actor_account_id BIGINT NULL,
    context_type VARCHAR(16) NOT NULL,
    system_id BIGINT NULL,
    tenant_id BIGINT NULL,
    source_type VARCHAR(24) NOT NULL,
    request_id VARCHAR(64) NOT NULL,
    trace_id VARCHAR(64) NOT NULL,
    result VARCHAR(24) NOT NULL,
    before_json JSON NULL,
    after_json JSON NULL,
    failure_code VARCHAR(64) NULL,
    created_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    KEY idx_audit_operation_aggregate (aggregate_type, aggregate_id, created_at),
    KEY idx_audit_operation_context (system_id, tenant_id, created_at),
    KEY idx_audit_operation_trace (trace_id),
    CONSTRAINT ck_audit_operation_context CHECK (context_type IN ('PLATFORM', 'SYSTEM')),
    CONSTRAINT ck_audit_operation_result CHECK (result IN ('SUCCESS', 'DENIED', 'FAILED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE un_plat_account (
    id BIGINT NOT NULL,
    account_code VARCHAR(64) NOT NULL,
    username VARCHAR(80) NOT NULL,
    username_normalized VARCHAR(80) NOT NULL,
    email VARCHAR(254) NULL,
    email_normalized VARCHAR(254) NULL,
    phone VARCHAR(32) NULL,
    display_name VARCHAR(120) NOT NULL,
    locale VARCHAR(16) NOT NULL DEFAULT 'zh-CN',
    time_zone VARCHAR(64) NOT NULL DEFAULT 'Asia/Shanghai',
    status VARCHAR(24) NOT NULL,
    last_login_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL,
    created_by BIGINT NULL,
    updated_at DATETIME(3) NOT NULL,
    updated_by BIGINT NULL,
    deleted_at DATETIME(3) NULL,
    deleted_by BIGINT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_plat_account_code (account_code),
    UNIQUE KEY uk_plat_account_username (username_normalized),
    UNIQUE KEY uk_plat_account_email (email_normalized),
    KEY idx_plat_account_status (status, created_at),
    CONSTRAINT ck_plat_account_status CHECK (status IN ('ACTIVE', 'LOCKED', 'DISABLED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE un_plat_credential (
    id BIGINT NOT NULL,
    account_id BIGINT NOT NULL,
    credential_type VARCHAR(24) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    password_algorithm VARCHAR(32) NOT NULL,
    password_parameters VARCHAR(255) NOT NULL,
    failed_attempts INT NOT NULL DEFAULT 0,
    locked_until DATETIME(3) NULL,
    password_changed_at DATETIME(3) NOT NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_plat_credential_account_type (account_id, credential_type),
    CONSTRAINT fk_plat_credential_account FOREIGN KEY (account_id) REFERENCES un_plat_account (id),
    CONSTRAINT ck_plat_credential_type CHECK (credential_type IN ('PASSWORD')),
    CONSTRAINT ck_plat_credential_failed CHECK (failed_attempts >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE un_plat_system (
    id BIGINT NOT NULL,
    system_code VARCHAR(64) NOT NULL,
    name VARCHAR(160) NOT NULL,
    description VARCHAR(1000) NULL,
    status VARCHAR(24) NOT NULL,
    tenant_mode VARCHAR(16) NOT NULL,
    owner_account_id BIGINT NOT NULL,
    permission_version BIGINT NOT NULL DEFAULT 1,
    initialized_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL,
    created_by BIGINT NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    updated_by BIGINT NOT NULL,
    archived_at DATETIME(3) NULL,
    deleted_at DATETIME(3) NULL,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_plat_system_code (system_code),
    KEY idx_plat_system_owner (owner_account_id, status),
    CONSTRAINT fk_plat_system_owner FOREIGN KEY (owner_account_id) REFERENCES un_plat_account (id),
    CONSTRAINT ck_plat_system_status CHECK (status IN ('INITIALIZING', 'ACTIVE', 'DISABLED', 'ARCHIVED')),
    CONSTRAINT ck_plat_system_tenant_mode CHECK (tenant_mode IN ('SINGLE', 'MULTI'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE un_plat_tenant (
    id BIGINT NOT NULL,
    system_id BIGINT NOT NULL,
    tenant_code VARCHAR(64) NOT NULL,
    name VARCHAR(160) NOT NULL,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(24) NOT NULL,
    created_at DATETIME(3) NOT NULL,
    created_by BIGINT NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    updated_by BIGINT NOT NULL,
    deleted_at DATETIME(3) NULL,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_plat_tenant_code (system_id, tenant_code),
    KEY idx_plat_tenant_default (system_id, is_default, status),
    CONSTRAINT fk_plat_tenant_system FOREIGN KEY (system_id) REFERENCES un_plat_system (id),
    CONSTRAINT ck_plat_tenant_status CHECK (status IN ('ACTIVE', 'DISABLED', 'ARCHIVED')),
    CONSTRAINT ck_plat_tenant_default CHECK (is_default IN (0, 1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE un_plat_member (
    id BIGINT NOT NULL,
    system_id BIGINT NOT NULL,
    account_id BIGINT NOT NULL,
    member_code VARCHAR(64) NOT NULL,
    display_name VARCHAR(120) NOT NULL,
    default_tenant_id BIGINT NOT NULL,
    status VARCHAR(24) NOT NULL,
    joined_at DATETIME(3) NOT NULL,
    created_at DATETIME(3) NOT NULL,
    created_by BIGINT NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    updated_by BIGINT NOT NULL,
    deleted_at DATETIME(3) NULL,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_plat_member_account (system_id, account_id),
    UNIQUE KEY uk_plat_member_code (system_id, member_code),
    KEY idx_plat_member_tenant (system_id, default_tenant_id, status),
    CONSTRAINT fk_plat_member_system FOREIGN KEY (system_id) REFERENCES un_plat_system (id),
    CONSTRAINT fk_plat_member_account FOREIGN KEY (account_id) REFERENCES un_plat_account (id),
    CONSTRAINT fk_plat_member_tenant FOREIGN KEY (default_tenant_id) REFERENCES un_plat_tenant (id),
    CONSTRAINT ck_plat_member_status CHECK (status IN ('ACTIVE', 'DISABLED', 'PENDING'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE un_plat_role (
    id BIGINT NOT NULL,
    scope_type VARCHAR(16) NOT NULL,
    scope_key BIGINT NOT NULL,
    system_id BIGINT NULL,
    tenant_id BIGINT NULL,
    role_code VARCHAR(64) NOT NULL,
    name VARCHAR(120) NOT NULL,
    role_type VARCHAR(24) NOT NULL,
    status VARCHAR(24) NOT NULL,
    permission_version BIGINT NOT NULL DEFAULT 1,
    created_at DATETIME(3) NOT NULL,
    created_by BIGINT NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    updated_by BIGINT NOT NULL,
    deleted_at DATETIME(3) NULL,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_plat_role_code (scope_type, scope_key, role_code),
    KEY idx_plat_role_system (system_id, tenant_id, status),
    CONSTRAINT fk_plat_role_system FOREIGN KEY (system_id) REFERENCES un_plat_system (id),
    CONSTRAINT fk_plat_role_tenant FOREIGN KEY (tenant_id) REFERENCES un_plat_tenant (id),
    CONSTRAINT ck_plat_role_scope CHECK ((scope_type = 'PLATFORM' AND scope_key = 0 AND system_id IS NULL AND tenant_id IS NULL) OR (scope_type = 'SYSTEM' AND scope_key = system_id AND system_id IS NOT NULL)),
    CONSTRAINT ck_plat_role_type CHECK (role_type IN ('ROOT', 'ADMIN', 'MEMBER', 'CUSTOM')),
    CONSTRAINT ck_plat_role_status CHECK (status IN ('ACTIVE', 'DISABLED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE un_plat_permission (
    id BIGINT NOT NULL,
    scope_type VARCHAR(16) NOT NULL,
    scope_key BIGINT NOT NULL,
    system_id BIGINT NULL,
    permission_code VARCHAR(128) NOT NULL,
    name VARCHAR(160) NOT NULL,
    resource_type VARCHAR(32) NOT NULL,
    status VARCHAR(24) NOT NULL,
    created_at DATETIME(3) NOT NULL,
    created_by BIGINT NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    updated_by BIGINT NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_plat_permission_code (scope_type, scope_key, permission_code),
    KEY idx_plat_permission_system (system_id, status),
    CONSTRAINT fk_plat_permission_system FOREIGN KEY (system_id) REFERENCES un_plat_system (id),
    CONSTRAINT ck_plat_permission_scope CHECK ((scope_type = 'PLATFORM' AND scope_key = 0 AND system_id IS NULL) OR (scope_type = 'SYSTEM' AND scope_key = system_id AND system_id IS NOT NULL)),
    CONSTRAINT ck_plat_permission_status CHECK (status IN ('ACTIVE', 'DISABLED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE un_plat_role_permission (
    id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    effect VARCHAR(8) NOT NULL,
    created_at DATETIME(3) NOT NULL,
    created_by BIGINT NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_plat_role_permission (role_id, permission_id),
    CONSTRAINT fk_plat_role_permission_role FOREIGN KEY (role_id) REFERENCES un_plat_role (id),
    CONSTRAINT fk_plat_role_permission_permission FOREIGN KEY (permission_id) REFERENCES un_plat_permission (id),
    CONSTRAINT ck_plat_role_permission_effect CHECK (effect IN ('ALLOW', 'DENY'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE un_plat_member_role (
    id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    tenant_id BIGINT NULL,
    valid_from DATETIME(3) NOT NULL,
    valid_until DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL,
    created_by BIGINT NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_plat_member_role (member_id, role_id, tenant_id),
    KEY idx_plat_member_role_valid (member_id, valid_from, valid_until),
    CONSTRAINT fk_plat_member_role_member FOREIGN KEY (member_id) REFERENCES un_plat_member (id),
    CONSTRAINT fk_plat_member_role_role FOREIGN KEY (role_id) REFERENCES un_plat_role (id),
    CONSTRAINT fk_plat_member_role_tenant FOREIGN KEY (tenant_id) REFERENCES un_plat_tenant (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE un_plat_context_session (
    id BIGINT NOT NULL,
    token_hash CHAR(64) NOT NULL,
    context_type VARCHAR(16) NOT NULL,
    account_id BIGINT NOT NULL,
    system_id BIGINT NULL,
    tenant_id BIGINT NULL,
    member_id BIGINT NULL,
    permission_version BIGINT NOT NULL,
    permissions_json JSON NOT NULL,
    status VARCHAR(24) NOT NULL,
    issued_at DATETIME(3) NOT NULL,
    expires_at DATETIME(3) NOT NULL,
    last_seen_at DATETIME(3) NOT NULL,
    revoked_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_plat_context_token (token_hash),
    KEY idx_plat_context_account (account_id, status, expires_at),
    KEY idx_plat_context_system (system_id, member_id, tenant_id, status),
    CONSTRAINT fk_plat_context_account FOREIGN KEY (account_id) REFERENCES un_plat_account (id),
    CONSTRAINT fk_plat_context_system FOREIGN KEY (system_id) REFERENCES un_plat_system (id),
    CONSTRAINT fk_plat_context_tenant FOREIGN KEY (tenant_id) REFERENCES un_plat_tenant (id),
    CONSTRAINT fk_plat_context_member FOREIGN KEY (member_id) REFERENCES un_plat_member (id),
    CONSTRAINT ck_plat_context_shape CHECK ((context_type = 'PLATFORM' AND system_id IS NULL AND tenant_id IS NULL AND member_id IS NULL) OR (context_type = 'SYSTEM' AND system_id IS NOT NULL AND tenant_id IS NOT NULL AND member_id IS NOT NULL)),
    CONSTRAINT ck_plat_context_status CHECK (status IN ('ACTIVE', 'REVOKED', 'EXPIRED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE un_plat_refresh_token (
    id BIGINT NOT NULL,
    context_session_id BIGINT NOT NULL,
    token_hash CHAR(64) NOT NULL,
    token_family CHAR(36) NOT NULL,
    status VARCHAR(24) NOT NULL,
    issued_at DATETIME(3) NOT NULL,
    expires_at DATETIME(3) NOT NULL,
    used_at DATETIME(3) NULL,
    revoked_at DATETIME(3) NULL,
    rotated_to_id BIGINT NULL,
    created_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_plat_refresh_token_hash (token_hash),
    KEY idx_plat_refresh_family (token_family, status, expires_at),
    CONSTRAINT fk_plat_refresh_session FOREIGN KEY (context_session_id) REFERENCES un_plat_context_session (id),
    CONSTRAINT fk_plat_refresh_rotated FOREIGN KEY (rotated_to_id) REFERENCES un_plat_refresh_token (id),
    CONSTRAINT ck_plat_refresh_status CHECK (status IN ('ACTIVE', 'USED', 'REVOKED', 'EXPIRED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
