-- Cycle114 enterprise identity provider and MFA closure.
-- Enterprise identity credentials remain external SecretRefs; plaintext secrets are never persisted.
CREATE TABLE un_plat_identity_provider (
    id BIGINT NOT NULL,
    provider_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    name VARCHAR(160) NOT NULL,
    protocol VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    issuer_uri VARCHAR(1000) NULL,
    authorization_endpoint VARCHAR(1000) NULL,
    token_endpoint VARCHAR(1000) NULL,
    jwks_uri VARCHAR(1000) NULL,
    directory_endpoint VARCHAR(1000) NULL,
    client_id VARCHAR(255) NULL,
    secret_ref VARCHAR(512) NULL,
    secret_version VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    callback_uri VARCHAR(1000) NOT NULL,
    scopes VARCHAR(500) NOT NULL DEFAULT 'openid profile email',
    allowed_domains_json JSON NOT NULL,
    attribute_mapping_json JSON NOT NULL,
    jit_account BOOLEAN NOT NULL DEFAULT FALSE,
    jit_system_member BOOLEAN NOT NULL DEFAULT FALSE,
    system_id BIGINT NULL,
    tenant_id BIGINT NULL,
    mfa_policy VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'OPTIONAL',
    status VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'DRAFT',
    preflight_status VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'NOT_RUN',
    preflight_version BIGINT NULL,
    preflight_failure_code VARCHAR(96) NULL,
    preflight_at DATETIME(3) NULL,
    published_at DATETIME(3) NULL,
    disabled_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL,
    created_by BIGINT NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    updated_by BIGINT NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_plat_identity_provider_code (provider_code),
    KEY idx_plat_identity_provider_scope (system_id, tenant_id, status),
    CONSTRAINT fk_plat_identity_provider_system FOREIGN KEY (system_id) REFERENCES un_plat_system (id),
    CONSTRAINT fk_plat_identity_provider_tenant FOREIGN KEY (tenant_id) REFERENCES un_plat_tenant (id),
    CONSTRAINT fk_plat_identity_provider_scope FOREIGN KEY (system_id, tenant_id)
        REFERENCES un_plat_tenant (system_id, id),
    CONSTRAINT ck_plat_identity_provider_protocol CHECK (protocol IN ('OIDC','OAUTH2','SAML2','LDAP','AD','WECOM','DINGTALK')),
    CONSTRAINT ck_plat_identity_provider_status CHECK (status IN ('DRAFT','PUBLISHED','DISABLED')),
    CONSTRAINT ck_plat_identity_provider_preflight CHECK (preflight_status IN ('NOT_RUN','PASSED','FAILED')),
    CONSTRAINT ck_plat_identity_provider_mfa CHECK (mfa_policy IN ('DISABLED','OPTIONAL','REQUIRED')),
    CONSTRAINT ck_plat_identity_provider_scope CHECK ((system_id IS NULL AND tenant_id IS NULL) OR (system_id IS NOT NULL AND tenant_id IS NOT NULL)),
    CONSTRAINT ck_plat_identity_provider_jit CHECK (jit_system_member = FALSE OR (jit_account = TRUE AND system_id IS NOT NULL AND tenant_id IS NOT NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE un_plat_identity_binding (
    id BIGINT NOT NULL,
    provider_id BIGINT NOT NULL,
    external_user_id VARCHAR(255) NOT NULL,
    account_id BIGINT NOT NULL,
    system_id BIGINT NULL,
    tenant_id BIGINT NULL,
    member_id BIGINT NULL,
    email_normalized VARCHAR(254) NULL,
    external_department_id VARCHAR(255) NULL,
    attributes_json JSON NOT NULL,
    status VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'ACTIVE',
    last_login_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_plat_identity_binding_external (provider_id, external_user_id),
    UNIQUE KEY uk_plat_identity_binding_account (provider_id, account_id),
    KEY idx_plat_identity_binding_scope (system_id, tenant_id, account_id),
    CONSTRAINT fk_plat_identity_binding_provider FOREIGN KEY (provider_id) REFERENCES un_plat_identity_provider (id),
    CONSTRAINT fk_plat_identity_binding_account FOREIGN KEY (account_id) REFERENCES un_plat_account (id),
    CONSTRAINT fk_plat_identity_binding_system FOREIGN KEY (system_id) REFERENCES un_plat_system (id),
    CONSTRAINT fk_plat_identity_binding_tenant FOREIGN KEY (tenant_id) REFERENCES un_plat_tenant (id),
    CONSTRAINT fk_plat_identity_binding_member FOREIGN KEY (member_id) REFERENCES un_plat_member (id),
    CONSTRAINT fk_plat_identity_binding_scope FOREIGN KEY (system_id, tenant_id)
        REFERENCES un_plat_tenant (system_id, id),
    CONSTRAINT fk_plat_identity_binding_member_scope FOREIGN KEY (system_id, member_id)
        REFERENCES un_plat_member (system_id, id),
    CONSTRAINT fk_plat_identity_binding_member_tenant FOREIGN KEY (system_id, member_id, tenant_id)
        REFERENCES un_plat_member_tenant (system_id, member_id, tenant_id),
    CONSTRAINT ck_plat_identity_binding_status CHECK (status IN ('ACTIVE','DISABLED')),
    CONSTRAINT ck_plat_identity_binding_scope CHECK ((system_id IS NULL AND tenant_id IS NULL AND member_id IS NULL) OR (system_id IS NOT NULL AND tenant_id IS NOT NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE un_plat_identity_auth_state (
    id BIGINT NOT NULL,
    state_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    provider_id BIGINT NOT NULL,
    system_id BIGINT NULL,
    tenant_id BIGINT NULL,
    redirect_uri VARCHAR(1000) NULL,
    nonce VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    code_verifier VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    status VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'ACTIVE',
    expires_at DATETIME(3) NOT NULL,
    consumed_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_plat_identity_auth_state_hash (state_hash),
    KEY idx_plat_identity_auth_state_expiry (status, expires_at),
    CONSTRAINT fk_plat_identity_auth_state_provider FOREIGN KEY (provider_id) REFERENCES un_plat_identity_provider (id),
    CONSTRAINT fk_plat_identity_auth_state_scope FOREIGN KEY (system_id, tenant_id)
        REFERENCES un_plat_tenant (system_id, id),
    CONSTRAINT ck_plat_identity_auth_state_status CHECK (status IN ('ACTIVE','CONSUMED','EXPIRED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE un_plat_mfa_enrollment (
    id BIGINT NOT NULL,
    account_id BIGINT NOT NULL,
    system_id BIGINT NULL,
    tenant_id BIGINT NULL,
    scope_system_id BIGINT GENERATED ALWAYS AS (IFNULL(system_id, 0)) STORED,
    scope_tenant_id BIGINT GENERATED ALWAYS AS (IFNULL(tenant_id, 0)) STORED,
    secret_ref VARCHAR(512) NOT NULL,
    secret_version VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    status VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'ACTIVE',
    verified_at DATETIME(3) NOT NULL,
    last_used_step BIGINT NULL,
    recovery_regenerated_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_plat_mfa_enrollment_scope (account_id, scope_system_id, scope_tenant_id),
    CONSTRAINT fk_plat_mfa_enrollment_account FOREIGN KEY (account_id) REFERENCES un_plat_account (id),
    CONSTRAINT fk_plat_mfa_enrollment_system FOREIGN KEY (system_id) REFERENCES un_plat_system (id),
    CONSTRAINT fk_plat_mfa_enrollment_tenant FOREIGN KEY (tenant_id) REFERENCES un_plat_tenant (id),
    CONSTRAINT fk_plat_mfa_enrollment_scope FOREIGN KEY (system_id, tenant_id)
        REFERENCES un_plat_tenant (system_id, id),
    CONSTRAINT ck_plat_mfa_enrollment_status CHECK (status IN ('ACTIVE','DISABLED')),
    CONSTRAINT ck_plat_mfa_enrollment_scope CHECK ((system_id IS NULL AND tenant_id IS NULL) OR (system_id IS NOT NULL AND tenant_id IS NOT NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE un_plat_mfa_recovery_code (
    id BIGINT NOT NULL,
    enrollment_id BIGINT NOT NULL,
    code_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    status VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'ACTIVE',
    used_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_plat_mfa_recovery_hash (enrollment_id, code_hash),
    CONSTRAINT fk_plat_mfa_recovery_enrollment FOREIGN KEY (enrollment_id) REFERENCES un_plat_mfa_enrollment (id) ON DELETE CASCADE,
    CONSTRAINT ck_plat_mfa_recovery_status CHECK (status IN ('ACTIVE','USED','REVOKED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE un_plat_mfa_challenge (
    id BIGINT NOT NULL,
    challenge_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    provider_id BIGINT NOT NULL,
    account_id BIGINT NOT NULL,
    system_id BIGINT NULL,
    tenant_id BIGINT NULL,
    auth_method VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    status VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'ACTIVE',
    expires_at DATETIME(3) NOT NULL,
    consumed_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_plat_mfa_challenge_hash (challenge_hash),
    KEY idx_plat_mfa_challenge_expiry (status, expires_at),
    CONSTRAINT fk_plat_mfa_challenge_provider FOREIGN KEY (provider_id) REFERENCES un_plat_identity_provider (id),
    CONSTRAINT fk_plat_mfa_challenge_account FOREIGN KEY (account_id) REFERENCES un_plat_account (id),
    CONSTRAINT fk_plat_mfa_challenge_scope FOREIGN KEY (system_id, tenant_id)
        REFERENCES un_plat_tenant (system_id, id),
    CONSTRAINT ck_plat_mfa_challenge_status CHECK (status IN ('ACTIVE','CONSUMED','EXPIRED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
