// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.audit.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.audit.base.entity.AuditEvent;
import com.unique.unexamine.audit.base.mapper.AuditEventMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class AuditEventBaseService {
    private final AuditEventMapper mapper;

    public AuditEventBaseService(AuditEventMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(AuditEvent entity) {
        return mapper.insert(entity);
    }

    public AuditEvent selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<AuditEvent> selectList(Wrapper<AuditEvent> query) {
        return mapper.selectList(query);
    }
}
