// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.audit.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.audit.base.entity.AuditFieldChange;
import com.unique.unexamine.audit.base.mapper.AuditFieldChangeMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class AuditFieldChangeBaseService {
    private final AuditFieldChangeMapper mapper;

    public AuditFieldChangeBaseService(AuditFieldChangeMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(AuditFieldChange entity) {
        return mapper.insert(entity);
    }

    public AuditFieldChange selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<AuditFieldChange> selectList(Wrapper<AuditFieldChange> query) {
        return mapper.selectList(query);
    }
}
