// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.audit.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.audit.base.entity.AuditRetentionMarker;
import com.unique.unexamine.audit.base.mapper.AuditRetentionMarkerMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class AuditRetentionMarkerBaseService {
    private final AuditRetentionMarkerMapper mapper;

    public AuditRetentionMarkerBaseService(AuditRetentionMarkerMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(AuditRetentionMarker entity) {
        return mapper.insert(entity);
    }

    public AuditRetentionMarker selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<AuditRetentionMarker> selectList(Wrapper<AuditRetentionMarker> query) {
        return mapper.selectList(query);
    }
}
