// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.application.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.application.base.entity.AppCallNonce;
import com.unique.unexamine.application.base.mapper.AppCallNonceMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class AppCallNonceBaseService {
    private final AppCallNonceMapper mapper;

    public AppCallNonceBaseService(AppCallNonceMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(AppCallNonce entity) {
        return mapper.insert(entity);
    }

    public AppCallNonce selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<AppCallNonce> selectList(Wrapper<AppCallNonce> query) {
        return mapper.selectList(query);
    }
}
