// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.application.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.application.base.entity.AppCall;
import com.unique.unexamine.application.base.mapper.AppCallMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class AppCallBaseService {
    private final AppCallMapper mapper;

    public AppCallBaseService(AppCallMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(AppCall entity) {
        return mapper.insert(entity);
    }

    public AppCall selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<AppCall> selectList(Wrapper<AppCall> query) {
        return mapper.selectList(query);
    }

    public int updateById(AppCall entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
