// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.application.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.application.base.entity.AppCredential;
import com.unique.unexamine.application.base.mapper.AppCredentialMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class AppCredentialBaseService {
    private final AppCredentialMapper mapper;

    public AppCredentialBaseService(AppCredentialMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(AppCredential entity) {
        return mapper.insert(entity);
    }

    public AppCredential selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<AppCredential> selectList(Wrapper<AppCredential> query) {
        return mapper.selectList(query);
    }

    public int updateById(AppCredential entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
