// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.application.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.application.base.entity.AppDefinition;
import com.unique.unexamine.application.base.mapper.AppDefinitionMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class AppDefinitionBaseService {
    private final AppDefinitionMapper mapper;

    public AppDefinitionBaseService(AppDefinitionMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(AppDefinition entity) {
        return mapper.insert(entity);
    }

    public AppDefinition selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<AppDefinition> selectList(Wrapper<AppDefinition> query) {
        return mapper.selectList(query);
    }

    public int updateById(AppDefinition entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
