// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.application.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.application.base.entity.AppGrant;
import com.unique.unexamine.application.base.mapper.AppGrantMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class AppGrantBaseService {
    private final AppGrantMapper mapper;

    public AppGrantBaseService(AppGrantMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(AppGrant entity) {
        return mapper.insert(entity);
    }

    public AppGrant selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<AppGrant> selectList(Wrapper<AppGrant> query) {
        return mapper.selectList(query);
    }

    public int updateById(AppGrant entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
