// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.application.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.application.base.entity.AppVersion;
import com.unique.unexamine.application.base.mapper.AppVersionMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class AppVersionBaseService {
    private final AppVersionMapper mapper;

    public AppVersionBaseService(AppVersionMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(AppVersion entity) {
        return mapper.insert(entity);
    }

    public AppVersion selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<AppVersion> selectList(Wrapper<AppVersion> query) {
        return mapper.selectList(query);
    }
}
