// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.file.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.file.base.entity.FileUploadSession;
import com.unique.unexamine.file.base.mapper.FileUploadSessionMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class FileUploadSessionBaseService {
    private final FileUploadSessionMapper mapper;

    public FileUploadSessionBaseService(FileUploadSessionMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(FileUploadSession entity) {
        return mapper.insert(entity);
    }

    public FileUploadSession selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<FileUploadSession> selectList(Wrapper<FileUploadSession> query) {
        return mapper.selectList(query);
    }

    public int updateById(FileUploadSession entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
