// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.file.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.file.base.entity.FileSecurityScan;
import com.unique.unexamine.file.base.mapper.FileSecurityScanMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class FileSecurityScanBaseService {
    private final FileSecurityScanMapper mapper;

    public FileSecurityScanBaseService(FileSecurityScanMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(FileSecurityScan entity) {
        return mapper.insert(entity);
    }

    public FileSecurityScan selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<FileSecurityScan> selectList(Wrapper<FileSecurityScan> query) {
        return mapper.selectList(query);
    }

    public int updateById(FileSecurityScan entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
