// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.file.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.file.base.entity.FileReference;
import com.unique.unexamine.file.base.mapper.FileReferenceMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class FileReferenceBaseService {
    private final FileReferenceMapper mapper;

    public FileReferenceBaseService(FileReferenceMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(FileReference entity) {
        return mapper.insert(entity);
    }

    public FileReference selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<FileReference> selectList(Wrapper<FileReference> query) {
        return mapper.selectList(query);
    }

    public int updateById(FileReference entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
