// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.file.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.file.base.entity.FileObject;
import com.unique.unexamine.file.base.mapper.FileObjectMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class FileObjectBaseService {
    private final FileObjectMapper mapper;

    public FileObjectBaseService(FileObjectMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(FileObject entity) {
        return mapper.insert(entity);
    }

    public FileObject selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<FileObject> selectList(Wrapper<FileObject> query) {
        return mapper.selectList(query);
    }

    public int updateById(FileObject entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
