// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.messagelog.base.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.unique.examine.messagelog.base.entity.AuditBusinessLog;

import org.apache.ibatis.annotations.Mapper;

/**
 * Generated mapper contract for table `un_audit_business_log`.
 */
@Mapper
public interface AuditBusinessLogMapper extends BaseMapper<AuditBusinessLog> {

    String TABLE_NAME = AuditBusinessLog.TABLE_NAME;
}
