// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.messagelog.base.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.unique.examine.messagelog.base.entity.AuditLogExportTask;

import org.apache.ibatis.annotations.Mapper;

/**
 * Generated mapper contract for table `un_audit_log_export_task`.
 */
@Mapper
public interface AuditLogExportTaskMapper extends BaseMapper<AuditLogExportTask> {

    String TABLE_NAME = AuditLogExportTask.TABLE_NAME;
}
