// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.messagelog.base.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.unique.examine.messagelog.base.entity.AuditLoginLog;

import org.apache.ibatis.annotations.Mapper;

/**
 * Generated mapper contract for table `un_audit_login_log`.
 */
@Mapper
public interface AuditLoginLogMapper extends BaseMapper<AuditLoginLog> {

    String TABLE_NAME = AuditLoginLog.TABLE_NAME;
}
