// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.messagelog.base.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.unique.examine.messagelog.base.entity.MessageMessage;

import org.apache.ibatis.annotations.Mapper;

/**
 * Generated mapper contract for table `un_message_message`.
 */
@Mapper
public interface MessageMessageMapper extends BaseMapper<MessageMessage> {

    String TABLE_NAME = MessageMessage.TABLE_NAME;
}
