// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.messagelog.base.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.unique.examine.messagelog.base.entity.MessageTarget;

import org.apache.ibatis.annotations.Mapper;

/**
 * Generated mapper contract for table `un_message_target`.
 */
@Mapper
public interface MessageTargetMapper extends BaseMapper<MessageTarget> {

    String TABLE_NAME = MessageTarget.TABLE_NAME;
}
