// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.messagelog.base.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.unique.examine.messagelog.base.entity.MessageNotificationTemplate;

import org.apache.ibatis.annotations.Mapper;

/**
 * Generated mapper contract for table `un_message_notification_template`.
 */
@Mapper
public interface MessageNotificationTemplateMapper extends BaseMapper<MessageNotificationTemplate> {

    String TABLE_NAME = MessageNotificationTemplate.TABLE_NAME;
}
