// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.messagelog.base.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.unique.examine.messagelog.base.entity.MessageTodo;

import org.apache.ibatis.annotations.Mapper;

/**
 * Generated mapper contract for table `un_message_todo`.
 */
@Mapper
public interface MessageTodoMapper extends BaseMapper<MessageTodo> {

    String TABLE_NAME = MessageTodo.TABLE_NAME;
}
