// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.aiwork.base.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.unique.examine.aiwork.base.entity.AgentSession;

import org.apache.ibatis.annotations.Mapper;

/**
 * Generated mapper contract for table `un_agent_session`.
 */
@Mapper
public interface AgentSessionMapper extends BaseMapper<AgentSession> {

    String TABLE_NAME = AgentSession.TABLE_NAME;
}
