// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.aiwork.base.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.unique.examine.aiwork.base.entity.AgentAuditLog;

import org.apache.ibatis.annotations.Mapper;

/**
 * Generated mapper contract for table `un_agent_audit_log`.
 */
@Mapper
public interface AgentAuditLogMapper extends BaseMapper<AgentAuditLog> {

    String TABLE_NAME = AgentAuditLog.TABLE_NAME;
}
