// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.aiwork.base.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.unique.examine.aiwork.base.entity.AgentConfirmation;

import org.apache.ibatis.annotations.Mapper;

/**
 * Generated mapper contract for table `un_agent_confirmation`.
 */
@Mapper
public interface AgentConfirmationMapper extends BaseMapper<AgentConfirmation> {

    String TABLE_NAME = AgentConfirmation.TABLE_NAME;
}
