// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.aiwork.base.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.unique.examine.aiwork.base.entity.WorkDailyReport;

import org.apache.ibatis.annotations.Mapper;

/**
 * Generated mapper contract for table `un_work_daily_report`.
 */
@Mapper
public interface WorkDailyReportMapper extends BaseMapper<WorkDailyReport> {

    String TABLE_NAME = WorkDailyReport.TABLE_NAME;
}
