// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.aiwork.base.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.unique.examine.aiwork.base.entity.WorkTaskEvent;

import org.apache.ibatis.annotations.Mapper;

/**
 * Generated mapper contract for table `un_work_task_event`.
 */
@Mapper
public interface WorkTaskEventMapper extends BaseMapper<WorkTaskEvent> {

    String TABLE_NAME = WorkTaskEvent.TABLE_NAME;
}
