// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.aiwork.base.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.unique.examine.aiwork.base.entity.WorkDailyReportSource;

import org.apache.ibatis.annotations.Mapper;

/**
 * Generated mapper contract for table `un_work_daily_report_source`.
 */
@Mapper
public interface WorkDailyReportSourceMapper extends BaseMapper<WorkDailyReportSource> {

    String TABLE_NAME = WorkDailyReportSource.TABLE_NAME;
}
