// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.flow.base.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.unique.examine.flow.base.entity.FlowApprovalActionLog;

import org.apache.ibatis.annotations.Mapper;

/**
 * Generated mapper contract for table `un_flow_approval_action_log`.
 */
@Mapper
public interface FlowApprovalActionLogMapper extends BaseMapper<FlowApprovalActionLog> {

    String TABLE_NAME = FlowApprovalActionLog.TABLE_NAME;
}
