// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.flow.base.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.unique.examine.flow.base.entity.FlowSimulationLog;

import org.apache.ibatis.annotations.Mapper;

/**
 * Generated mapper contract for table `un_flow_simulation_log`.
 */
@Mapper
public interface FlowSimulationLogMapper extends BaseMapper<FlowSimulationLog> {

    String TABLE_NAME = FlowSimulationLog.TABLE_NAME;
}
