// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.flow.base.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.unique.examine.flow.base.entity.FlowApprovalTask;

import org.apache.ibatis.annotations.Mapper;

/**
 * Generated mapper contract for table `un_flow_approval_task`.
 */
@Mapper
public interface FlowApprovalTaskMapper extends BaseMapper<FlowApprovalTask> {

    String TABLE_NAME = FlowApprovalTask.TABLE_NAME;
}
