// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.flow.base.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.unique.examine.flow.base.entity.FlowDefinition;

import org.apache.ibatis.annotations.Mapper;

/**
 * Generated mapper contract for table `un_flow_definition`.
 */
@Mapper
public interface FlowDefinitionMapper extends BaseMapper<FlowDefinition> {

    String TABLE_NAME = FlowDefinition.TABLE_NAME;
}
