// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.flow.base.service;

import com.baomidou.mybatisplus.extension.service.IService;
import com.unique.examine.flow.base.entity.FlowSimulationLog;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

/**
 * Generated base service contract for FlowSimulationLog.
 */
public interface FlowSimulationLogBaseService extends IService<FlowSimulationLog> {

    Optional<FlowSimulationLog> findById(Long id);

    List<FlowSimulationLog> findAll();

    FlowSimulationLog saveEntity(FlowSimulationLog entity);

    boolean deleteByIds(Collection<Long> ids);
}
