// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.flow.base.service;

import com.baomidou.mybatisplus.extension.service.IService;
import com.unique.examine.flow.base.entity.FlowApprovalTask;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

/**
 * Generated base service contract for FlowApprovalTask.
 */
public interface FlowApprovalTaskBaseService extends IService<FlowApprovalTask> {

    Optional<FlowApprovalTask> findById(Long id);

    List<FlowApprovalTask> findAll();

    FlowApprovalTask saveEntity(FlowApprovalTask entity);

    boolean deleteByIds(Collection<Long> ids);
}
