// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.flow.base.service;

import com.baomidou.mybatisplus.extension.service.IService;
import com.unique.examine.flow.base.entity.FlowInstance;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

/**
 * Generated base service contract for FlowInstance.
 */
public interface FlowInstanceBaseService extends IService<FlowInstance> {

    Optional<FlowInstance> findById(Long id);

    List<FlowInstance> findAll();

    FlowInstance saveEntity(FlowInstance entity);

    boolean deleteByIds(Collection<Long> ids);
}
