// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.flow.base.service;

import com.baomidou.mybatisplus.extension.service.IService;
import com.unique.examine.flow.base.entity.FlowSnapshot;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

/**
 * Generated base service contract for FlowSnapshot.
 */
public interface FlowSnapshotBaseService extends IService<FlowSnapshot> {

    Optional<FlowSnapshot> findById(Long id);

    List<FlowSnapshot> findAll();

    FlowSnapshot saveEntity(FlowSnapshot entity);

    boolean deleteByIds(Collection<Long> ids);
}
