param(
    [string]$BaseUrl = 'http://127.0.0.1:18131',
    [switch]$NoFailExit
)

$ErrorActionPreference = 'Stop'
$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$EvidenceDir = Join-Path $RepoRoot 'docs/evidence/recovery'
$BrowserDir = Join-Path $EvidenceDir 'screenshots/r92-workflow-advanced-node-publish-impact'
$ResultPath = Join-Path $EvidenceDir 'r92-workflow-advanced-node-publish-impact-result.json'
$SummaryPath = Join-Path $EvidenceDir 'r92-workflow-advanced-node-publish-impact-2026-07-08.md'
$BrowserScriptPath = Join-Path $RepoRoot 'scripts/recovery-r92-browser-audit.js'
New-Item -ItemType Directory -Force -Path $EvidenceDir | Out-Null
New-Item -ItemType Directory -Force -Path $BrowserDir | Out-Null

function Invoke-Api {
    param([string]$Method, [string]$Path, [object]$Body = $null, [hashtable]$Headers = @{})
    $jsonBody = if ($null -eq $Body) { $null } else { $Body | ConvertTo-Json -Depth 100 -Compress }
    try {
        if ($null -eq $jsonBody) { $response = Invoke-RestMethod -Method $Method -Uri "$BaseUrl$Path" -Headers $Headers -TimeoutSec 60 }
        else { $response = Invoke-RestMethod -Method $Method -Uri "$BaseUrl$Path" -Headers $Headers -ContentType 'application/json; charset=utf-8' -Body $jsonBody -TimeoutSec 60 }
    } catch {
        $status = 0; $body = $_.Exception.Message
        if ($_.Exception.Response) { $status = [int]$_.Exception.Response.StatusCode; try { $body = ([System.IO.StreamReader]::new($_.Exception.Response.GetResponseStream())).ReadToEnd() } catch {} }
        throw "API failed: $Method $Path -> HTTP $status $body"
    }
    if ($response.code -ne 'SUCCESS') { throw "API failed: $Method $Path -> $($response | ConvertTo-Json -Depth 30 -Compress)" }
    return $response.data
}
function Invoke-ExpectedDenied { param([string]$Method, [string]$Path, [object]$Body = $null, [hashtable]$Headers = @{}) try { $null = Invoke-Api -Method $Method -Path $Path -Body $Body -Headers $Headers } catch { if ($_.Exception.Message -match 'HTTP 401|HTTP 403|PERMISSION_DENIED|没有系统后台管理权限|权限|无权') { return @{ status = 'DENIED'; path = $Path; detail = $_.Exception.Message } }; throw }; throw "Expected denied request but it succeeded: $Method $Path" }
function Add-Check([System.Collections.Generic.List[object]]$Checks, [string]$Area, [string]$Name, [bool]$Passed, [string]$Detail) { $Checks.Add([pscustomobject]@{ area = $Area; name = $Name; passed = $Passed; detail = $Detail }) | Out-Null }
function Read-DeployedAssetText { try { $index = (Invoke-WebRequest -Uri "$BaseUrl/" -UseBasicParsing -TimeoutSec 30).Content; $assetMatches = [regex]::Matches($index, 'src="(?<src>/assets/[^""<>]+\.js)"'); if ($assetMatches.Count -eq 0) { return '' }; $texts = New-Object System.Collections.Generic.List[string]; foreach ($match in $assetMatches) { $texts.Add((Invoke-WebRequest -Uri "$BaseUrl$($match.Groups['src'].Value)" -UseBasicParsing -TimeoutSec 30).Content) | Out-Null }; return ($texts -join "`n") } catch { return '' } }
function Get-FreeTcpPort { $listener = [System.Net.Sockets.TcpListener]::new([System.Net.IPAddress]::Loopback, 0); $listener.Start(); $port = $listener.LocalEndpoint.Port; $listener.Stop(); return $port }
function Find-Chrome { $paths = @("$env:ProgramFiles\Google\Chrome\Application\chrome.exe", "${env:ProgramFiles(x86)}\Google\Chrome\Application\chrome.exe", "$env:LocalAppData\Google\Chrome\Application\chrome.exe", "$env:ProgramFiles\Microsoft\Edge\Application\msedge.exe", "${env:ProgramFiles(x86)}\Microsoft\Edge\Application\msedge.exe"); foreach ($candidate in $paths) { if ($candidate -and (Test-Path -LiteralPath $candidate)) { return $candidate } }; throw 'Chrome or Edge executable was not found.' }
function Node { param([string]$Key, [string]$Type, [string]$Name, [int]$X, [int]$Y, [object]$Payload, [bool]$Runtime = $true) return @{ nodeKey = $Key; nodeType = $Type; nodeName = $Name; position = @{ x = $X; y = $Y; width = 180; height = 72 }; propertyPayload = $Payload; status = 1; runtimeExecutable = $Runtime } }
function Edge { param([string]$Key, [string]$Source, [string]$Target, [string]$Label, [object]$Condition = $null) return @{ edgeKey = $Key; sourceNodeKey = $Source; targetNodeKey = $Target; branchLabel = $Label; conditionPayload = $Condition } }
function New-R92Canvas { return @{ nodes = @((Node 'node_r92_approval' 'approval' 'R92 Approval' 80 150 @{ approvalType = 'OR_SIGN'; assigneeType = 'ROLE'; assigneeIds = @('role_flow_approver'); allowTransfer = $true; allowReject = $true; reasonRequired = $true }),(Node 'node_r92_condition' 'condition' 'R92 Amount Condition' 320 150 @{ ruleMode = 'FIRST_MATCH'; defaultBranchLabel = 'default'; unmatchedPolicy = 'FOLLOW_DEFAULT_BRANCH' }),(Node 'node_r92_external_api' 'external_api' 'R92 External API' 560 70 @{ appId = 'openapi_r92_app'; endpointCode = 'notify_external_system'; method = 'POST'; timeoutMs = 3000; retryPolicy = @{ maxRetries = 2; intervalSeconds = 30 } }),(Node 'node_r92_timer' 'timer' 'R92 Timer' 800 70 @{ timerMode = 'DELAY'; delayMinutes = 30; businessCalendarCode = 'default_workday'; maxTriggerCount = 1 }),(Node 'node_r92_field_update' 'field_update' 'R92 Field Update' 560 230 @{ updateRules = @(@{ fieldCode = 'approvalStatus'; valueExpression = 'APPROVED'; overwritePolicy = 'ALWAYS' }); auditReason = 'R92 publish impact verification' }),(Node 'node_r92_timeout' 'timeout_reminder' 'R92 Timeout Reminder' 800 230 @{ targetNodeKey = 'node_r92_approval'; timeoutMinutes = 60; templateCode = 'tpl_flow_timeout_reminder'; escalateToRoleIds = @('role_flow_admin') } $false),(Node 'node_r92_end' 'end' 'R92 End' 1040 150 @{})); edges = @((Edge 'edge_r92_approval_condition' 'node_r92_approval' 'node_r92_condition' 'approved'),(Edge 'edge_r92_condition_api' 'node_r92_condition' 'node_r92_external_api' 'amount >= 100000' @{ expressionId = 'expr_r92_amount_gte'; fieldCode = 'amount'; operator = 'GTE'; expectedValue = 100000; expressionText = 'amount GTE 100000' }),(Edge 'edge_r92_api_timer' 'node_r92_external_api' 'node_r92_timer' 'api success'),(Edge 'edge_r92_timer_end' 'node_r92_timer' 'node_r92_end' 'timer reached'),(Edge 'edge_r92_condition_field' 'node_r92_condition' 'node_r92_field_update' 'amount < 100000' @{ expressionId = 'expr_r92_amount_lt'; fieldCode = 'amount'; operator = 'LT'; expectedValue = 100000; expressionText = 'amount LT 100000' }),(Edge 'edge_r92_field_timeout' 'node_r92_field_update' 'node_r92_timeout' 'write back'),(Edge 'edge_r92_timeout_end' 'node_r92_timeout' 'node_r92_end' 'reminded')) } }

$checks = [System.Collections.Generic.List[object]]::new(); $stamp = Get-Date -Format 'yyyyMMddHHmmss'; $password = 'Aa123456!'; $adminLoginName = "r92_admin_$stamp"; $normalLoginName = "r92_normal_$stamp"; $systemId = ''; $moduleId = ''; $flowId = ''; $status = 'PASS'; $errorMessage = $null; $chromeProcess = $null; $chromeProfile = $null; $warningCodes = @(); $impactTypes = @(); $simHighTypes = @(); $simLowTypes = @(); $published = @{}; $r73Result = $null
try {
    $health = Invoke-Api -Method Get -Path '/api/v1/health'; Add-Check $checks 'release' 'release health is reachable' ($health.status -eq 'UP') "status=$($health.status)"
    $adminReg = Invoke-Api -Method Post -Path '/api/v1/auth/register-with-system' -Body @{ accountName = $adminLoginName; mobile = "139$($stamp.Substring($stamp.Length - 8))"; email = "$adminLoginName@example.test"; password = $password; systemName = "R92 Workflow System $stamp"; systemCode = "r92_sys_$stamp"; tenantMode = 1; templateCode = 'blank' }
    $systemId = [string]$adminReg.systemId; $adminHeaders = @{ Authorization = "Bearer $($adminReg.accessToken)" }
    $adminSwitch = Invoke-Api -Method Post -Path '/api/v1/platform/system-switch' -Headers $adminHeaders -Body @{ systemId = $systemId; tenantId = $null; reason = 'R92 workflow advanced setup' }
    Add-Check $checks 'setup' 'registered admin owns new system' (@($adminSwitch.effectiveRoleIds) -contains 'SYSTEM_SUPER_ADMIN') "system=$systemId"
    $normalReg = Invoke-Api -Method Post -Path '/api/v1/auth/register-with-system' -Body @{ accountName = $normalLoginName; mobile = "138$($stamp.Substring($stamp.Length - 8))"; email = "$normalLoginName@example.test"; password = $password; systemName = "R92 Normal Owned $stamp"; systemCode = "r92_normal_$stamp"; tenantMode = 1; templateCode = 'blank' }; $normalHeaders = @{ Authorization = "Bearer $($normalReg.accessToken)" }
    $group = Invoke-Api -Method Post -Path "/api/v1/systems/$systemId/module-groups" -Headers $adminHeaders -Body @{ name = "R92 Flow Group $stamp"; sort = 10; visibleRoleIds = @(); publishStatus = 'DRAFT' }
    $module = Invoke-Api -Method Post -Path "/api/v1/systems/$systemId/modules" -Headers $adminHeaders -Body @{ groupId = [string]$group.groupId; moduleCode = "r92_flow_case_$stamp"; name = "R92 Flow Case $stamp"; status = 1; description = 'R92 workflow advanced node module' }; $moduleId = [string]$module.moduleId
    $library = Invoke-Api -Method Get -Path "/api/v1/systems/$systemId/flows/node-library" -Headers $adminHeaders; $libraryTypes = @($library | ForEach-Object { [string]$_.nodeType }); $requiredLibrary = @('approval','condition','field_update','external_api','timer','timeout_reminder','end'); $missingLibrary = @($requiredLibrary | Where-Object { $libraryTypes -notcontains $_ }); Add-Check $checks 'api-library' 'advanced node library exposes required node types' ($missingLibrary.Count -eq 0) "types=$($libraryTypes -join ',') missing=$($missingLibrary -join ',')"
    $flow = Invoke-Api -Method Post -Path "/api/v1/systems/$systemId/flows" -Headers $adminHeaders -Body @{ flowCode = "r92_flow_$stamp"; flowName = "R92 Advanced Flow $stamp"; boundModuleId = $moduleId; status = 1; triggerRule = @{ triggerType = 'MANUAL_ACTION'; actionCodes = @('record.submitApproval'); conditionExpression = ''; manualStartAllowed = $true; idempotencyRequired = $true }; description = 'R92 advanced workflow publish impact closure' }; $flowId = [string]$flow.flowId
    $canvas = New-R92Canvas; $savedFlow = Invoke-Api -Method Put -Path "/api/v1/systems/$systemId/flows/$flowId/canvas" -Headers $adminHeaders -Body $canvas; $readCanvas = Invoke-Api -Method Get -Path "/api/v1/systems/$systemId/flows/$flowId/canvas" -Headers $adminHeaders; $readTypes = @($readCanvas.nodes | ForEach-Object { [string]$_.nodeType }); $missingReadTypes = @($requiredLibrary | Where-Object { $readTypes -notcontains $_ }); Add-Check $checks 'api-canvas' 'advanced canvas save/readback preserves node types and edges' (($missingReadTypes.Count -eq 0) -and (@($readCanvas.edges).Count -ge 7)) "nodes=$($readTypes -join ',') edges=$(@($readCanvas.edges).Count)"
    $externalPanel = Invoke-Api -Method Get -Path "/api/v1/systems/$systemId/flows/$flowId/nodes/node_r92_external_api/properties" -Headers $adminHeaders; Add-Check $checks 'api-properties' 'selected advanced node property panel is readable' (($externalPanel.nodeType -eq 'external_api') -and (@($externalPanel.propertySchema).Count -gt 0)) "nodeType=$($externalPanel.nodeType) fields=$(@($externalPanel.propertySchema).Count)"
    $publishCheck = Invoke-Api -Method Post -Path "/api/v1/systems/$systemId/flows/$flowId/publish-check" -Headers $adminHeaders -Body @{ reason = 'R92 publish impact check'; idempotencyKey = "r92-check-$stamp" }; $warningCodes = @($publishCheck.warningItems | ForEach-Object { [string]$_.itemCode }); $impactTypes = @($publishCheck.impactRefs | ForEach-Object { if ($_.objectType) { [string]$_.objectType } elseif ($_.refType) { [string]$_.refType } else { [string]$_.type } }); $requiredWarnings = @('W_EXTERNAL_API_SCOPE','W_TIMEOUT_TEMPLATE','W_TIMER_SCHEDULE','W_FIELD_UPDATE_PERMISSION'); $requiredImpacts = @('MODULE','FLOW_DEFINITION','OPENAPI_APP','FLOW_TIMER','MODULE_FIELD','MESSAGE_TEMPLATE','TODO_MESSAGE'); $missingWarnings = @($requiredWarnings | Where-Object { $warningCodes -notcontains $_ }); $missingImpacts = @($requiredImpacts | Where-Object { $impactTypes -notcontains $_ }); Add-Check $checks 'api-publish-check' 'publish check passes with advanced warnings and impact refs' (($publishCheck.passed -eq $true) -and ($missingWarnings.Count -eq 0) -and ($missingImpacts.Count -eq 0)) "warnings=$($warningCodes -join ',') impacts=$($impactTypes -join ',') trace=$($publishCheck.traceId)"
    $simulationHigh = Invoke-Api -Method Post -Path "/api/v1/systems/$systemId/flows/$flowId/simulate" -Headers $adminHeaders -Body @{ versionNo = 'DRAFT'; recordId = 'r92_preview_high'; actorMemberId = 'current_member'; startNodeKey = 'node_r92_approval'; fieldValues = @{ amount = 120000 }; idempotencyKey = "r92-sim-high-$stamp" }; $simHighTypes = @($simulationHigh.stepTraces | ForEach-Object { [string]$_.nodeType })
    $simulationLow = Invoke-Api -Method Post -Path "/api/v1/systems/$systemId/flows/$flowId/simulate" -Headers $adminHeaders -Body @{ versionNo = 'DRAFT'; recordId = 'r92_preview_low'; actorMemberId = 'current_member'; startNodeKey = 'node_r92_approval'; fieldValues = @{ amount = 10 }; idempotencyKey = "r92-sim-low-$stamp" }; $simLowTypes = @($simulationLow.stepTraces | ForEach-Object { [string]$_.nodeType })
    Add-Check $checks 'api-simulation' 'simulation covers external-api timer branch and field-update timeout branch without runtime instance' (($simulationHigh.passed -eq $true) -and ($simulationLow.passed -eq $true) -and ($simHighTypes -contains 'external_api') -and ($simHighTypes -contains 'timer') -and ($simLowTypes -contains 'field_update') -and ($simLowTypes -contains 'timeout_reminder') -and ($simulationHigh.runtimeInstanceCreated -eq $false) -and ($simulationLow.runtimeInstanceCreated -eq $false)) "high=$($simHighTypes -join ',') low=$($simLowTypes -join ',')"
    $published = Invoke-Api -Method Post -Path "/api/v1/systems/$systemId/flows/$flowId/publish" -Headers $adminHeaders -Body @{ reason = 'R92 publish advanced workflow'; idempotencyKey = "r92-publish-$stamp" }; $snapshots = Invoke-Api -Method Get -Path "/api/v1/systems/$systemId/flows/$flowId/snapshots" -Headers $adminHeaders; $impact = Invoke-Api -Method Get -Path "/api/v1/systems/$systemId/flows/$flowId/impact-analysis" -Headers $adminHeaders; Add-Check $checks 'api-publish' 'publish creates snapshot and impact analysis remains readable' (([string]$published.version).Length -gt 0 -and @($snapshots).Count -ge 1 -and @($impact.impactRefs).Count -ge $requiredImpacts.Count) "version=$($published.version) snapshots=$(@($snapshots).Count) impactRefs=$(@($impact.impactRefs).Count)"
    $normalDetailDenied = Invoke-ExpectedDenied -Method Get -Path "/api/v1/systems/$systemId/flows/$flowId" -Headers $normalHeaders; $normalCanvasDenied = Invoke-ExpectedDenied -Method Put -Path "/api/v1/systems/$systemId/flows/$flowId/canvas" -Headers $normalHeaders -Body $canvas; $normalCheckDenied = Invoke-ExpectedDenied -Method Post -Path "/api/v1/systems/$systemId/flows/$flowId/publish-check" -Headers $normalHeaders -Body @{ reason = 'forbidden'; idempotencyKey = "r92-forbidden-$stamp" }; Add-Check $checks 'permission' 'normal member cannot read mutate or publish-check target system flow admin APIs' (($normalDetailDenied.status -eq 'DENIED') -and ($normalCanvasDenied.status -eq 'DENIED') -and ($normalCheckDenied.status -eq 'DENIED')) "detail=$($normalDetailDenied.status) canvas=$($normalCanvasDenied.status) check=$($normalCheckDenied.status)"
    $sourceAdmin = Get-Content -Raw -Encoding UTF8 (Join-Path $RepoRoot 'frontend/src/features/system-admin/systemAdmin.ts'); $sourceFlow = Get-Content -Raw -Encoding UTF8 (Join-Path $RepoRoot 'backend/examine-flow/src/main/java/com/unique/examine/flow/manage/definition/FlowDefinitionService.java'); $deployedAssetText = Read-DeployedAssetText; $sourceMarkers = @('r92WorkflowDesigner','r92AdvancedNodeLibrary','r92PublishImpactSummary','createAdvancedFlowPreset','W_TIMER_SCHEDULE','WRITE_BACK_FIELD'); $deployedMarkers = @('r92WorkflowDesigner','r92AdvancedNodeLibrary','r92PublishImpactSummary','r92AdvancedPresetButton'); $missingSourceMarkers = @($sourceMarkers | Where-Object { $sourceAdmin -notmatch [regex]::Escape($_) -and $sourceFlow -notmatch [regex]::Escape($_) }); $missingDeployedMarkers = @($deployedMarkers | Where-Object { $deployedAssetText -notmatch [regex]::Escape($_) }); Add-Check $checks 'source' 'R92 source markers exist in frontend and flow service' ($missingSourceMarkers.Count -eq 0) "missing=$($missingSourceMarkers -join ',')"; Add-Check $checks 'deployed' 'deployed asset contains R92 designer markers' (($deployedAssetText.Length -gt 0) -and ($missingDeployedMarkers.Count -eq 0)) "assetLength=$($deployedAssetText.Length) missing=$($missingDeployedMarkers -join ',')"
    $debugPort = Get-FreeTcpPort; $chrome = Find-Chrome; $chromeProfile = Join-Path $BrowserDir "chrome-profile-$stamp"; New-Item -ItemType Directory -Force -Path $chromeProfile | Out-Null; $chromeProcess = Start-Process -FilePath $chrome -ArgumentList @('--headless=new','--disable-gpu','--disable-extensions','--no-sandbox','--no-first-run','--no-default-browser-check','--remote-allow-origins=*',"--remote-debugging-port=$debugPort","--user-data-dir=$chromeProfile",'about:blank') -PassThru -WindowStyle Hidden; $ready = $false; for ($i = 0; $i -lt 50; $i++) { try { Invoke-RestMethod -Uri "http://127.0.0.1:$debugPort/json/version" -TimeoutSec 2 | Out-Null; $ready = $true; break } catch { Start-Sleep -Milliseconds 200 } }; if (-not $ready) { throw 'Chrome DevTools endpoint did not become ready.' }
    $browserOut = Join-Path $BrowserDir 'workflow-advanced-node-browser-audit.json'; $env:R92_BASE_URL = $BaseUrl; $env:R92_CDP_PORT = [string]$debugPort; $env:R92_BROWSER_OUT = $browserOut; $env:R92_SYSTEM_ID = $systemId; $env:R92_FLOW_ID = $flowId; $env:R92_ADMIN_ACCESS_TOKEN = [string]$adminReg.accessToken; $env:R92_ADMIN_REFRESH_TOKEN = [string]$adminReg.refreshToken; $env:R92_ADMIN_ACCOUNT_ID = [string]$adminReg.accountId; $nodeExe = if (Test-Path 'D:\dev\nodejs24\node.exe') { 'D:\dev\nodejs24\node.exe' } else { 'node' }; $nodeOutput = & $nodeExe $BrowserScriptPath 2>&1; if ($LASTEXITCODE -ne 0) { throw "R92 browser audit failed: $nodeOutput" }; $browser = Get-Content -Raw -LiteralPath $browserOut | ConvertFrom-Json; if ($browser.error) { throw "R92 browser audit failed: $($browser.error)" }
    $browserResults = @($browser.results); $desktop = @($browserResults | Where-Object { $_.kind -eq 'admin-desktop-after' }) | Select-Object -First 1; $mobile = @($browserResults | Where-Object { $_.kind -eq 'admin-mobile' }) | Select-Object -First 1; $desktopTypes = @($desktop.nodeTypes); $browserMissingTypes = @($requiredLibrary | Where-Object { $desktopTypes -notcontains $_ }); $browserOverflowCount = @($browserResults | Where-Object { $_.overflowX -gt 2 }).Count; $browserBlockerCount = @($browserResults | Where-Object { $_.blockerText -eq $true }).Count; Add-Check $checks 'browser' 'admin browser exposes advanced library canvas properties publish impact and simulation' ($desktop.designer -and $desktop.advancedPresetButton -and $browserMissingTypes.Count -eq 0 -and $desktop.publishSummary -eq 'true' -and $desktop.publishImpactCount -ge 7 -and $desktop.publishWarningCount -ge 4 -and $desktop.simulationPassed -eq 'true' -and $desktop.simulationStepCount -ge 5) ($desktop | ConvertTo-Json -Depth 20 -Compress); Add-Check $checks 'browser' 'mobile workflow designer remains contained' ($mobile.designer -and $mobile.overflowX -eq 0) ($mobile | ConvertTo-Json -Depth 20 -Compress); Add-Check $checks 'browser' 'R92 browser audit has no overflow or blocker text' (($browserOverflowCount -eq 0) -and ($browserBlockerCount -eq 0)) "overflow=$browserOverflowCount blockers=$browserBlockerCount results=$($browserResults.Count)"
    $r73Script = Join-Path $RepoRoot 'scripts/recovery-r73-workflow-todo-message-error-state-residual.ps1'; $r73Out = & powershell -NoProfile -ExecutionPolicy Bypass -File $r73Script -BaseUrl $BaseUrl -NoFailExit 2>&1 | Out-String; $r73Path = Join-Path $RepoRoot 'docs/evidence/recovery/r73-workflow-todo-message-error-state-residual-result.json'; if (Test-Path -LiteralPath $r73Path) { $r73Result = Get-Content -Raw -Encoding UTF8 -LiteralPath $r73Path | ConvertFrom-Json }; Add-Check $checks 'runtime-child' 'fresh R73 runtime todo/message terminal reject transfer evidence passes' ($r73Result -and $r73Result.status -eq 'PASS' -and [int]$r73Result.terminalRejectConflictStatus -eq 400 -and [int]$r73Result.terminalTransferConflictStatus -eq 400 -and $r73Result.rejectDetailTerminalStatus -eq 'REJECTED') "status=$($r73Result.status) reject=$($r73Result.terminalRejectConflictStatus) transfer=$($r73Result.terminalTransferConflictStatus) rejectDetail=$($r73Result.rejectDetailTerminalStatus) out=$($r73Out.Substring(0, [Math]::Min(500, $r73Out.Length)))"
    $state = Get-Content -Raw -Encoding UTF8 (Join-Path $RepoRoot '.cursor/session/state.json') | ConvertFrom-Json; Add-Check $checks 'signoff-boundary' 'R92 does not close user signoff' ($state.gates.user_script_passed -eq $false) "user_script_passed=$($state.gates.user_script_passed)"
} catch { $status = 'FAIL'; $errorMessage = $_.Exception.Message; Add-Check $checks 'fatal' 'R92 script completed without fatal error' $false $errorMessage } finally { if ($chromeProcess -and -not $chromeProcess.HasExited) { Stop-Process -Id $chromeProcess.Id -Force -ErrorAction SilentlyContinue }; if ($chromeProfile -and (Test-Path -LiteralPath $chromeProfile)) { Remove-Item -LiteralPath $chromeProfile -Recurse -Force -ErrorAction SilentlyContinue } }
$failed = @($checks | Where-Object { -not $_.passed }); if ($failed.Count -gt 0) { $status = 'FAIL' }
$result = [ordered]@{ status = $status; task = 'REC-P0-092'; generatedAt = (Get-Date).ToString('o'); baseUrl = $BaseUrl; userSignoff = $false; systemId = $systemId; moduleId = $moduleId; flowId = $flowId; normalLoginName = $normalLoginName; checks = $checks; warningCodes = $warningCodes; impactTypes = $impactTypes; simulationHighNodeTypes = $simHighTypes; simulationLowNodeTypes = $simLowTypes; publishedVersion = $published.version; browserAudit = 'docs/evidence/recovery/screenshots/r92-workflow-advanced-node-publish-impact/workflow-advanced-node-browser-audit.json'; runtimeChildEvidence = 'docs/evidence/recovery/r73-workflow-todo-message-error-state-residual-result.json'; error = $errorMessage }
$result | ConvertTo-Json -Depth 100 | Set-Content -LiteralPath $ResultPath -Encoding UTF8
$summary = @('# R92 Workflow Advanced Node Publish Impact Evidence','',"- Status: $status","- BaseUrl: $BaseUrl","- System: $systemId","- Flow: $flowId","- Advanced warnings: $(@($warningCodes) -join ', ')","- Impact refs: $(@($impactTypes) -join ', ')","- Simulation high path: $(@($simHighTypes) -join ' -> ')","- Simulation low path: $(@($simLowTypes) -join ' -> ')","- Published version: $($published.version)","- Browser audit: docs/evidence/recovery/screenshots/r92-workflow-advanced-node-publish-impact/workflow-advanced-node-browser-audit.json","- Runtime child evidence: docs/evidence/recovery/r73-workflow-todo-message-error-state-residual-result.json","- User signoff: false (engineering evidence only)",'','## Checks')
foreach ($check in $checks) { $summary += "- [$($check.passed)] $($check.area) / $($check.name): $($check.detail)" }; if ($errorMessage) { $summary += "`nFatal: $errorMessage" }; $summary -join "`n" | Set-Content -LiteralPath $SummaryPath -Encoding UTF8
Write-Output ($result | ConvertTo-Json -Depth 100); if ($status -ne 'PASS' -and -not $NoFailExit) { exit 1 }
