// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.module.base.service;

import com.baomidou.mybatisplus.extension.service.IService;
import com.unique.examine.module.base.entity.ModuleListScene;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

/**
 * Generated base service contract for ModuleListScene.
 */
public interface ModuleListSceneBaseService extends IService<ModuleListScene> {

    Optional<ModuleListScene> findById(Long id);

    List<ModuleListScene> findAll();

    ModuleListScene saveEntity(ModuleListScene entity);

    boolean deleteByIds(Collection<Long> ids);
}
