// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.module.base.service;

import com.baomidou.mybatisplus.extension.service.IService;
import com.unique.examine.module.base.entity.ModuleDictItem;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

/**
 * Generated base service contract for ModuleDictItem.
 */
public interface ModuleDictItemBaseService extends IService<ModuleDictItem> {

    Optional<ModuleDictItem> findById(Long id);

    List<ModuleDictItem> findAll();

    ModuleDictItem saveEntity(ModuleDictItem entity);

    boolean deleteByIds(Collection<Long> ids);
}
