// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.module.base.service;

import com.baomidou.mybatisplus.extension.service.IService;
import com.unique.examine.module.base.entity.ModuleDynamicSequence;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

/**
 * Generated base service contract for ModuleDynamicSequence.
 */
public interface ModuleDynamicSequenceBaseService extends IService<ModuleDynamicSequence> {

    Optional<ModuleDynamicSequence> findById(Long id);

    List<ModuleDynamicSequence> findAll();

    ModuleDynamicSequence saveEntity(ModuleDynamicSequence entity);

    boolean deleteByIds(Collection<Long> ids);
}
