// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.module.base.service;

import com.baomidou.mybatisplus.extension.service.IService;
import com.unique.examine.module.base.entity.ModuleImportExportConfig;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

/**
 * Generated base service contract for ModuleImportExportConfig.
 */
public interface ModuleImportExportConfigBaseService extends IService<ModuleImportExportConfig> {

    Optional<ModuleImportExportConfig> findById(Long id);

    List<ModuleImportExportConfig> findAll();

    ModuleImportExportConfig saveEntity(ModuleImportExportConfig entity);

    boolean deleteByIds(Collection<Long> ids);
}
