// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.module.base.service;

import com.baomidou.mybatisplus.extension.service.IService;
import com.unique.examine.module.base.entity.ModuleDynamicValue;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

/**
 * Generated base service contract for ModuleDynamicValue.
 */
public interface ModuleDynamicValueBaseService extends IService<ModuleDynamicValue> {

    Optional<ModuleDynamicValue> findById(Long id);

    List<ModuleDynamicValue> findAll();

    ModuleDynamicValue saveEntity(ModuleDynamicValue entity);

    boolean deleteByIds(Collection<Long> ids);
}
