// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.module.base.service;

import com.baomidou.mybatisplus.extension.service.IService;
import com.unique.examine.module.base.entity.ModuleDynamicRecord;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

/**
 * Generated base service contract for ModuleDynamicRecord.
 */
public interface ModuleDynamicRecordBaseService extends IService<ModuleDynamicRecord> {

    Optional<ModuleDynamicRecord> findById(Long id);

    List<ModuleDynamicRecord> findAll();

    ModuleDynamicRecord saveEntity(ModuleDynamicRecord entity);

    boolean deleteByIds(Collection<Long> ids);
}
