// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.analytics.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.analytics.base.entity.AnaDashboardPublication;
import com.unique.unexamine.analytics.base.mapper.AnaDashboardPublicationMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class AnaDashboardPublicationBaseService {
    private final AnaDashboardPublicationMapper mapper;

    public AnaDashboardPublicationBaseService(AnaDashboardPublicationMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(AnaDashboardPublication entity) {
        return mapper.insert(entity);
    }

    public AnaDashboardPublication selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<AnaDashboardPublication> selectList(Wrapper<AnaDashboardPublication> query) {
        return mapper.selectList(query);
    }

    public int updateById(AnaDashboardPublication entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
