// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.analytics.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.analytics.base.entity.AnaKpi;
import com.unique.unexamine.analytics.base.mapper.AnaKpiMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class AnaKpiBaseService {
    private final AnaKpiMapper mapper;

    public AnaKpiBaseService(AnaKpiMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(AnaKpi entity) {
        return mapper.insert(entity);
    }

    public AnaKpi selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<AnaKpi> selectList(Wrapper<AnaKpi> query) {
        return mapper.selectList(query);
    }

    public int updateById(AnaKpi entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
