// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.analytics.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.analytics.base.entity.AnaKpiResult;
import com.unique.unexamine.analytics.base.mapper.AnaKpiResultMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class AnaKpiResultBaseService {
    private final AnaKpiResultMapper mapper;

    public AnaKpiResultBaseService(AnaKpiResultMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(AnaKpiResult entity) {
        return mapper.insert(entity);
    }

    public AnaKpiResult selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<AnaKpiResult> selectList(Wrapper<AnaKpiResult> query) {
        return mapper.selectList(query);
    }

    public int updateById(AnaKpiResult entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
