// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.core.base.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.unique.examine.core.base.entity.OpsApiCachePolicy;

import org.apache.ibatis.annotations.Mapper;

/**
 * Generated mapper contract for table `un_ops_api_cache_policy`.
 */
@Mapper
public interface OpsApiCachePolicyMapper extends BaseMapper<OpsApiCachePolicy> {

    String TABLE_NAME = OpsApiCachePolicy.TABLE_NAME;
}
