// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.core.base.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.unique.examine.core.base.entity.OpsDeployment;

import org.apache.ibatis.annotations.Mapper;

/**
 * Generated mapper contract for table `un_ops_deployment`.
 */
@Mapper
public interface OpsDeploymentMapper extends BaseMapper<OpsDeployment> {

    String TABLE_NAME = OpsDeployment.TABLE_NAME;
}
