// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.core.base.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.unique.examine.core.base.entity.OpsRateLimitPolicy;

import org.apache.ibatis.annotations.Mapper;

/**
 * Generated mapper contract for table `un_ops_rate_limit_policy`.
 */
@Mapper
public interface OpsRateLimitPolicyMapper extends BaseMapper<OpsRateLimitPolicy> {

    String TABLE_NAME = OpsRateLimitPolicy.TABLE_NAME;
}
