// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.core.base.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.unique.examine.core.base.entity.SysAsyncTaskFile;

import org.apache.ibatis.annotations.Mapper;

/**
 * Generated mapper contract for table `un_sys_async_task_file`.
 */
@Mapper
public interface SysAsyncTaskFileMapper extends BaseMapper<SysAsyncTaskFile> {

    String TABLE_NAME = SysAsyncTaskFile.TABLE_NAME;
}
