// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.core.base.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.unique.examine.core.base.entity.SysAsyncTaskEvent;

import org.apache.ibatis.annotations.Mapper;

/**
 * Generated mapper contract for table `un_sys_async_task_event`.
 */
@Mapper
public interface SysAsyncTaskEventMapper extends BaseMapper<SysAsyncTaskEvent> {

    String TABLE_NAME = SysAsyncTaskEvent.TABLE_NAME;
}
