// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.core.base.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.unique.examine.core.base.entity.SysIdempotencyKey;

import org.apache.ibatis.annotations.Mapper;

/**
 * Generated mapper contract for table `un_sys_idempotency_key`.
 */
@Mapper
public interface SysIdempotencyKeyMapper extends BaseMapper<SysIdempotencyKey> {

    String TABLE_NAME = SysIdempotencyKey.TABLE_NAME;
}
