// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.core.base.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.unique.examine.core.base.entity.SysSecretRef;

import org.apache.ibatis.annotations.Mapper;

/**
 * Generated mapper contract for table `un_sys_secret_ref`.
 */
@Mapper
public interface SysSecretRefMapper extends BaseMapper<SysSecretRef> {

    String TABLE_NAME = SysSecretRef.TABLE_NAME;
}
