package com.unique.examine.openapi.repository.jdbc;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.unique.examine.openapi.domain.*;
import com.unique.examine.openapi.repository.OpenApiRepository;
import com.unique.examine.openapi.repository.PlatformOpenApiRepository;
import org.springframework.dao.DuplicateKeyException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.transaction.annotation.Transactional;

import java.net.InetAddress;
import java.sql.ResultSet;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.*;

public class JdbcPlatformOpenApiRepository implements PlatformOpenApiRepository {
    private static final TypeReference<Set<String>> SET = new TypeReference<>() {};
    private static final TypeReference<List<String>> LIST = new TypeReference<>() {};
    private final JdbcTemplate jdbc; private final ObjectMapper json;
    public JdbcPlatformOpenApiRepository(JdbcTemplate jdbc,ObjectMapper json){this.jdbc=jdbc;this.json=json;}
    public Optional<ApplicationBundle> findByAppKey(String key){return one(PlatformOpenApiSql.BY_KEY,key);}
    public Optional<ApplicationBundle> find(long id){return one(PlatformOpenApiSql.BY_ID,id);}
    public List<ApplicationBundle> list(int offset,int limit){return List.copyOf(jdbc.query(PlatformOpenApiSql.LIST,this::bundle,limit,offset));}
    public long count(){return Objects.requireNonNullElse(jdbc.queryForObject("SELECT COUNT(*) FROM un_platform_openapi_application",Long.class),0L);}
    public void insertApplication(PlatformOpenApiApplication a){jdbc.update("INSERT INTO un_platform_openapi_application(id,service_account_id,app_key,name,status,scopes_json,ip_allowlist_json,rate_limit_per_minute,current_credential_version,created_at,created_by,updated_at,updated_by,version) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)",a.id(),a.serviceAccountId(),a.appKey(),a.name(),a.status().name(),write(new TreeSet<>(a.scopes())),write(a.ipAllowlist()),a.rateLimitPerMinute(),a.currentCredentialVersion(),ts(a.createdAt()),a.createdBy(),ts(a.updatedAt()),a.updatedBy(),a.version());}
    public void insertCredential(OpenApiCredential c){jdbc.update("INSERT INTO un_platform_openapi_credential(id,application_id,credential_version,secret_ref,status,activated_at,revoked_at,created_at,created_by) VALUES(?,?,?,?,?,?,?,?,?)",c.id(),c.applicationId(),c.credentialVersion(),c.secretRef(),c.status().name(),ts(c.activatedAt()),ts(c.revokedAt()),ts(c.createdAt()),c.createdBy());}
    public boolean updatePolicy(PlatformOpenApiApplication a,long v){return jdbc.update("UPDATE un_platform_openapi_application SET service_account_id=?,name=?,scopes_json=?,ip_allowlist_json=?,rate_limit_per_minute=?,updated_at=?,updated_by=?,version=version+1 WHERE id=? AND version=?",a.serviceAccountId(),a.name(),write(new TreeSet<>(a.scopes())),write(a.ipAllowlist()),a.rateLimitPerMinute(),ts(a.updatedAt()),a.updatedBy(),a.id(),v)==1;}
    public boolean updateStatus(long id,PlatformOpenApiApplication.Status status,long actor,Instant now,long v){return jdbc.update("UPDATE un_platform_openapi_application SET status=?,updated_at=?,updated_by=?,version=version+1 WHERE id=? AND version=?",status.name(),ts(now),actor,id,v)==1;}
    @Transactional public boolean rotateCredential(PlatformOpenApiApplication a,OpenApiCredential old,OpenApiCredential next,long v){if(jdbc.update("UPDATE un_platform_openapi_application SET current_credential_version=?,updated_at=?,updated_by=?,version=version+1 WHERE id=? AND version=?",next.credentialVersion(),ts(a.updatedAt()),a.updatedBy(),a.id(),v)!=1)return false;if(jdbc.update("UPDATE un_platform_openapi_credential SET status='REVOKED',revoked_at=? WHERE application_id=? AND credential_version=? AND status='ACTIVE'",ts(old.revokedAt()),old.applicationId(),old.credentialVersion())!=1)throw new IllegalStateException("Credential changed concurrently");insertCredential(next);return true;}
    public boolean consumeNonce(long id,int version,String nonce,Instant expires,Instant now){jdbc.update("DELETE FROM un_platform_openapi_nonce WHERE application_id=? AND expires_at<?",id,ts(now));try{jdbc.update("INSERT INTO un_platform_openapi_nonce(application_id,credential_version,nonce,expires_at,created_at) VALUES(?,?,?,?,?)",id,version,nonce,ts(expires),ts(now));return true;}catch(DuplicateKeyException e){return false;}}
    public OpenApiRateBucket lockRateBucket(long id,Instant window){jdbc.update("INSERT IGNORE INTO un_platform_openapi_rate_bucket(application_id,window_start,request_count,version) VALUES(?,?,0,0)",id,ts(window));return jdbc.queryForObject("SELECT application_id,window_start,request_count,version FROM un_platform_openapi_rate_bucket WHERE application_id=? AND window_start=? FOR UPDATE",(r,n)->new OpenApiRateBucket(r.getLong(1),r.getTimestamp(2).toInstant(),r.getInt(3),r.getLong(4)),id,ts(window));}
    public boolean incrementRateBucket(long id,Instant window,int count,long v){return jdbc.update("UPDATE un_platform_openapi_rate_bucket SET request_count=request_count+1,version=version+1 WHERE application_id=? AND window_start=? AND request_count=? AND version=?",id,ts(window),count,v)==1;}
    public void insertCallLog(OpenApiCallLog l){jdbc.update("INSERT INTO un_platform_openapi_call_log(id,application_id,app_key_hash,credential_version,route_template,request_method,result_category,http_status,latency_ms,request_id,trace_id,observed_ip,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)",l.id(),l.applicationId(),l.appKeyHash(),l.credentialVersion(),l.routeTemplate(),l.requestMethod(),l.resultCategory().name(),l.httpStatus(),l.latencyMs(),l.requestId(),l.traceId(),ip(l.observedIp()),ts(l.createdAt()));}
    public long countCallLogs(long id,String category,String method){return Objects.requireNonNullElse(jdbc.queryForObject("SELECT COUNT(*) FROM un_platform_openapi_call_log WHERE application_id=? AND (?='ALL' OR result_category=?) AND (?='ALL' OR request_method=?)",Long.class,id,category,category,method,method),0L);}
    public List<OpenApiRepository.ApplicationCallLog> listCallLogs(long id,String category,String method,int offset,int limit){return List.copyOf(jdbc.query("SELECT id,credential_version,route_template,request_method,result_category,http_status,latency_ms,request_id,trace_id,observed_ip,created_at FROM un_platform_openapi_call_log WHERE application_id=? AND (?='ALL' OR result_category=?) AND (?='ALL' OR request_method=?) ORDER BY created_at DESC,id DESC LIMIT ? OFFSET ?",this::log,id,category,category,method,method,limit,offset));}
    private Optional<ApplicationBundle> one(String sql,Object...args){var rows=jdbc.query(sql,this::bundle,args);if(rows.size()>1)throw new IllegalStateException("Duplicate platform app");return rows.stream().findFirst();}
    private ApplicationBundle bundle(ResultSet r,int n)throws java.sql.SQLException{var a=new PlatformOpenApiApplication(r.getLong("id"),r.getLong("service_account_id"),r.getString("app_key"),r.getString("name"),PlatformOpenApiApplication.Status.valueOf(r.getString("status")),readSet(r.getString("scopes_json")),readList(r.getString("ip_allowlist_json")),r.getInt("rate_limit_per_minute"),r.getInt("current_credential_version"),r.getTimestamp("created_at").toInstant(),r.getLong("created_by"),r.getTimestamp("updated_at").toInstant(),r.getLong("updated_by"),r.getLong("version"));var revoked=r.getTimestamp("revoked_at");var c=new OpenApiCredential(r.getLong("credential_id"),a.id(),r.getInt("credential_version"),r.getString("secret_ref"),OpenApiCredential.Status.valueOf(r.getString("credential_status")),r.getTimestamp("activated_at").toInstant(),revoked==null?null:revoked.toInstant(),r.getTimestamp("credential_created_at").toInstant(),r.getLong("credential_created_by"));return new ApplicationBundle(a,c);}
    private OpenApiRepository.ApplicationCallLog log(ResultSet r,int n)throws java.sql.SQLException{return new OpenApiRepository.ApplicationCallLog(r.getLong("id"),r.getObject("credential_version",Integer.class),r.getString("route_template"),r.getString("request_method"),OpenApiCallLog.ResultCategory.valueOf(r.getString("result_category")),r.getInt("http_status"),r.getLong("latency_ms"),r.getString("request_id"),r.getString("trace_id"),text(r.getBytes("observed_ip")),r.getTimestamp("created_at").toInstant());}
    private String write(Object v){try{return json.writeValueAsString(v);}catch(Exception e){throw new IllegalArgumentException("Invalid policy",e);}}
    private Set<String> readSet(String v){try{return json.readValue(v,SET);}catch(Exception e){throw new IllegalStateException(e);}}
    private List<String> readList(String v){try{return json.readValue(v,LIST);}catch(Exception e){throw new IllegalStateException(e);}}
    private static Timestamp ts(Instant v){return v==null?null:Timestamp.from(v);} private static byte[] ip(String v){try{return InetAddress.getByName(v).getAddress();}catch(Exception e){throw new IllegalArgumentException(e);}} private static String text(byte[] v){try{return InetAddress.getByAddress(v).getHostAddress();}catch(Exception e){throw new IllegalStateException(e);}}
}
