package com.unique.examine.openapi.api;

import com.unique.examine.core.api.*;import com.unique.examine.core.context.RequestSession;import com.unique.examine.openapi.domain.PlatformOpenApiApplication;import com.unique.examine.openapi.service.PlatformOpenApiApplicationService;
import jakarta.servlet.http.HttpServletRequest;import org.springframework.http.*;import org.springframework.web.bind.annotation.*;

@RestController @RequestMapping("/api/v1/platform/admin/openapi/applications")
public class PlatformOpenApiApplicationController {
    private final PlatformOpenApiApplicationService service;public PlatformOpenApiApplicationController(PlatformOpenApiApplicationService service){this.service=service;}
    @PostMapping public ResponseEntity<ApiResponse<PlatformOpenApiViews.Application>> create(@RequestBody PlatformOpenApiRequests.Create body,@RequestAttribute(value=RequestSession.REQUEST_ATTRIBUTE,required=false)Object session,HttpServletRequest request){return ResponseEntity.status(HttpStatus.CREATED).body(ok(service.create(PlatformOpenApiAdminSession.require(session),body),request));}
    @GetMapping public ApiResponse<PlatformOpenApiViews.ApplicationPage> list(@RequestParam(defaultValue="1")int page,@RequestParam(defaultValue="20")int size,@RequestAttribute(value=RequestSession.REQUEST_ATTRIBUTE,required=false)Object session,HttpServletRequest request){return ok(service.list(PlatformOpenApiAdminSession.require(session),page,size),request);}
    @GetMapping("/{id}") public ApiResponse<PlatformOpenApiViews.Application> detail(@PathVariable long id,@RequestAttribute(value=RequestSession.REQUEST_ATTRIBUTE,required=false)Object session,HttpServletRequest request){return ok(service.detail(PlatformOpenApiAdminSession.require(session),id),request);}
    @PutMapping("/{id}/policy") public ApiResponse<PlatformOpenApiViews.Application> policy(@PathVariable long id,@RequestBody PlatformOpenApiRequests.Policy body,@RequestAttribute(value=RequestSession.REQUEST_ATTRIBUTE,required=false)Object session,HttpServletRequest request){return ok(service.policy(PlatformOpenApiAdminSession.require(session),id,body),request);}
    @PostMapping("/{id}:rotate-secret-ref") public ApiResponse<PlatformOpenApiViews.Application> rotate(@PathVariable long id,@RequestBody PlatformOpenApiRequests.Rotate body,@RequestAttribute(value=RequestSession.REQUEST_ATTRIBUTE,required=false)Object session,HttpServletRequest request){return ok(service.rotate(PlatformOpenApiAdminSession.require(session),id,body),request);}
    @PostMapping("/{id}:enable") public ApiResponse<PlatformOpenApiViews.Application> enable(@PathVariable long id,@RequestBody PlatformOpenApiRequests.Status body,@RequestAttribute(value=RequestSession.REQUEST_ATTRIBUTE,required=false)Object session,HttpServletRequest request){return ok(service.status(PlatformOpenApiAdminSession.require(session),id,body,PlatformOpenApiApplication.Status.ACTIVE),request);}
    @PostMapping("/{id}:disable") public ApiResponse<PlatformOpenApiViews.Application> disable(@PathVariable long id,@RequestBody PlatformOpenApiRequests.Status body,@RequestAttribute(value=RequestSession.REQUEST_ATTRIBUTE,required=false)Object session,HttpServletRequest request){return ok(service.status(PlatformOpenApiAdminSession.require(session),id,body,PlatformOpenApiApplication.Status.DISABLED),request);}
    @GetMapping("/{id}/call-logs") public ApiResponse<PlatformOpenApiViews.CallLogPage> logs(@PathVariable long id,@RequestParam(defaultValue="ALL")String resultCategory,@RequestParam(defaultValue="ALL")String requestMethod,@RequestParam(defaultValue="1")int page,@RequestParam(defaultValue="20")int size,@RequestAttribute(value=RequestSession.REQUEST_ATTRIBUTE,required=false)Object session,HttpServletRequest request){return ok(service.logs(PlatformOpenApiAdminSession.require(session),id,resultCategory,requestMethod,page,size),request);}
    private static <T> ApiResponse<T> ok(T v,HttpServletRequest r){return ApiResponse.success(v,attr(r,WebRequestAttributes.REQUEST_ID),attr(r,WebRequestAttributes.TRACE_ID));}private static String attr(HttpServletRequest r,String n){var v=r.getAttribute(n);return v==null?"":String.valueOf(v);}
}
