// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.plat.base.service.impl;

import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.unique.examine.plat.base.entity.PlatAccount;
import com.unique.examine.plat.base.mapper.PlatAccountMapper;
import com.unique.examine.plat.base.service.PlatAccountBaseService;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

import org.springframework.stereotype.Service;

/**
 * Generated MyBatis-Plus base service implementation for PlatAccount.
 */
@Service
public class PlatAccountBaseServiceImpl extends ServiceImpl<PlatAccountMapper, PlatAccount> implements PlatAccountBaseService {

    @Override
    public Optional<PlatAccount> findById(Long id) {
        return Optional.ofNullable(getById(id));
    }

    @Override
    public List<PlatAccount> findAll() {
        return list();
    }

    @Override
    public PlatAccount saveEntity(PlatAccount entity) {
        saveOrUpdate(entity);
        return entity;
    }

    @Override
    public boolean deleteByIds(Collection<Long> ids) {
        return ids != null && !ids.isEmpty() && removeBatchByIds(ids);
    }
}
