// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.plat.base.service.impl;

import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.unique.examine.plat.base.entity.PlatRolePermission;
import com.unique.examine.plat.base.mapper.PlatRolePermissionMapper;
import com.unique.examine.plat.base.service.PlatRolePermissionBaseService;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

import org.springframework.stereotype.Service;

/**
 * Generated MyBatis-Plus base service implementation for PlatRolePermission.
 */
@Service
public class PlatRolePermissionBaseServiceImpl extends ServiceImpl<PlatRolePermissionMapper, PlatRolePermission> implements PlatRolePermissionBaseService {

    @Override
    public Optional<PlatRolePermission> findById(Long id) {
        return Optional.ofNullable(getById(id));
    }

    @Override
    public List<PlatRolePermission> findAll() {
        return list();
    }

    @Override
    public PlatRolePermission saveEntity(PlatRolePermission entity) {
        saveOrUpdate(entity);
        return entity;
    }

    @Override
    public boolean deleteByIds(Collection<Long> ids) {
        if (ids == null || ids.isEmpty()) {
            return false;
        }
        return removeBatchByIds(ids);
    }
}
