// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.plat.base.service.impl;

import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.unique.examine.plat.base.entity.PlatSystem;
import com.unique.examine.plat.base.mapper.PlatSystemMapper;
import com.unique.examine.plat.base.service.PlatSystemBaseService;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

import org.springframework.stereotype.Service;

/**
 * Generated MyBatis-Plus base service implementation for PlatSystem.
 */
@Service
public class PlatSystemBaseServiceImpl extends ServiceImpl<PlatSystemMapper, PlatSystem> implements PlatSystemBaseService {

    @Override
    public Optional<PlatSystem> findById(Long id) {
        return Optional.ofNullable(getById(id));
    }

    @Override
    public List<PlatSystem> findAll() {
        return list();
    }

    @Override
    public PlatSystem saveEntity(PlatSystem entity) {
        saveOrUpdate(entity);
        return entity;
    }

    @Override
    public boolean deleteByIds(Collection<Long> ids) {
        return ids != null && !ids.isEmpty() && removeBatchByIds(ids);
    }
}
