// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.plat.base.service.impl;

import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.unique.examine.plat.base.entity.PlatNoMemberAccessRequest;
import com.unique.examine.plat.base.mapper.PlatNoMemberAccessRequestMapper;
import com.unique.examine.plat.base.service.PlatNoMemberAccessRequestBaseService;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

import org.springframework.stereotype.Service;

/**
 * Generated MyBatis-Plus base service implementation for PlatNoMemberAccessRequest.
 */
@Service
public class PlatNoMemberAccessRequestBaseServiceImpl extends ServiceImpl<PlatNoMemberAccessRequestMapper, PlatNoMemberAccessRequest> implements PlatNoMemberAccessRequestBaseService {

    @Override
    public Optional<PlatNoMemberAccessRequest> findById(Long id) {
        return Optional.ofNullable(getById(id));
    }

    @Override
    public List<PlatNoMemberAccessRequest> findAll() {
        return list();
    }

    @Override
    public PlatNoMemberAccessRequest saveEntity(PlatNoMemberAccessRequest entity) {
        saveOrUpdate(entity);
        return entity;
    }

    @Override
    public boolean deleteByIds(Collection<Long> ids) {
        return ids != null && !ids.isEmpty() && removeBatchByIds(ids);
    }
}
