// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.plat.base.service.impl;

import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.unique.examine.plat.base.entity.PlatEffectivePermissionSnapshot;
import com.unique.examine.plat.base.mapper.PlatEffectivePermissionSnapshotMapper;
import com.unique.examine.plat.base.service.PlatEffectivePermissionSnapshotBaseService;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

import org.springframework.stereotype.Service;

/**
 * Generated MyBatis-Plus base service implementation for PlatEffectivePermissionSnapshot.
 */
@Service
public class PlatEffectivePermissionSnapshotBaseServiceImpl extends ServiceImpl<PlatEffectivePermissionSnapshotMapper, PlatEffectivePermissionSnapshot> implements PlatEffectivePermissionSnapshotBaseService {

    @Override
    public Optional<PlatEffectivePermissionSnapshot> findById(Long id) {
        return Optional.ofNullable(getById(id));
    }

    @Override
    public List<PlatEffectivePermissionSnapshot> findAll() {
        return list();
    }

    @Override
    public PlatEffectivePermissionSnapshot saveEntity(PlatEffectivePermissionSnapshot entity) {
        saveOrUpdate(entity);
        return entity;
    }

    @Override
    public boolean deleteByIds(Collection<Long> ids) {
        return ids != null && !ids.isEmpty() && removeBatchByIds(ids);
    }
}
