// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.plat.base.service.impl;

import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.unique.examine.plat.base.entity.PlatDepartment;
import com.unique.examine.plat.base.mapper.PlatDepartmentMapper;
import com.unique.examine.plat.base.service.PlatDepartmentBaseService;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

import org.springframework.stereotype.Service;

/**
 * Generated MyBatis-Plus base service implementation for PlatDepartment.
 */
@Service
public class PlatDepartmentBaseServiceImpl extends ServiceImpl<PlatDepartmentMapper, PlatDepartment> implements PlatDepartmentBaseService {

    @Override
    public Optional<PlatDepartment> findById(Long id) {
        return Optional.ofNullable(getById(id));
    }

    @Override
    public List<PlatDepartment> findAll() {
        return list();
    }

    @Override
    public PlatDepartment saveEntity(PlatDepartment entity) {
        saveOrUpdate(entity);
        return entity;
    }

    @Override
    public boolean deleteByIds(Collection<Long> ids) {
        if (ids == null || ids.isEmpty()) {
            return false;
        }
        return removeBatchByIds(ids);
    }
}
