// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.plat.base.service.impl;

import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.unique.examine.plat.base.entity.PlatMember;
import com.unique.examine.plat.base.mapper.PlatMemberMapper;
import com.unique.examine.plat.base.service.PlatMemberBaseService;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

import org.springframework.stereotype.Service;

/**
 * Generated MyBatis-Plus base service implementation for PlatMember.
 */
@Service
public class PlatMemberBaseServiceImpl extends ServiceImpl<PlatMemberMapper, PlatMember> implements PlatMemberBaseService {

    @Override
    public Optional<PlatMember> findById(Long id) {
        return Optional.ofNullable(getById(id));
    }

    @Override
    public List<PlatMember> findAll() {
        return list();
    }

    @Override
    public PlatMember saveEntity(PlatMember entity) {
        saveOrUpdate(entity);
        return entity;
    }

    @Override
    public boolean deleteByIds(Collection<Long> ids) {
        return ids != null && !ids.isEmpty() && removeBatchByIds(ids);
    }
}
