// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.plat.base.service.impl;

import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.unique.examine.plat.base.entity.PlatTenant;
import com.unique.examine.plat.base.mapper.PlatTenantMapper;
import com.unique.examine.plat.base.service.PlatTenantBaseService;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

import org.springframework.stereotype.Service;

/**
 * Generated MyBatis-Plus base service implementation for PlatTenant.
 */
@Service
public class PlatTenantBaseServiceImpl extends ServiceImpl<PlatTenantMapper, PlatTenant> implements PlatTenantBaseService {

    @Override
    public Optional<PlatTenant> findById(Long id) {
        return Optional.ofNullable(getById(id));
    }

    @Override
    public List<PlatTenant> findAll() {
        return list();
    }

    @Override
    public PlatTenant saveEntity(PlatTenant entity) {
        saveOrUpdate(entity);
        return entity;
    }

    @Override
    public boolean deleteByIds(Collection<Long> ids) {
        if (ids == null || ids.isEmpty()) {
            return false;
        }
        return removeBatchByIds(ids);
    }
}
