// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.aiwork.base.service.impl;

import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.unique.examine.aiwork.base.entity.AgentModelAuthorization;
import com.unique.examine.aiwork.base.mapper.AgentModelAuthorizationMapper;
import com.unique.examine.aiwork.base.service.AgentModelAuthorizationBaseService;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

import org.springframework.stereotype.Service;

/**
 * Generated MyBatis-Plus base service implementation for AgentModelAuthorization.
 */
@Service
public class AgentModelAuthorizationBaseServiceImpl extends ServiceImpl<AgentModelAuthorizationMapper, AgentModelAuthorization> implements AgentModelAuthorizationBaseService {

    @Override
    public Optional<AgentModelAuthorization> findById(Long id) {
        return Optional.ofNullable(getById(id));
    }

    @Override
    public List<AgentModelAuthorization> findAll() {
        return list();
    }

    @Override
    public AgentModelAuthorization saveEntity(AgentModelAuthorization entity) {
        saveOrUpdate(entity);
        return entity;
    }

    @Override
    public boolean deleteByIds(Collection<Long> ids) {
        if (ids == null || ids.isEmpty()) {
            return false;
        }
        return removeBatchByIds(ids);
    }
}
