// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.aiwork.base.service.impl;

import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.unique.examine.aiwork.base.entity.WorkDailyReportSource;
import com.unique.examine.aiwork.base.mapper.WorkDailyReportSourceMapper;
import com.unique.examine.aiwork.base.service.WorkDailyReportSourceBaseService;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

import org.springframework.stereotype.Service;

/**
 * Generated MyBatis-Plus base service implementation for WorkDailyReportSource.
 */
@Service
public class WorkDailyReportSourceBaseServiceImpl extends ServiceImpl<WorkDailyReportSourceMapper, WorkDailyReportSource> implements WorkDailyReportSourceBaseService {

    @Override
    public Optional<WorkDailyReportSource> findById(Long id) {
        return Optional.ofNullable(getById(id));
    }

    @Override
    public List<WorkDailyReportSource> findAll() {
        return list();
    }

    @Override
    public WorkDailyReportSource saveEntity(WorkDailyReportSource entity) {
        saveOrUpdate(entity);
        return entity;
    }

    @Override
    public boolean deleteByIds(Collection<Long> ids) {
        return ids != null && !ids.isEmpty() && removeBatchByIds(ids);
    }
}
