// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.aiwork.base.service.impl;

import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.unique.examine.aiwork.base.entity.WorkDailyReport;
import com.unique.examine.aiwork.base.mapper.WorkDailyReportMapper;
import com.unique.examine.aiwork.base.service.WorkDailyReportBaseService;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

import org.springframework.stereotype.Service;

/**
 * Generated MyBatis-Plus base service implementation for WorkDailyReport.
 */
@Service
public class WorkDailyReportBaseServiceImpl extends ServiceImpl<WorkDailyReportMapper, WorkDailyReport> implements WorkDailyReportBaseService {

    @Override
    public Optional<WorkDailyReport> findById(Long id) {
        return Optional.ofNullable(getById(id));
    }

    @Override
    public List<WorkDailyReport> findAll() {
        return list();
    }

    @Override
    public WorkDailyReport saveEntity(WorkDailyReport entity) {
        saveOrUpdate(entity);
        return entity;
    }

    @Override
    public boolean deleteByIds(Collection<Long> ids) {
        if (ids == null || ids.isEmpty()) {
            return false;
        }
        return removeBatchByIds(ids);
    }
}
