// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.aiwork.base.service.impl;

import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.unique.examine.aiwork.base.entity.WorkProject;
import com.unique.examine.aiwork.base.mapper.WorkProjectMapper;
import com.unique.examine.aiwork.base.service.WorkProjectBaseService;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

import org.springframework.stereotype.Service;

/**
 * Generated MyBatis-Plus base service implementation for WorkProject.
 */
@Service
public class WorkProjectBaseServiceImpl extends ServiceImpl<WorkProjectMapper, WorkProject> implements WorkProjectBaseService {

    @Override
    public Optional<WorkProject> findById(Long id) {
        return Optional.ofNullable(getById(id));
    }

    @Override
    public List<WorkProject> findAll() {
        return list();
    }

    @Override
    public WorkProject saveEntity(WorkProject entity) {
        saveOrUpdate(entity);
        return entity;
    }

    @Override
    public boolean deleteByIds(Collection<Long> ids) {
        return ids != null && !ids.isEmpty() && removeBatchByIds(ids);
    }
}
