// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.aiwork.base.service.impl;

import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.unique.examine.aiwork.base.entity.WorkCalendarItem;
import com.unique.examine.aiwork.base.mapper.WorkCalendarItemMapper;
import com.unique.examine.aiwork.base.service.WorkCalendarItemBaseService;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

import org.springframework.stereotype.Service;

/**
 * Generated MyBatis-Plus base service implementation for WorkCalendarItem.
 */
@Service
public class WorkCalendarItemBaseServiceImpl extends ServiceImpl<WorkCalendarItemMapper, WorkCalendarItem> implements WorkCalendarItemBaseService {

    @Override
    public Optional<WorkCalendarItem> findById(Long id) {
        return Optional.ofNullable(getById(id));
    }

    @Override
    public List<WorkCalendarItem> findAll() {
        return list();
    }

    @Override
    public WorkCalendarItem saveEntity(WorkCalendarItem entity) {
        saveOrUpdate(entity);
        return entity;
    }

    @Override
    public boolean deleteByIds(Collection<Long> ids) {
        return ids != null && !ids.isEmpty() && removeBatchByIds(ids);
    }
}
