// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.module.base.entity;

import java.time.LocalDateTime;
import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;

/**
 * Generated entity for table `un_module_work_config`.
 */
@TableName("un_module_work_config")
public class ModuleWorkConfig {

    public static final String TABLE_NAME = "un_module_work_config";

    /**
     * Column `id`.
     */
    @TableId(value = "id", type = IdType.AUTO)
    private Long id;

    /**
     * Column `system_id`.
     */
    private Long systemId;

    /**
     * Column `tenant_id`.
     */
    private Long tenantId;

    /**
     * Column `config_type`.
     */
    private String configType;

    /**
     * Column `field_list`.
     */
    private String fieldList;

    /**
     * Column `card_fields`.
     */
    private String cardFields;

    /**
     * Column `kanban_column_field_id`.
     */
    private Long kanbanColumnFieldId;

    /**
     * Column `kanban_swimlane_field_id`.
     */
    private Long kanbanSwimlaneFieldId;

    /**
     * Column `kanban_group_field_id`.
     */
    private Long kanbanGroupFieldId;

    /**
     * Column `publish_status`.
     */
    private String publishStatus;

    /**
     * Column `published_version`.
     */
    private String publishedVersion;

    /**
     * Column `updated_at`.
     */
    private LocalDateTime updatedAt;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getSystemId() {
        return systemId;
    }

    public void setSystemId(Long systemId) {
        this.systemId = systemId;
    }

    public Long getTenantId() {
        return tenantId;
    }

    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    public String getConfigType() {
        return configType;
    }

    public void setConfigType(String configType) {
        this.configType = configType;
    }

    public String getFieldList() {
        return fieldList;
    }

    public void setFieldList(String fieldList) {
        this.fieldList = fieldList;
    }

    public String getCardFields() {
        return cardFields;
    }

    public void setCardFields(String cardFields) {
        this.cardFields = cardFields;
    }

    public Long getKanbanColumnFieldId() {
        return kanbanColumnFieldId;
    }

    public void setKanbanColumnFieldId(Long kanbanColumnFieldId) {
        this.kanbanColumnFieldId = kanbanColumnFieldId;
    }

    public Long getKanbanSwimlaneFieldId() {
        return kanbanSwimlaneFieldId;
    }

    public void setKanbanSwimlaneFieldId(Long kanbanSwimlaneFieldId) {
        this.kanbanSwimlaneFieldId = kanbanSwimlaneFieldId;
    }

    public Long getKanbanGroupFieldId() {
        return kanbanGroupFieldId;
    }

    public void setKanbanGroupFieldId(Long kanbanGroupFieldId) {
        this.kanbanGroupFieldId = kanbanGroupFieldId;
    }

    public String getPublishStatus() {
        return publishStatus;
    }

    public void setPublishStatus(String publishStatus) {
        this.publishStatus = publishStatus;
    }

    public String getPublishedVersion() {
        return publishedVersion;
    }

    public void setPublishedVersion(String publishedVersion) {
        this.publishedVersion = publishedVersion;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

}
