// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.module.base.entity;

import java.time.LocalDateTime;
import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;

/**
 * Generated entity for table `un_module_group`.
 */
@TableName("un_module_group")
public class ModuleGroup {

    public static final String TABLE_NAME = "un_module_group";

    /**
     * Column `id`.
     */
    @TableId(value = "id", type = IdType.AUTO)
    private Long id;

    /**
     * Column `system_id`.
     */
    private Long systemId;

    /**
     * Column `tenant_id`.
     */
    private Long tenantId;

    /**
     * Column `group_code`.
     */
    private String groupCode;

    /**
     * Column `group_name`.
     */
    private String groupName;

    /**
     * Column `icon`.
     */
    private String icon;

    /**
     * Column `sort_order`.
     */
    private Integer sortOrder;

    /**
     * Column `visible_role_ids`.
     */
    private String visibleRoleIds;

    /**
     * Column `publish_status`.
     */
    private String publishStatus;

    /**
     * Column `published_version`.
     */
    private String publishedVersion;

    /**
     * Column `created_at`.
     */
    private LocalDateTime createdAt;

    /**
     * Column `updated_at`.
     */
    private LocalDateTime updatedAt;

    /**
     * Column `deleted`.
     */
    private Integer deleted;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getSystemId() {
        return systemId;
    }

    public void setSystemId(Long systemId) {
        this.systemId = systemId;
    }

    public Long getTenantId() {
        return tenantId;
    }

    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    public String getGroupCode() {
        return groupCode;
    }

    public void setGroupCode(String groupCode) {
        this.groupCode = groupCode;
    }

    public String getGroupName() {
        return groupName;
    }

    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    public String getIcon() {
        return icon;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

    public Integer getSortOrder() {
        return sortOrder;
    }

    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    public String getVisibleRoleIds() {
        return visibleRoleIds;
    }

    public void setVisibleRoleIds(String visibleRoleIds) {
        this.visibleRoleIds = visibleRoleIds;
    }

    public String getPublishStatus() {
        return publishStatus;
    }

    public void setPublishStatus(String publishStatus) {
        this.publishStatus = publishStatus;
    }

    public String getPublishedVersion() {
        return publishedVersion;
    }

    public void setPublishedVersion(String publishedVersion) {
        this.publishedVersion = publishedVersion;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    public Integer getDeleted() {
        return deleted;
    }

    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

}
