// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.module.base.entity;

import java.time.LocalDateTime;
import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;

/**
 * Generated entity for table `un_module_publish_version`.
 */
@TableName("un_module_publish_version")
public class ModulePublishVersion {

    public static final String TABLE_NAME = "un_module_publish_version";

    /**
     * Column `id`.
     */
    @TableId(value = "id", type = IdType.AUTO)
    private Long id;

    /**
     * Column `system_id`.
     */
    private Long systemId;

    /**
     * Column `tenant_id`.
     */
    private Long tenantId;

    /**
     * Column `object_type`.
     */
    private String objectType;

    /**
     * Column `object_id`.
     */
    private Long objectId;

    /**
     * Column `version_no`.
     */
    private String versionNo;

    /**
     * Column `publish_status`.
     */
    private String publishStatus;

    /**
     * Column `impact_refs`.
     */
    private String impactRefs;

    /**
     * Column `failure_items`.
     */
    private String failureItems;

    /**
     * Column `trace_id`.
     */
    private String traceId;

    /**
     * Column `created_at`.
     */
    private LocalDateTime createdAt;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getSystemId() {
        return systemId;
    }

    public void setSystemId(Long systemId) {
        this.systemId = systemId;
    }

    public Long getTenantId() {
        return tenantId;
    }

    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    public String getObjectType() {
        return objectType;
    }

    public void setObjectType(String objectType) {
        this.objectType = objectType;
    }

    public Long getObjectId() {
        return objectId;
    }

    public void setObjectId(Long objectId) {
        this.objectId = objectId;
    }

    public String getVersionNo() {
        return versionNo;
    }

    public void setVersionNo(String versionNo) {
        this.versionNo = versionNo;
    }

    public String getPublishStatus() {
        return publishStatus;
    }

    public void setPublishStatus(String publishStatus) {
        this.publishStatus = publishStatus;
    }

    public String getImpactRefs() {
        return impactRefs;
    }

    public void setImpactRefs(String impactRefs) {
        this.impactRefs = impactRefs;
    }

    public String getFailureItems() {
        return failureItems;
    }

    public void setFailureItems(String failureItems) {
        this.failureItems = failureItems;
    }

    public String getTraceId() {
        return traceId;
    }

    public void setTraceId(String traceId) {
        this.traceId = traceId;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

}
