// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.module.base.entity;

import java.time.LocalDateTime;
import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;

/**
 * Generated entity for table `un_module_dynamic_draft`.
 */
@TableName("un_module_dynamic_draft")
public class ModuleDynamicDraft {

    public static final String TABLE_NAME = "un_module_dynamic_draft";

    /**
     * Column `id`.
     */
    @TableId(value = "id", type = IdType.AUTO)
    private Long id;

    /**
     * Column `system_id`.
     */
    private Long systemId;

    /**
     * Column `tenant_id`.
     */
    private Long tenantId;

    /**
     * Column `module_id`.
     */
    private Long moduleId;

    /**
     * Column `draft_no`.
     */
    private String draftNo;

    /**
     * Column `draft_payload`.
     */
    private String draftPayload;

    /**
     * Column `created_by`.
     */
    private Long createdBy;

    /**
     * Column `updated_at`.
     */
    private LocalDateTime updatedAt;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getSystemId() {
        return systemId;
    }

    public void setSystemId(Long systemId) {
        this.systemId = systemId;
    }

    public Long getTenantId() {
        return tenantId;
    }

    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    public Long getModuleId() {
        return moduleId;
    }

    public void setModuleId(Long moduleId) {
        this.moduleId = moduleId;
    }

    public String getDraftNo() {
        return draftNo;
    }

    public void setDraftNo(String draftNo) {
        this.draftNo = draftNo;
    }

    public String getDraftPayload() {
        return draftPayload;
    }

    public void setDraftPayload(String draftPayload) {
        this.draftPayload = draftPayload;
    }

    public Long getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

}
