// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.module.base.entity;

import java.time.LocalDateTime;
import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;

/**
 * Generated entity for table `un_module_dynamic_history`.
 */
@TableName("un_module_dynamic_history")
public class ModuleDynamicHistory {

    public static final String TABLE_NAME = "un_module_dynamic_history";

    /**
     * Column `id`.
     */
    @TableId(value = "id", type = IdType.AUTO)
    private Long id;

    /**
     * Column `system_id`.
     */
    private Long systemId;

    /**
     * Column `tenant_id`.
     */
    private Long tenantId;

    /**
     * Column `module_id`.
     */
    private Long moduleId;

    /**
     * Column `record_id`.
     */
    private Long recordId;

    /**
     * Column `action_code`.
     */
    private String actionCode;

    /**
     * Column `field_diff`.
     */
    private String fieldDiff;

    /**
     * Column `source_type`.
     */
    private String sourceType;

    /**
     * Column `permission_snapshot_id`.
     */
    private String permissionSnapshotId;

    /**
     * Column `desensitize_result`.
     */
    private String desensitizeResult;

    /**
     * Column `trace_id`.
     */
    private String traceId;

    /**
     * Column `audit_log_id`.
     */
    private String auditLogId;

    /**
     * Column `operated_by`.
     */
    private Long operatedBy;

    /**
     * Column `operated_at`.
     */
    private LocalDateTime operatedAt;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getSystemId() {
        return systemId;
    }

    public void setSystemId(Long systemId) {
        this.systemId = systemId;
    }

    public Long getTenantId() {
        return tenantId;
    }

    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    public Long getModuleId() {
        return moduleId;
    }

    public void setModuleId(Long moduleId) {
        this.moduleId = moduleId;
    }

    public Long getRecordId() {
        return recordId;
    }

    public void setRecordId(Long recordId) {
        this.recordId = recordId;
    }

    public String getActionCode() {
        return actionCode;
    }

    public void setActionCode(String actionCode) {
        this.actionCode = actionCode;
    }

    public String getFieldDiff() {
        return fieldDiff;
    }

    public void setFieldDiff(String fieldDiff) {
        this.fieldDiff = fieldDiff;
    }

    public String getSourceType() {
        return sourceType;
    }

    public void setSourceType(String sourceType) {
        this.sourceType = sourceType;
    }

    public String getPermissionSnapshotId() {
        return permissionSnapshotId;
    }

    public void setPermissionSnapshotId(String permissionSnapshotId) {
        this.permissionSnapshotId = permissionSnapshotId;
    }

    public String getDesensitizeResult() {
        return desensitizeResult;
    }

    public void setDesensitizeResult(String desensitizeResult) {
        this.desensitizeResult = desensitizeResult;
    }

    public String getTraceId() {
        return traceId;
    }

    public void setTraceId(String traceId) {
        this.traceId = traceId;
    }

    public String getAuditLogId() {
        return auditLogId;
    }

    public void setAuditLogId(String auditLogId) {
        this.auditLogId = auditLogId;
    }

    public Long getOperatedBy() {
        return operatedBy;
    }

    public void setOperatedBy(Long operatedBy) {
        this.operatedBy = operatedBy;
    }

    public LocalDateTime getOperatedAt() {
        return operatedAt;
    }

    public void setOperatedAt(LocalDateTime operatedAt) {
        this.operatedAt = operatedAt;
    }

}
