// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.module.base.entity;

import java.time.LocalDateTime;
import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;

/**
 * Generated entity for table `un_module_dynamic_sequence`.
 */
@TableName("un_module_dynamic_sequence")
public class ModuleDynamicSequence {

    public static final String TABLE_NAME = "un_module_dynamic_sequence";

    /**
     * Column `id`.
     */
    @TableId(value = "id", type = IdType.AUTO)
    private Long id;

    /**
     * Column `system_id`.
     */
    private Long systemId;

    /**
     * Column `tenant_id`.
     */
    private Long tenantId;

    /**
     * Column `module_id`.
     */
    private Long moduleId;

    /**
     * Column `sequence_type`.
     */
    private String sequenceType;

    /**
     * Column `prefix_rule`.
     */
    private String prefixRule;

    /**
     * Column `current_no`.
     */
    private Long currentNo;

    /**
     * Column `updated_at`.
     */
    private LocalDateTime updatedAt;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getSystemId() {
        return systemId;
    }

    public void setSystemId(Long systemId) {
        this.systemId = systemId;
    }

    public Long getTenantId() {
        return tenantId;
    }

    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    public Long getModuleId() {
        return moduleId;
    }

    public void setModuleId(Long moduleId) {
        this.moduleId = moduleId;
    }

    public String getSequenceType() {
        return sequenceType;
    }

    public void setSequenceType(String sequenceType) {
        this.sequenceType = sequenceType;
    }

    public String getPrefixRule() {
        return prefixRule;
    }

    public void setPrefixRule(String prefixRule) {
        this.prefixRule = prefixRule;
    }

    public Long getCurrentNo() {
        return currentNo;
    }

    public void setCurrentNo(Long currentNo) {
        this.currentNo = currentNo;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

}
