// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.module.base.entity;

import java.time.LocalDateTime;
import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;

/**
 * Generated entity for table `un_module_action_config`.
 */
@TableName("un_module_action_config")
public class ModuleActionConfig {

    public static final String TABLE_NAME = "un_module_action_config";

    /**
     * Column `id`.
     */
    @TableId(value = "id", type = IdType.AUTO)
    private Long id;

    /**
     * Column `module_id`.
     */
    private Long moduleId;

    /**
     * Column `action_code`.
     */
    private String actionCode;

    /**
     * Column `action_name`.
     */
    private String actionName;

    /**
     * Column `action_type`.
     */
    private String actionType;

    /**
     * Column `selection_rule`.
     */
    private String selectionRule;

    /**
     * Column `permission_code`.
     */
    private String permissionCode;

    /**
     * Column `result_contract`.
     */
    private String resultContract;

    /**
     * Column `status`.
     */
    private Integer status;

    /**
     * Column `created_at`.
     */
    private LocalDateTime createdAt;

    /**
     * Column `updated_at`.
     */
    private LocalDateTime updatedAt;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getModuleId() {
        return moduleId;
    }

    public void setModuleId(Long moduleId) {
        this.moduleId = moduleId;
    }

    public String getActionCode() {
        return actionCode;
    }

    public void setActionCode(String actionCode) {
        this.actionCode = actionCode;
    }

    public String getActionName() {
        return actionName;
    }

    public void setActionName(String actionName) {
        this.actionName = actionName;
    }

    public String getActionType() {
        return actionType;
    }

    public void setActionType(String actionType) {
        this.actionType = actionType;
    }

    public String getSelectionRule() {
        return selectionRule;
    }

    public void setSelectionRule(String selectionRule) {
        this.selectionRule = selectionRule;
    }

    public String getPermissionCode() {
        return permissionCode;
    }

    public void setPermissionCode(String permissionCode) {
        this.permissionCode = permissionCode;
    }

    public String getResultContract() {
        return resultContract;
    }

    public void setResultContract(String resultContract) {
        this.resultContract = resultContract;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

}
