// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.module.base.entity;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;

/**
 * Generated entity for table `un_module_dynamic_value`.
 */
@TableName("un_module_dynamic_value")
public class ModuleDynamicValue {

    public static final String TABLE_NAME = "un_module_dynamic_value";

    /**
     * Column `id`.
     */
    @TableId(value = "id", type = IdType.AUTO)
    private Long id;

    /**
     * Column `record_id`.
     */
    private Long recordId;

    /**
     * Column `module_id`.
     */
    private Long moduleId;

    /**
     * Column `field_id`.
     */
    private Long fieldId;

    /**
     * Column `child_row_id`.
     */
    private Long childRowId;

    /**
     * Column `value_text`.
     */
    private String valueText;

    /**
     * Column `value_number`.
     */
    private BigDecimal valueNumber;

    /**
     * Column `value_datetime`.
     */
    private LocalDateTime valueDatetime;

    /**
     * Column `value_json`.
     */
    private String valueJson;

    /**
     * Column `created_at`.
     */
    private LocalDateTime createdAt;

    /**
     * Column `updated_at`.
     */
    private LocalDateTime updatedAt;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getRecordId() {
        return recordId;
    }

    public void setRecordId(Long recordId) {
        this.recordId = recordId;
    }

    public Long getModuleId() {
        return moduleId;
    }

    public void setModuleId(Long moduleId) {
        this.moduleId = moduleId;
    }

    public Long getFieldId() {
        return fieldId;
    }

    public void setFieldId(Long fieldId) {
        this.fieldId = fieldId;
    }

    public Long getChildRowId() {
        return childRowId;
    }

    public void setChildRowId(Long childRowId) {
        this.childRowId = childRowId;
    }

    public String getValueText() {
        return valueText;
    }

    public void setValueText(String valueText) {
        this.valueText = valueText;
    }

    public BigDecimal getValueNumber() {
        return valueNumber;
    }

    public void setValueNumber(BigDecimal valueNumber) {
        this.valueNumber = valueNumber;
    }

    public LocalDateTime getValueDatetime() {
        return valueDatetime;
    }

    public void setValueDatetime(LocalDateTime valueDatetime) {
        this.valueDatetime = valueDatetime;
    }

    public String getValueJson() {
        return valueJson;
    }

    public void setValueJson(String valueJson) {
        this.valueJson = valueJson;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

}
