// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.upload.base.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.unique.examine.upload.base.entity.UploadFile;

import org.apache.ibatis.annotations.Mapper;

/**
 * Generated mapper contract for table `un_upload_file`.
 */
@Mapper
public interface UploadFileMapper extends BaseMapper<UploadFile> {

    String TABLE_NAME = UploadFile.TABLE_NAME;
}
