// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.upload.base.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.unique.examine.upload.base.entity.UploadFileAccessLog;

import org.apache.ibatis.annotations.Mapper;

/**
 * Generated mapper contract for table `un_upload_file_access_log`.
 */
@Mapper
public interface UploadFileAccessLogMapper extends BaseMapper<UploadFileAccessLog> {

    String TABLE_NAME = UploadFileAccessLog.TABLE_NAME;
}
