// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.module.base.service.impl;

import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.unique.examine.module.base.entity.ModuleDictType;
import com.unique.examine.module.base.mapper.ModuleDictTypeMapper;
import com.unique.examine.module.base.service.ModuleDictTypeBaseService;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

import org.springframework.stereotype.Service;

/**
 * Generated MyBatis-Plus base service implementation for ModuleDictType.
 */
@Service
public class ModuleDictTypeBaseServiceImpl extends ServiceImpl<ModuleDictTypeMapper, ModuleDictType> implements ModuleDictTypeBaseService {

    @Override
    public Optional<ModuleDictType> findById(Long id) {
        return Optional.ofNullable(getById(id));
    }

    @Override
    public List<ModuleDictType> findAll() {
        return list();
    }

    @Override
    public ModuleDictType saveEntity(ModuleDictType entity) {
        saveOrUpdate(entity);
        return entity;
    }

    @Override
    public boolean deleteByIds(Collection<Long> ids) {
        return ids != null && !ids.isEmpty() && removeBatchByIds(ids);
    }
}
