// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.module.base.service.impl;

import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.unique.examine.module.base.entity.ModuleActionConfig;
import com.unique.examine.module.base.mapper.ModuleActionConfigMapper;
import com.unique.examine.module.base.service.ModuleActionConfigBaseService;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

import org.springframework.stereotype.Service;

/**
 * Generated MyBatis-Plus base service implementation for ModuleActionConfig.
 */
@Service
public class ModuleActionConfigBaseServiceImpl extends ServiceImpl<ModuleActionConfigMapper, ModuleActionConfig> implements ModuleActionConfigBaseService {

    @Override
    public Optional<ModuleActionConfig> findById(Long id) {
        return Optional.ofNullable(getById(id));
    }

    @Override
    public List<ModuleActionConfig> findAll() {
        return list();
    }

    @Override
    public ModuleActionConfig saveEntity(ModuleActionConfig entity) {
        saveOrUpdate(entity);
        return entity;
    }

    @Override
    public boolean deleteByIds(Collection<Long> ids) {
        if (ids == null || ids.isEmpty()) {
            return false;
        }
        return removeBatchByIds(ids);
    }
}
