// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.module.base.service.impl;

import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.unique.examine.module.base.entity.ModulePrintTemplate;
import com.unique.examine.module.base.mapper.ModulePrintTemplateMapper;
import com.unique.examine.module.base.service.ModulePrintTemplateBaseService;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

import org.springframework.stereotype.Service;

/**
 * Generated MyBatis-Plus base service implementation for ModulePrintTemplate.
 */
@Service
public class ModulePrintTemplateBaseServiceImpl extends ServiceImpl<ModulePrintTemplateMapper, ModulePrintTemplate> implements ModulePrintTemplateBaseService {

    @Override
    public Optional<ModulePrintTemplate> findById(Long id) {
        return Optional.ofNullable(getById(id));
    }

    @Override
    public List<ModulePrintTemplate> findAll() {
        return list();
    }

    @Override
    public ModulePrintTemplate saveEntity(ModulePrintTemplate entity) {
        saveOrUpdate(entity);
        return entity;
    }

    @Override
    public boolean deleteByIds(Collection<Long> ids) {
        return ids != null && !ids.isEmpty() && removeBatchByIds(ids);
    }
}
