// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.module.base.service.impl;

import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.unique.examine.module.base.entity.ModuleDynamicValue;
import com.unique.examine.module.base.mapper.ModuleDynamicValueMapper;
import com.unique.examine.module.base.service.ModuleDynamicValueBaseService;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

import org.springframework.stereotype.Service;

/**
 * Generated MyBatis-Plus base service implementation for ModuleDynamicValue.
 */
@Service
public class ModuleDynamicValueBaseServiceImpl extends ServiceImpl<ModuleDynamicValueMapper, ModuleDynamicValue> implements ModuleDynamicValueBaseService {

    @Override
    public Optional<ModuleDynamicValue> findById(Long id) {
        return Optional.ofNullable(getById(id));
    }

    @Override
    public List<ModuleDynamicValue> findAll() {
        return list();
    }

    @Override
    public ModuleDynamicValue saveEntity(ModuleDynamicValue entity) {
        saveOrUpdate(entity);
        return entity;
    }

    @Override
    public boolean deleteByIds(Collection<Long> ids) {
        if (ids == null || ids.isEmpty()) {
            return false;
        }
        return removeBatchByIds(ids);
    }
}
