// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.module.base.service.impl;

import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.unique.examine.module.base.entity.ModuleDynamicSequence;
import com.unique.examine.module.base.mapper.ModuleDynamicSequenceMapper;
import com.unique.examine.module.base.service.ModuleDynamicSequenceBaseService;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

import org.springframework.stereotype.Service;

/**
 * Generated MyBatis-Plus base service implementation for ModuleDynamicSequence.
 */
@Service
public class ModuleDynamicSequenceBaseServiceImpl extends ServiceImpl<ModuleDynamicSequenceMapper, ModuleDynamicSequence> implements ModuleDynamicSequenceBaseService {

    @Override
    public Optional<ModuleDynamicSequence> findById(Long id) {
        return Optional.ofNullable(getById(id));
    }

    @Override
    public List<ModuleDynamicSequence> findAll() {
        return list();
    }

    @Override
    public ModuleDynamicSequence saveEntity(ModuleDynamicSequence entity) {
        saveOrUpdate(entity);
        return entity;
    }

    @Override
    public boolean deleteByIds(Collection<Long> ids) {
        if (ids == null || ids.isEmpty()) {
            return false;
        }
        return removeBatchByIds(ids);
    }
}
