// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.module.base.service.impl;

import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.unique.examine.module.base.entity.ModuleGroup;
import com.unique.examine.module.base.mapper.ModuleGroupMapper;
import com.unique.examine.module.base.service.ModuleGroupBaseService;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

import org.springframework.stereotype.Service;

/**
 * Generated MyBatis-Plus base service implementation for ModuleGroup.
 */
@Service
public class ModuleGroupBaseServiceImpl extends ServiceImpl<ModuleGroupMapper, ModuleGroup> implements ModuleGroupBaseService {

    @Override
    public Optional<ModuleGroup> findById(Long id) {
        return Optional.ofNullable(getById(id));
    }

    @Override
    public List<ModuleGroup> findAll() {
        return list();
    }

    @Override
    public ModuleGroup saveEntity(ModuleGroup entity) {
        saveOrUpdate(entity);
        return entity;
    }

    @Override
    public boolean deleteByIds(Collection<Long> ids) {
        return ids != null && !ids.isEmpty() && removeBatchByIds(ids);
    }
}
