// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.module.base.service.impl;

import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.unique.examine.module.base.entity.ModuleDynamicAttachment;
import com.unique.examine.module.base.mapper.ModuleDynamicAttachmentMapper;
import com.unique.examine.module.base.service.ModuleDynamicAttachmentBaseService;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

import org.springframework.stereotype.Service;

/**
 * Generated MyBatis-Plus base service implementation for ModuleDynamicAttachment.
 */
@Service
public class ModuleDynamicAttachmentBaseServiceImpl extends ServiceImpl<ModuleDynamicAttachmentMapper, ModuleDynamicAttachment> implements ModuleDynamicAttachmentBaseService {

    @Override
    public Optional<ModuleDynamicAttachment> findById(Long id) {
        return Optional.ofNullable(getById(id));
    }

    @Override
    public List<ModuleDynamicAttachment> findAll() {
        return list();
    }

    @Override
    public ModuleDynamicAttachment saveEntity(ModuleDynamicAttachment entity) {
        saveOrUpdate(entity);
        return entity;
    }

    @Override
    public boolean deleteByIds(Collection<Long> ids) {
        if (ids == null || ids.isEmpty()) {
            return false;
        }
        return removeBatchByIds(ids);
    }
}
