// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.module.base.service.impl;

import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.unique.examine.module.base.entity.ModuleListScene;
import com.unique.examine.module.base.mapper.ModuleListSceneMapper;
import com.unique.examine.module.base.service.ModuleListSceneBaseService;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

import org.springframework.stereotype.Service;

/**
 * Generated MyBatis-Plus base service implementation for ModuleListScene.
 */
@Service
public class ModuleListSceneBaseServiceImpl extends ServiceImpl<ModuleListSceneMapper, ModuleListScene> implements ModuleListSceneBaseService {

    @Override
    public Optional<ModuleListScene> findById(Long id) {
        return Optional.ofNullable(getById(id));
    }

    @Override
    public List<ModuleListScene> findAll() {
        return list();
    }

    @Override
    public ModuleListScene saveEntity(ModuleListScene entity) {
        saveOrUpdate(entity);
        return entity;
    }

    @Override
    public boolean deleteByIds(Collection<Long> ids) {
        return ids != null && !ids.isEmpty() && removeBatchByIds(ids);
    }
}
