// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.module.base.service.impl;

import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.unique.examine.module.base.entity.ModuleDynamicIndex;
import com.unique.examine.module.base.mapper.ModuleDynamicIndexMapper;
import com.unique.examine.module.base.service.ModuleDynamicIndexBaseService;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

import org.springframework.stereotype.Service;

/**
 * Generated MyBatis-Plus base service implementation for ModuleDynamicIndex.
 */
@Service
public class ModuleDynamicIndexBaseServiceImpl extends ServiceImpl<ModuleDynamicIndexMapper, ModuleDynamicIndex> implements ModuleDynamicIndexBaseService {

    @Override
    public Optional<ModuleDynamicIndex> findById(Long id) {
        return Optional.ofNullable(getById(id));
    }

    @Override
    public List<ModuleDynamicIndex> findAll() {
        return list();
    }

    @Override
    public ModuleDynamicIndex saveEntity(ModuleDynamicIndex entity) {
        saveOrUpdate(entity);
        return entity;
    }

    @Override
    public boolean deleteByIds(Collection<Long> ids) {
        return ids != null && !ids.isEmpty() && removeBatchByIds(ids);
    }
}
