// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.module.base.service.impl;

import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.unique.examine.module.base.entity.ModuleDynamicRelation;
import com.unique.examine.module.base.mapper.ModuleDynamicRelationMapper;
import com.unique.examine.module.base.service.ModuleDynamicRelationBaseService;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

import org.springframework.stereotype.Service;

/**
 * Generated MyBatis-Plus base service implementation for ModuleDynamicRelation.
 */
@Service
public class ModuleDynamicRelationBaseServiceImpl extends ServiceImpl<ModuleDynamicRelationMapper, ModuleDynamicRelation> implements ModuleDynamicRelationBaseService {

    @Override
    public Optional<ModuleDynamicRelation> findById(Long id) {
        return Optional.ofNullable(getById(id));
    }

    @Override
    public List<ModuleDynamicRelation> findAll() {
        return list();
    }

    @Override
    public ModuleDynamicRelation saveEntity(ModuleDynamicRelation entity) {
        saveOrUpdate(entity);
        return entity;
    }

    @Override
    public boolean deleteByIds(Collection<Long> ids) {
        return ids != null && !ids.isEmpty() && removeBatchByIds(ids);
    }
}
