// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.module.base.service.impl;

import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.unique.examine.module.base.entity.ModuleDynamicHistory;
import com.unique.examine.module.base.mapper.ModuleDynamicHistoryMapper;
import com.unique.examine.module.base.service.ModuleDynamicHistoryBaseService;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

import org.springframework.stereotype.Service;

/**
 * Generated MyBatis-Plus base service implementation for ModuleDynamicHistory.
 */
@Service
public class ModuleDynamicHistoryBaseServiceImpl extends ServiceImpl<ModuleDynamicHistoryMapper, ModuleDynamicHistory> implements ModuleDynamicHistoryBaseService {

    @Override
    public Optional<ModuleDynamicHistory> findById(Long id) {
        return Optional.ofNullable(getById(id));
    }

    @Override
    public List<ModuleDynamicHistory> findAll() {
        return list();
    }

    @Override
    public ModuleDynamicHistory saveEntity(ModuleDynamicHistory entity) {
        saveOrUpdate(entity);
        return entity;
    }

    @Override
    public boolean deleteByIds(Collection<Long> ids) {
        if (ids == null || ids.isEmpty()) {
            return false;
        }
        return removeBatchByIds(ids);
    }
}
