// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.module.base.service.impl;

import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.unique.examine.module.base.entity.ModulePublishVersion;
import com.unique.examine.module.base.mapper.ModulePublishVersionMapper;
import com.unique.examine.module.base.service.ModulePublishVersionBaseService;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

import org.springframework.stereotype.Service;

/**
 * Generated MyBatis-Plus base service implementation for ModulePublishVersion.
 */
@Service
public class ModulePublishVersionBaseServiceImpl extends ServiceImpl<ModulePublishVersionMapper, ModulePublishVersion> implements ModulePublishVersionBaseService {

    @Override
    public Optional<ModulePublishVersion> findById(Long id) {
        return Optional.ofNullable(getById(id));
    }

    @Override
    public List<ModulePublishVersion> findAll() {
        return list();
    }

    @Override
    public ModulePublishVersion saveEntity(ModulePublishVersion entity) {
        saveOrUpdate(entity);
        return entity;
    }

    @Override
    public boolean deleteByIds(Collection<Long> ids) {
        if (ids == null || ids.isEmpty()) {
            return false;
        }
        return removeBatchByIds(ids);
    }
}
