// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.upload.base.entity;

import java.time.LocalDateTime;
import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;

/**
 * Generated entity for table `un_upload_storage_policy`.
 */
@TableName("un_upload_storage_policy")
public class UploadStoragePolicy {

    public static final String TABLE_NAME = "un_upload_storage_policy";

    /**
     * Column `id`.
     */
    @TableId(value = "id", type = IdType.AUTO)
    private Long id;

    /**
     * Column `scope`.
     */
    private String scope;

    /**
     * Column `system_id`.
     */
    private Long systemId;

    /**
     * Column `tenant_id`.
     */
    private Long tenantId;

    /**
     * Column `policy_code`.
     */
    private String policyCode;

    /**
     * Column `storage_provider`.
     */
    private String storageProvider;

    /**
     * Column `storage_bucket`.
     */
    private String storageBucket;

    /**
     * Column `secret_ref_id`.
     */
    private String secretRefId;

    /**
     * Column `max_file_size`.
     */
    private Long maxFileSize;

    /**
     * Column `allowed_extensions`.
     */
    private String allowedExtensions;

    /**
     * Column `preview_enabled`.
     */
    private Integer previewEnabled;

    /**
     * Column `quota_limit_bytes`.
     */
    private Long quotaLimitBytes;

    /**
     * Column `status`.
     */
    private Integer status;

    /**
     * Column `updated_at`.
     */
    private LocalDateTime updatedAt;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getScope() {
        return scope;
    }

    public void setScope(String scope) {
        this.scope = scope;
    }

    public Long getSystemId() {
        return systemId;
    }

    public void setSystemId(Long systemId) {
        this.systemId = systemId;
    }

    public Long getTenantId() {
        return tenantId;
    }

    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    public String getPolicyCode() {
        return policyCode;
    }

    public void setPolicyCode(String policyCode) {
        this.policyCode = policyCode;
    }

    public String getStorageProvider() {
        return storageProvider;
    }

    public void setStorageProvider(String storageProvider) {
        this.storageProvider = storageProvider;
    }

    public String getStorageBucket() {
        return storageBucket;
    }

    public void setStorageBucket(String storageBucket) {
        this.storageBucket = storageBucket;
    }

    public String getSecretRefId() {
        return secretRefId;
    }

    public void setSecretRefId(String secretRefId) {
        this.secretRefId = secretRefId;
    }

    public Long getMaxFileSize() {
        return maxFileSize;
    }

    public void setMaxFileSize(Long maxFileSize) {
        this.maxFileSize = maxFileSize;
    }

    public String getAllowedExtensions() {
        return allowedExtensions;
    }

    public void setAllowedExtensions(String allowedExtensions) {
        this.allowedExtensions = allowedExtensions;
    }

    public Integer getPreviewEnabled() {
        return previewEnabled;
    }

    public void setPreviewEnabled(Integer previewEnabled) {
        this.previewEnabled = previewEnabled;
    }

    public Long getQuotaLimitBytes() {
        return quotaLimitBytes;
    }

    public void setQuotaLimitBytes(Long quotaLimitBytes) {
        this.quotaLimitBytes = quotaLimitBytes;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

}
