// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.upload.base.entity;

import java.time.LocalDateTime;
import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;

/**
 * Generated entity for table `un_upload_file_recycle`.
 */
@TableName("un_upload_file_recycle")
public class UploadFileRecycle {

    public static final String TABLE_NAME = "un_upload_file_recycle";

    /**
     * Column `id`.
     */
    @TableId(value = "id", type = IdType.AUTO)
    private Long id;

    /**
     * Column `file_id`.
     */
    private String fileId;

    /**
     * Column `recycle_reason`.
     */
    private String recycleReason;

    /**
     * Column `recycled_by`.
     */
    private Long recycledBy;

    /**
     * Column `recycled_at`.
     */
    private LocalDateTime recycledAt;

    /**
     * Column `restore_deadline`.
     */
    private LocalDateTime restoreDeadline;

    /**
     * Column `restore_status`.
     */
    private String restoreStatus;

    /**
     * Column `restored_by`.
     */
    private Long restoredBy;

    /**
     * Column `restored_at`.
     */
    private LocalDateTime restoredAt;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFileId() {
        return fileId;
    }

    public void setFileId(String fileId) {
        this.fileId = fileId;
    }

    public String getRecycleReason() {
        return recycleReason;
    }

    public void setRecycleReason(String recycleReason) {
        this.recycleReason = recycleReason;
    }

    public Long getRecycledBy() {
        return recycledBy;
    }

    public void setRecycledBy(Long recycledBy) {
        this.recycledBy = recycledBy;
    }

    public LocalDateTime getRecycledAt() {
        return recycledAt;
    }

    public void setRecycledAt(LocalDateTime recycledAt) {
        this.recycledAt = recycledAt;
    }

    public LocalDateTime getRestoreDeadline() {
        return restoreDeadline;
    }

    public void setRestoreDeadline(LocalDateTime restoreDeadline) {
        this.restoreDeadline = restoreDeadline;
    }

    public String getRestoreStatus() {
        return restoreStatus;
    }

    public void setRestoreStatus(String restoreStatus) {
        this.restoreStatus = restoreStatus;
    }

    public Long getRestoredBy() {
        return restoredBy;
    }

    public void setRestoredBy(Long restoredBy) {
        this.restoredBy = restoredBy;
    }

    public LocalDateTime getRestoredAt() {
        return restoredAt;
    }

    public void setRestoredAt(LocalDateTime restoredAt) {
        this.restoredAt = restoredAt;
    }

}
