// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.upload.base.entity;

import java.time.LocalDateTime;
import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;

/**
 * Generated entity for table `un_upload_file`.
 */
@TableName("un_upload_file")
public class UploadFile {

    public static final String TABLE_NAME = "un_upload_file";

    /**
     * Column `id`.
     */
    @TableId(value = "id", type = IdType.AUTO)
    private Long id;

    /**
     * Column `file_id`.
     */
    private String fileId;

    /**
     * Column `scope`.
     */
    private String scope;

    /**
     * Column `system_id`.
     */
    private Long systemId;

    /**
     * Column `tenant_id`.
     */
    private Long tenantId;

    /**
     * Column `file_name`.
     */
    private String fileName;

    /**
     * Column `extension`.
     */
    private String extension;

    /**
     * Column `mime_type`.
     */
    private String mimeType;

    /**
     * Column `size_bytes`.
     */
    private Long sizeBytes;

    /**
     * Column `sha256`.
     */
    private String sha256;

    /**
     * Column `storage_provider`.
     */
    private String storageProvider;

    /**
     * Column `storage_bucket`.
     */
    private String storageBucket;

    /**
     * Column `object_key`.
     */
    private String objectKey;

    /**
     * Column `storage_status`.
     */
    private String storageStatus;

    /**
     * Column `preview_status`.
     */
    private String previewStatus;

    /**
     * Column `owner_account_id`.
     */
    private Long ownerAccountId;

    /**
     * Column `owner_member_id`.
     */
    private Long ownerMemberId;

    /**
     * Column `permission_snapshot_id`.
     */
    private String permissionSnapshotId;

    /**
     * Column `created_at`.
     */
    private LocalDateTime createdAt;

    /**
     * Column `updated_at`.
     */
    private LocalDateTime updatedAt;

    /**
     * Column `deleted`.
     */
    private Integer deleted;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFileId() {
        return fileId;
    }

    public void setFileId(String fileId) {
        this.fileId = fileId;
    }

    public String getScope() {
        return scope;
    }

    public void setScope(String scope) {
        this.scope = scope;
    }

    public Long getSystemId() {
        return systemId;
    }

    public void setSystemId(Long systemId) {
        this.systemId = systemId;
    }

    public Long getTenantId() {
        return tenantId;
    }

    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public String getExtension() {
        return extension;
    }

    public void setExtension(String extension) {
        this.extension = extension;
    }

    public String getMimeType() {
        return mimeType;
    }

    public void setMimeType(String mimeType) {
        this.mimeType = mimeType;
    }

    public Long getSizeBytes() {
        return sizeBytes;
    }

    public void setSizeBytes(Long sizeBytes) {
        this.sizeBytes = sizeBytes;
    }

    public String getSha256() {
        return sha256;
    }

    public void setSha256(String sha256) {
        this.sha256 = sha256;
    }

    public String getStorageProvider() {
        return storageProvider;
    }

    public void setStorageProvider(String storageProvider) {
        this.storageProvider = storageProvider;
    }

    public String getStorageBucket() {
        return storageBucket;
    }

    public void setStorageBucket(String storageBucket) {
        this.storageBucket = storageBucket;
    }

    public String getObjectKey() {
        return objectKey;
    }

    public void setObjectKey(String objectKey) {
        this.objectKey = objectKey;
    }

    public String getStorageStatus() {
        return storageStatus;
    }

    public void setStorageStatus(String storageStatus) {
        this.storageStatus = storageStatus;
    }

    public String getPreviewStatus() {
        return previewStatus;
    }

    public void setPreviewStatus(String previewStatus) {
        this.previewStatus = previewStatus;
    }

    public Long getOwnerAccountId() {
        return ownerAccountId;
    }

    public void setOwnerAccountId(Long ownerAccountId) {
        this.ownerAccountId = ownerAccountId;
    }

    public Long getOwnerMemberId() {
        return ownerMemberId;
    }

    public void setOwnerMemberId(Long ownerMemberId) {
        this.ownerMemberId = ownerMemberId;
    }

    public String getPermissionSnapshotId() {
        return permissionSnapshotId;
    }

    public void setPermissionSnapshotId(String permissionSnapshotId) {
        this.permissionSnapshotId = permissionSnapshotId;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    public Integer getDeleted() {
        return deleted;
    }

    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

}
