package com.unique.examine.plat.platform;

import com.fasterxml.jackson.databind.*;import com.unique.examine.core.ai.PlatformOperationsQueryFacade;import com.unique.examine.core.error.BusinessException;import com.unique.examine.core.id.IdService;import com.unique.examine.plat.api.AuthenticatedSession;
import org.springframework.beans.factory.ObjectProvider;import org.springframework.http.HttpStatus;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.sql.*;import java.time.*;import java.util.*;
import static com.unique.examine.plat.platform.PlatformFlowDashboardViews.*;

@Service
public class PlatformFlowDashboardService {
    private static final Set<String> STATS=Set.of("AUTHORIZED_SYSTEMS","OPEN_TASKS","UNREAD_MESSAGES","FLOW_RUNS");
    private static final Map<String,QuickEntry> ENTRIES=Map.of(
      "FLOW",new QuickEntry("平台 Flow","/platform/flows","platform.flow.read"),
      "WORK",new QuickEntry("工作","/platform/work","platform.work.read"),
      "TODO",new QuickEntry("待办","/platform/todos","platform.task.read"),
      "MESSAGE",new QuickEntry("消息","/platform/messages","platform.message.read"),
      "AGENT",new QuickEntry("AI Agent","/platform/agent","platform.ai.agent.use"));
    private final JdbcTemplate jdbc;private final ObjectMapper json;private final IdService ids;private final ObjectProvider<PlatformOperationsQueryFacade.ServiceHealthProvider> health;
    public PlatformFlowDashboardService(JdbcTemplate jdbc,ObjectMapper json,IdService ids,ObjectProvider<PlatformOperationsQueryFacade.ServiceHealthProvider> health){this.jdbc=jdbc;this.json=json;this.ids=ids;this.health=health;}

    @Transactional(readOnly=true) public List<FlowDefinition> flowDefinitions(boolean admin){return List.copyOf(jdbc.query("SELECT * FROM un_platform_flow_definition"+(admin?"":" WHERE status='PUBLISHED'")+" ORDER BY updated_at DESC,id DESC",this::flow));}
    @Transactional public FlowDefinition createFlow(long actor,PlatformFlowDashboardRequests.Create r){validateIdentity(r.code(),r.name());var now=Instant.now();var draft=node(r.draft());var id=ids.nextId();jdbc.update("INSERT INTO un_platform_flow_definition(id,code,name,description,draft_json,draft_version,status,created_at,created_by,updated_at,updated_by,version) VALUES(?,?,?,?,?,1,'DRAFT',?,?,?,?,0)",id,r.code(),text(r.name(),200),optional(r.description(),1000),write(draft),ts(now),actor,ts(now),actor);return requireFlow(id);}
    @Transactional public FlowDefinition saveFlow(long actor,long id,PlatformFlowDashboardRequests.Save r){var old=requireFlow(id);expect(r.expectedVersion(),old.version());validateIdentity(old.code(),r.name());if(jdbc.update("UPDATE un_platform_flow_definition SET name=?,description=?,draft_json=?,draft_version=draft_version+1,updated_at=?,updated_by=?,version=version+1 WHERE id=? AND version=?",text(r.name(),200),optional(r.description(),1000),write(node(r.draft())),ts(Instant.now()),actor,id,old.version())!=1)conflict();return requireFlow(id);}
    @Transactional(readOnly=true) public CheckResult checkFlow(long id){return checkFlowDraft(requireFlow(id).draft());}
    @Transactional public FlowVersion publishFlow(long actor,long id,Long expected){var root=requireFlow(id);expect(expected,root.version());var check=checkFlowDraft(root.draft());if(!check.valid())throw invalid("PLATFORM_FLOW_CHECK_FAILED",String.join("; ",check.issues()));var number=root.activeVersionNumber()==null?1:root.activeVersionNumber()+1;var versionId=ids.nextId();var now=Instant.now();var snapshot=flowSnapshot(root);var checksum=sha(write(snapshot));jdbc.update("INSERT INTO un_platform_flow_version(id,definition_id,version_number,snapshot_json,checksum,published_at,published_by) VALUES(?,?,?,?,?,?,?)",versionId,id,number,write(snapshot),checksum,ts(now),actor);if(jdbc.update("UPDATE un_platform_flow_definition SET active_version_id=?,active_version_number=?,status='PUBLISHED',updated_at=?,updated_by=?,version=version+1 WHERE id=? AND version=?",versionId,number,ts(now),actor,id,root.version())!=1)conflict();return requireFlowVersion(id,number);}
    @Transactional(readOnly=true) public List<FlowVersion> flowVersions(long id){requireFlow(id);return List.copyOf(jdbc.query("SELECT * FROM un_platform_flow_version WHERE definition_id=? ORDER BY version_number DESC",this::flowVersion,id));}
    @Transactional public FlowInstance start(long actor,long definitionId,JsonNode input){var root=requireFlow(definitionId);if(!"PUBLISHED".equals(root.status())||root.activeVersionNumber()==null)throw invalid("PLATFORM_FLOW_NOT_STARTABLE","Platform Flow is not published");var version=requireFlowVersion(definitionId,root.activeVersionNumber());var now=Instant.now();var id=ids.nextId();var result=json.createObjectNode().put("outcome","COMPLETED").put("definitionCode",root.code()).put("definitionVersion",version.versionNumber()).put("executedStepCount",version.snapshot().path("draft").path("steps").size()).put("completedAt",now.toString());((com.fasterxml.jackson.databind.node.ObjectNode)result).set("input",node(input));jdbc.update("INSERT INTO un_platform_flow_instance(id,definition_id,definition_version_id,starter_account_id,status,input_json,result_json,started_at,completed_at,version) VALUES(?,?,?,?,'COMPLETED',?,?,?,?,0)",id,definitionId,Long.parseLong(version.id()),actor,write(node(input)),write(result),ts(now),ts(now));return requireInstance(actor,id);}
    @Transactional(readOnly=true) public List<FlowInstance> instances(long actor){return List.copyOf(jdbc.query("SELECT i.*,v.version_number FROM un_platform_flow_instance i JOIN un_platform_flow_version v ON v.id=i.definition_version_id WHERE i.starter_account_id=? ORDER BY i.started_at DESC,i.id DESC LIMIT 100",this::instance,actor));}
    @Transactional(readOnly=true) public FlowInstance instance(long actor,long id){return requireInstance(actor,id);}

    @Transactional(readOnly=true) public List<Dashboard> dashboards(){return List.copyOf(jdbc.query("SELECT * FROM un_platform_dashboard ORDER BY updated_at DESC,id DESC",this::dashboard));}
    @Transactional public Dashboard createDashboard(long actor,PlatformFlowDashboardRequests.Create r){validateIdentity(r.code(),r.name());var now=Instant.now();var id=ids.nextId();jdbc.update("INSERT INTO un_platform_dashboard(id,code,name,description,draft_json,draft_version,status,created_at,created_by,updated_at,updated_by,version) VALUES(?,?,?,?,?,1,'DRAFT',?,?,?,?,0)",id,r.code(),text(r.name(),200),optional(r.description(),1000),write(node(r.draft())),ts(now),actor,ts(now),actor);return requireDashboard(id);}
    @Transactional public Dashboard saveDashboard(long actor,long id,PlatformFlowDashboardRequests.Save r){var old=requireDashboard(id);expect(r.expectedVersion(),old.version());validateIdentity(old.code(),r.name());if(jdbc.update("UPDATE un_platform_dashboard SET name=?,description=?,draft_json=?,draft_version=draft_version+1,updated_at=?,updated_by=?,version=version+1 WHERE id=? AND version=?",text(r.name(),200),optional(r.description(),1000),write(node(r.draft())),ts(Instant.now()),actor,id,old.version())!=1)conflict();return requireDashboard(id);}
    @Transactional(readOnly=true) public CheckResult checkDashboard(long id){return checkDashboardDraft(requireDashboard(id).draft());}
    @Transactional public DashboardVersion publishDashboard(long actor,long id,Long expected){var root=requireDashboard(id);expect(expected,root.version());var check=checkDashboardDraft(root.draft());if(!check.valid())throw invalid("PLATFORM_DASHBOARD_CHECK_FAILED",String.join("; ",check.issues()));var number=root.activeVersionNumber()==null?1:root.activeVersionNumber()+1;var versionId=ids.nextId();var now=Instant.now();var snapshot=dashboardSnapshot(root);jdbc.update("INSERT INTO un_platform_dashboard_version(id,dashboard_id,version_number,snapshot_json,checksum,published_at,published_by) VALUES(?,?,?,?,?,?,?)",versionId,id,number,write(snapshot),sha(write(snapshot)),ts(now),actor);if(jdbc.update("UPDATE un_platform_dashboard SET active_version_id=?,active_version_number=?,status='PUBLISHED',updated_at=?,updated_by=?,version=version+1 WHERE id=? AND version=?",versionId,number,ts(now),actor,id,root.version())!=1)conflict();return requireDashboardVersion(id,number);}
    @Transactional(readOnly=true) public List<DashboardVersion> dashboardVersions(long id){requireDashboard(id);return List.copyOf(jdbc.query("SELECT * FROM un_platform_dashboard_version WHERE dashboard_id=? ORDER BY version_number DESC",this::dashboardVersion,id));}
    @Transactional public Dashboard restoreDashboard(long actor,long id,int number,Long expected){var root=requireDashboard(id);expect(expected,root.version());var version=requireDashboardVersion(id,number);var snap=version.snapshot();if(jdbc.update("UPDATE un_platform_dashboard SET name=?,description=?,draft_json=?,draft_version=draft_version+1,updated_at=?,updated_by=?,version=version+1 WHERE id=? AND version=?",snap.path("name").asText(),snap.path("description").isNull()?null:snap.path("description").asText(),write(snap.path("draft")),ts(Instant.now()),actor,id,root.version())!=1)conflict();return requireDashboard(id);}
    @Transactional(readOnly=true) public DashboardRuntime runtime(AuthenticatedSession session){var rows=jdbc.query("SELECT d.*,v.snapshot_json,v.version_number,v.published_at FROM un_platform_dashboard d JOIN un_platform_dashboard_version v ON v.id=d.active_version_id WHERE d.status='PUBLISHED' ORDER BY d.updated_at DESC,d.id DESC LIMIT 1",(r,n)->runtime(session,r));if(rows.isEmpty())return defaultRuntime(session);return rows.getFirst();}

    private DashboardRuntime runtime(AuthenticatedSession s,ResultSet r)throws SQLException{var snap=read(r.getString("snapshot_json"));return runtimeFrom(s,snap,r.getInt("version_number"),r.getTimestamp("published_at").toInstant().toString());}
    private DashboardRuntime defaultRuntime(AuthenticatedSession s){var draft=json.createObjectNode();var stats=draft.putArray("statistics");STATS.forEach(stats::add);var entries=draft.putArray("quickEntries");ENTRIES.keySet().forEach(entries::add);draft.put("includeHealth",true);var snap=json.createObjectNode().put("code","PLATFORM_HOME").put("name","平台仪表盘").putNull("description");((com.fasterxml.jackson.databind.node.ObjectNode)snap).set("draft",draft);return runtimeFrom(s,snap,0,Instant.now().toString());}
    private DashboardRuntime runtimeFrom(AuthenticatedSession s,JsonNode snap,int number,String published){var stats=new ArrayList<Statistic>();for(var n:snap.path("draft").path("statistics")){var code=n.asText();var permission=statPermission(code);if(permission!=null&&s.permissions().contains(permission))stats.add(new Statistic(code,statLabel(code),statValue(code,s.accountId()),permission));}var entries=new ArrayList<QuickEntry>();for(var n:snap.path("draft").path("quickEntries")){var e=ENTRIES.get(n.asText());if(e!=null&&s.permissions().contains(e.requiredPermission()))entries.add(e);}var healthRows=new ArrayList<Health>();if(snap.path("draft").path("includeHealth").asBoolean(false)){var provider=health.getIfAvailable();if(provider!=null){try{provider.current().services().forEach(v->healthRows.add(new Health(v.service().name(),v.state().name())));}catch(RuntimeException ignored){healthRows.add(new Health("DEPENDENCIES","UNKNOWN"));}}else healthRows.add(new Health("DEPENDENCIES","UNKNOWN"));}return new DashboardRuntime(snap.path("code").asText(),snap.path("name").asText(),snap.path("description").isNull()?null:snap.path("description").asText(),number,stats,healthRows,entries,published);}
    private long statValue(String code,long account){return switch(code){case "AUTHORIZED_SYSTEMS"->count("SELECT COUNT(*) FROM un_plat_member WHERE account_id=? AND status='ACTIVE' AND deleted_at IS NULL",account);case "OPEN_TASKS"->count("SELECT COUNT(*) FROM un_platform_task WHERE account_id=? AND status='OPEN'",account);case "UNREAD_MESSAGES"->count("SELECT COUNT(*) FROM un_platform_inbox_message WHERE recipient_account_id=? AND read_at IS NULL AND archived_at IS NULL",account);case "FLOW_RUNS"->count("SELECT COUNT(*) FROM un_platform_flow_instance WHERE starter_account_id=?",account);default->0;};}
    private long count(String sql,long id){return Objects.requireNonNullElse(jdbc.queryForObject(sql,Long.class,id),0L);}
    private static String statPermission(String c){return switch(c){case "AUTHORIZED_SYSTEMS"->"platform.runtime.access";case "OPEN_TASKS"->"platform.task.read";case "UNREAD_MESSAGES"->"platform.message.read";case "FLOW_RUNS"->"platform.flow.read";default->null;};}private static String statLabel(String c){return switch(c){case "AUTHORIZED_SYSTEMS"->"授权系统";case "OPEN_TASKS"->"待处理任务";case "UNREAD_MESSAGES"->"未读消息";case "FLOW_RUNS"->"我的流程运行";default->c;};}
    private CheckResult checkFlowDraft(JsonNode d){var issues=new ArrayList<String>();if(!d.isObject())issues.add("draft must be an object");else if(!d.path("steps").isArray()||d.path("steps").isEmpty())issues.add("steps must contain at least one platform step");else for(var n:d.path("steps"))if(!n.isTextual()||n.asText().isBlank()||n.asText().length()>100)issues.add("each step must be non-empty text within 100 characters");return new CheckResult(issues.isEmpty(),issues);}
    private CheckResult checkDashboardDraft(JsonNode d){var issues=new ArrayList<String>();if(!d.isObject())issues.add("draft must be an object");else{if(!d.path("statistics").isArray())issues.add("statistics must be an array");else for(var n:d.path("statistics"))if(!STATS.contains(n.asText()))issues.add("unsupported statistic: "+n.asText());if(!d.path("quickEntries").isArray())issues.add("quickEntries must be an array");else for(var n:d.path("quickEntries"))if(!ENTRIES.containsKey(n.asText()))issues.add("unsupported quick entry: "+n.asText());if(!d.path("includeHealth").isBoolean())issues.add("includeHealth must be boolean");}return new CheckResult(issues.isEmpty(),issues);}
    private JsonNode flowSnapshot(FlowDefinition r){var o=json.createObjectNode().put("code",r.code()).put("name",r.name());if(r.description()==null)o.putNull("description");else o.put("description",r.description());o.set("draft",r.draft());return o;}
    private JsonNode dashboardSnapshot(Dashboard r){var o=json.createObjectNode().put("code",r.code()).put("name",r.name());if(r.description()==null)o.putNull("description");else o.put("description",r.description());o.set("draft",r.draft());return o;}
    private FlowDefinition requireFlow(long id){var v=jdbc.query("SELECT * FROM un_platform_flow_definition WHERE id=?",this::flow,id);if(v.isEmpty())throw notFound("PLATFORM_FLOW_NOT_FOUND");return v.getFirst();}private FlowVersion requireFlowVersion(long id,int n){var v=jdbc.query("SELECT * FROM un_platform_flow_version WHERE definition_id=? AND version_number=?",this::flowVersion,id,n);if(v.isEmpty())throw notFound("PLATFORM_FLOW_VERSION_NOT_FOUND");return v.getFirst();}private FlowInstance requireInstance(long actor,long id){var v=jdbc.query("SELECT i.*,v.version_number FROM un_platform_flow_instance i JOIN un_platform_flow_version v ON v.id=i.definition_version_id WHERE i.id=? AND i.starter_account_id=?",this::instance,id,actor);if(v.isEmpty())throw notFound("PLATFORM_FLOW_INSTANCE_NOT_FOUND");return v.getFirst();}private Dashboard requireDashboard(long id){var v=jdbc.query("SELECT * FROM un_platform_dashboard WHERE id=?",this::dashboard,id);if(v.isEmpty())throw notFound("PLATFORM_DASHBOARD_NOT_FOUND");return v.getFirst();}private DashboardVersion requireDashboardVersion(long id,int n){var v=jdbc.query("SELECT * FROM un_platform_dashboard_version WHERE dashboard_id=? AND version_number=?",this::dashboardVersion,id,n);if(v.isEmpty())throw notFound("PLATFORM_DASHBOARD_VERSION_NOT_FOUND");return v.getFirst();}
    private FlowDefinition flow(ResultSet r,int n)throws SQLException{return new FlowDefinition(Long.toString(r.getLong("id")),r.getString("code"),r.getString("name"),r.getString("description"),read(r.getString("draft_json")),r.getLong("draft_version"),r.getString("status"),r.getObject("active_version_number",Integer.class),r.getLong("version"),r.getTimestamp("created_at").toInstant().toString(),r.getTimestamp("updated_at").toInstant().toString());}private FlowVersion flowVersion(ResultSet r,int n)throws SQLException{return new FlowVersion(Long.toString(r.getLong("id")),r.getInt("version_number"),read(r.getString("snapshot_json")),r.getString("checksum"),r.getTimestamp("published_at").toInstant().toString(),Long.toString(r.getLong("published_by")));}private FlowInstance instance(ResultSet r,int n)throws SQLException{var c=r.getTimestamp("completed_at");return new FlowInstance(Long.toString(r.getLong("id")),Long.toString(r.getLong("definition_id")),r.getInt("version_number"),r.getString("status"),read(r.getString("input_json")),read(r.getString("result_json")),r.getTimestamp("started_at").toInstant().toString(),c==null?null:c.toInstant().toString(),r.getLong("version"));}private Dashboard dashboard(ResultSet r,int n)throws SQLException{return new Dashboard(Long.toString(r.getLong("id")),r.getString("code"),r.getString("name"),r.getString("description"),read(r.getString("draft_json")),r.getLong("draft_version"),r.getString("status"),r.getObject("active_version_number",Integer.class),r.getLong("version"),r.getTimestamp("created_at").toInstant().toString(),r.getTimestamp("updated_at").toInstant().toString());}private DashboardVersion dashboardVersion(ResultSet r,int n)throws SQLException{return new DashboardVersion(Long.toString(r.getLong("id")),r.getInt("version_number"),read(r.getString("snapshot_json")),r.getString("checksum"),r.getTimestamp("published_at").toInstant().toString(),Long.toString(r.getLong("published_by")));}
    private JsonNode node(JsonNode n){return n==null||n.isNull()?json.createObjectNode():n.deepCopy();}private String write(JsonNode n){try{return json.writeValueAsString(n);}catch(Exception e){throw invalid("PLATFORM_CONFIG_INVALID","Configuration is not JSON serializable");}}private JsonNode read(String v){if(v==null)return null;try{return json.readTree(v);}catch(Exception e){throw new IllegalStateException(e);}}private static Timestamp ts(Instant i){return Timestamp.from(i);}private static String sha(String v){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(v.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
    private static void validateIdentity(String code,String name){if(code==null||!code.matches("^[A-Z][A-Z0-9_]{1,63}$"))throw invalid("PLATFORM_CONFIG_INVALID","code is invalid");text(name,200);}private static String text(String v,int max){if(v==null||v.isBlank()||v.strip().length()>max)throw invalid("PLATFORM_CONFIG_INVALID","text is invalid");return v.strip();}private static String optional(String v,int max){if(v==null||v.isBlank())return null;return text(v,max);}private static void expect(Long expected,long actual){if(expected==null||expected!=actual)conflict();}private static void conflict(){throw new BusinessException("PLATFORM_CONFIG_VERSION_CONFLICT","Configuration changed concurrently",HttpStatus.CONFLICT);}private static BusinessException invalid(String c,String m){return new BusinessException(c,m,HttpStatus.UNPROCESSABLE_ENTITY);}private static BusinessException notFound(String c){return new BusinessException(c,"Platform resource was not found",HttpStatus.NOT_FOUND);}
}
