package com.unique.examine.plat.platform;

import com.unique.examine.core.api.*;import com.unique.examine.core.context.RequestSession;import com.unique.examine.plat.manage.service.SessionGuard;import jakarta.servlet.http.HttpServletRequest;import org.springframework.http.*;import org.springframework.web.bind.annotation.*;
import java.util.List;import static com.unique.examine.plat.platform.PlatformFlowDashboardViews.*;

@RestController
public class PlatformFlowDashboardController {
    private final PlatformFlowDashboardService service;public PlatformFlowDashboardController(PlatformFlowDashboardService service){this.service=service;}
    @GetMapping("/api/v1/platform/flows/definitions") public ApiResponse<List<FlowDefinition>> runtimeDefinitions(@RequestAttribute(value=RequestSession.REQUEST_ATTRIBUTE,required=false)Object value,HttpServletRequest r){SessionGuard.requirePlatform(value,"platform.flow.read");return ok(service.flowDefinitions(false),r);}
    @PostMapping("/api/v1/platform/flows/definitions/{id}/instances") public ResponseEntity<ApiResponse<FlowInstance>> start(@PathVariable long id,@RequestBody(required=false)PlatformFlowDashboardRequests.Start body,@RequestAttribute(value=RequestSession.REQUEST_ATTRIBUTE,required=false)Object value,HttpServletRequest r){var s=SessionGuard.requirePlatform(value,"platform.flow.start");return ResponseEntity.status(HttpStatus.CREATED).body(ok(service.start(s.accountId(),id,body==null?null:body.input()),r));}
    @GetMapping("/api/v1/platform/flows/instances") public ApiResponse<List<FlowInstance>> instances(@RequestAttribute(value=RequestSession.REQUEST_ATTRIBUTE,required=false)Object value,HttpServletRequest r){var s=SessionGuard.requirePlatform(value,"platform.flow.read");return ok(service.instances(s.accountId()),r);}
    @GetMapping("/api/v1/platform/flows/instances/{id}") public ApiResponse<FlowInstance> instance(@PathVariable long id,@RequestAttribute(value=RequestSession.REQUEST_ATTRIBUTE,required=false)Object value,HttpServletRequest r){var s=SessionGuard.requirePlatform(value,"platform.flow.read");return ok(service.instance(s.accountId(),id),r);}
    @GetMapping("/api/v1/platform/admin/flows/definitions") public ApiResponse<List<FlowDefinition>> adminDefinitions(@RequestAttribute(value=RequestSession.REQUEST_ATTRIBUTE,required=false)Object value,HttpServletRequest r){SessionGuard.requirePlatform(value,"platform.flow.manage");return ok(service.flowDefinitions(true),r);}
    @PostMapping("/api/v1/platform/admin/flows/definitions") public ResponseEntity<ApiResponse<FlowDefinition>> createFlow(@RequestBody PlatformFlowDashboardRequests.Create body,@RequestAttribute(value=RequestSession.REQUEST_ATTRIBUTE,required=false)Object value,HttpServletRequest r){var s=SessionGuard.requirePlatform(value,"platform.flow.manage");return ResponseEntity.status(HttpStatus.CREATED).body(ok(service.createFlow(s.accountId(),body),r));}
    @PutMapping("/api/v1/platform/admin/flows/definitions/{id}/draft") public ApiResponse<FlowDefinition> saveFlow(@PathVariable long id,@RequestBody PlatformFlowDashboardRequests.Save body,@RequestAttribute(value=RequestSession.REQUEST_ATTRIBUTE,required=false)Object value,HttpServletRequest r){var s=SessionGuard.requirePlatform(value,"platform.flow.manage");return ok(service.saveFlow(s.accountId(),id,body),r);}
    @PostMapping("/api/v1/platform/admin/flows/definitions/{id}/draft:check") public ApiResponse<CheckResult> checkFlow(@PathVariable long id,@RequestAttribute(value=RequestSession.REQUEST_ATTRIBUTE,required=false)Object value,HttpServletRequest r){SessionGuard.requirePlatform(value,"platform.flow.manage");return ok(service.checkFlow(id),r);}
    @PostMapping("/api/v1/platform/admin/flows/definitions/{id}/draft:publish") public ApiResponse<FlowVersion> publishFlow(@PathVariable long id,@RequestBody PlatformFlowDashboardRequests.Publish body,@RequestAttribute(value=RequestSession.REQUEST_ATTRIBUTE,required=false)Object value,HttpServletRequest r){var s=SessionGuard.requirePlatform(value,"platform.flow.manage");return ok(service.publishFlow(s.accountId(),id,body.expectedVersion()),r);}
    @GetMapping("/api/v1/platform/admin/flows/definitions/{id}/versions") public ApiResponse<List<FlowVersion>> flowVersions(@PathVariable long id,@RequestAttribute(value=RequestSession.REQUEST_ATTRIBUTE,required=false)Object value,HttpServletRequest r){SessionGuard.requirePlatform(value,"platform.flow.manage");return ok(service.flowVersions(id),r);}

    @GetMapping("/api/v1/platform/admin/dashboards") public ApiResponse<List<Dashboard>> dashboards(@RequestAttribute(value=RequestSession.REQUEST_ATTRIBUTE,required=false)Object value,HttpServletRequest r){SessionGuard.requirePlatform(value,"platform.dashboard.manage");return ok(service.dashboards(),r);}
    @PostMapping("/api/v1/platform/admin/dashboards") public ResponseEntity<ApiResponse<Dashboard>> createDashboard(@RequestBody PlatformFlowDashboardRequests.Create body,@RequestAttribute(value=RequestSession.REQUEST_ATTRIBUTE,required=false)Object value,HttpServletRequest r){var s=SessionGuard.requirePlatform(value,"platform.dashboard.manage");return ResponseEntity.status(HttpStatus.CREATED).body(ok(service.createDashboard(s.accountId(),body),r));}
    @PutMapping("/api/v1/platform/admin/dashboards/{id}/draft") public ApiResponse<Dashboard> saveDashboard(@PathVariable long id,@RequestBody PlatformFlowDashboardRequests.Save body,@RequestAttribute(value=RequestSession.REQUEST_ATTRIBUTE,required=false)Object value,HttpServletRequest r){var s=SessionGuard.requirePlatform(value,"platform.dashboard.manage");return ok(service.saveDashboard(s.accountId(),id,body),r);}
    @PostMapping("/api/v1/platform/admin/dashboards/{id}/draft:check") public ApiResponse<CheckResult> checkDashboard(@PathVariable long id,@RequestAttribute(value=RequestSession.REQUEST_ATTRIBUTE,required=false)Object value,HttpServletRequest r){SessionGuard.requirePlatform(value,"platform.dashboard.manage");return ok(service.checkDashboard(id),r);}
    @PostMapping("/api/v1/platform/admin/dashboards/{id}/draft:publish") public ApiResponse<DashboardVersion> publishDashboard(@PathVariable long id,@RequestBody PlatformFlowDashboardRequests.Publish body,@RequestAttribute(value=RequestSession.REQUEST_ATTRIBUTE,required=false)Object value,HttpServletRequest r){var s=SessionGuard.requirePlatform(value,"platform.dashboard.manage");return ok(service.publishDashboard(s.accountId(),id,body.expectedVersion()),r);}
    @GetMapping("/api/v1/platform/admin/dashboards/{id}/versions") public ApiResponse<List<DashboardVersion>> dashboardVersions(@PathVariable long id,@RequestAttribute(value=RequestSession.REQUEST_ATTRIBUTE,required=false)Object value,HttpServletRequest r){SessionGuard.requirePlatform(value,"platform.dashboard.manage");return ok(service.dashboardVersions(id),r);}
    @PostMapping("/api/v1/platform/admin/dashboards/{id}/versions/{version}:restore") public ApiResponse<Dashboard> restoreDashboard(@PathVariable long id,@PathVariable int version,@RequestBody PlatformFlowDashboardRequests.Restore body,@RequestAttribute(value=RequestSession.REQUEST_ATTRIBUTE,required=false)Object value,HttpServletRequest r){var s=SessionGuard.requirePlatform(value,"platform.dashboard.manage");return ok(service.restoreDashboard(s.accountId(),id,version,body.expectedVersion()),r);}
    @GetMapping("/api/v1/platform/dashboard") public ApiResponse<DashboardRuntime> runtimeDashboard(@RequestAttribute(value=RequestSession.REQUEST_ATTRIBUTE,required=false)Object value,HttpServletRequest r){var s=SessionGuard.requirePlatform(value,"platform.dashboard.view");return ok(service.runtime(s),r);}
    private static <T> ApiResponse<T> ok(T data,HttpServletRequest r){return ApiResponse.success(data,String.valueOf(r.getAttribute(WebRequestAttributes.REQUEST_ID)),String.valueOf(r.getAttribute(WebRequestAttributes.TRACE_ID)));}
}
