// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.flow.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.flow.base.entity.FlowEdge;
import com.unique.unexamine.flow.base.mapper.FlowEdgeMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class FlowEdgeBaseService {
    private final FlowEdgeMapper mapper;

    public FlowEdgeBaseService(FlowEdgeMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(FlowEdge entity) {
        return mapper.insert(entity);
    }

    public FlowEdge selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<FlowEdge> selectList(Wrapper<FlowEdge> query) {
        return mapper.selectList(query);
    }

    public int updateById(FlowEdge entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
