// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.flow.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.flow.base.entity.FlowHistoryEvent;
import com.unique.unexamine.flow.base.mapper.FlowHistoryEventMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class FlowHistoryEventBaseService {
    private final FlowHistoryEventMapper mapper;

    public FlowHistoryEventBaseService(FlowHistoryEventMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(FlowHistoryEvent entity) {
        return mapper.insert(entity);
    }

    public FlowHistoryEvent selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<FlowHistoryEvent> selectList(Wrapper<FlowHistoryEvent> query) {
        return mapper.selectList(query);
    }
}
