// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.flow.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.flow.base.entity.FlowTaskCandidate;
import com.unique.unexamine.flow.base.mapper.FlowTaskCandidateMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class FlowTaskCandidateBaseService {
    private final FlowTaskCandidateMapper mapper;

    public FlowTaskCandidateBaseService(FlowTaskCandidateMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(FlowTaskCandidate entity) {
        return mapper.insert(entity);
    }

    public FlowTaskCandidate selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<FlowTaskCandidate> selectList(Wrapper<FlowTaskCandidate> query) {
        return mapper.selectList(query);
    }

    public int updateById(FlowTaskCandidate entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
