// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.flow.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.flow.base.entity.FlowBindingResolution;
import com.unique.unexamine.flow.base.mapper.FlowBindingResolutionMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class FlowBindingResolutionBaseService {
    private final FlowBindingResolutionMapper mapper;

    public FlowBindingResolutionBaseService(FlowBindingResolutionMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(FlowBindingResolution entity) {
        return mapper.insert(entity);
    }

    public FlowBindingResolution selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<FlowBindingResolution> selectList(Wrapper<FlowBindingResolution> query) {
        return mapper.selectList(query);
    }

    public int updateById(FlowBindingResolution entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
