// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.flow.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.flow.base.entity.FlowDefinition;
import com.unique.unexamine.flow.base.mapper.FlowDefinitionMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class FlowDefinitionBaseService {
    private final FlowDefinitionMapper mapper;

    public FlowDefinitionBaseService(FlowDefinitionMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(FlowDefinition entity) {
        return mapper.insert(entity);
    }

    public FlowDefinition selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<FlowDefinition> selectList(Wrapper<FlowDefinition> query) {
        return mapper.selectList(query);
    }

    public int updateById(FlowDefinition entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
