// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.flow.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.flow.base.entity.FlowExecution;
import com.unique.unexamine.flow.base.mapper.FlowExecutionMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class FlowExecutionBaseService {
    private final FlowExecutionMapper mapper;

    public FlowExecutionBaseService(FlowExecutionMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(FlowExecution entity) {
        return mapper.insert(entity);
    }

    public FlowExecution selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<FlowExecution> selectList(Wrapper<FlowExecution> query) {
        return mapper.selectList(query);
    }

    public int updateById(FlowExecution entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
