// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.flow.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.flow.base.entity.FlowPublication;
import com.unique.unexamine.flow.base.mapper.FlowPublicationMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class FlowPublicationBaseService {
    private final FlowPublicationMapper mapper;

    public FlowPublicationBaseService(FlowPublicationMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(FlowPublication entity) {
        return mapper.insert(entity);
    }

    public FlowPublication selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<FlowPublication> selectList(Wrapper<FlowPublication> query) {
        return mapper.selectList(query);
    }

    public int updateById(FlowPublication entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
