// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.flow.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.flow.base.entity.FlowNode;
import com.unique.unexamine.flow.base.mapper.FlowNodeMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class FlowNodeBaseService {
    private final FlowNodeMapper mapper;

    public FlowNodeBaseService(FlowNodeMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(FlowNode entity) {
        return mapper.insert(entity);
    }

    public FlowNode selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<FlowNode> selectList(Wrapper<FlowNode> query) {
        return mapper.selectList(query);
    }

    public int updateById(FlowNode entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
