// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.flow.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.flow.base.entity.FlowInstance;
import com.unique.unexamine.flow.base.mapper.FlowInstanceMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class FlowInstanceBaseService {
    private final FlowInstanceMapper mapper;

    public FlowInstanceBaseService(FlowInstanceMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(FlowInstance entity) {
        return mapper.insert(entity);
    }

    public FlowInstance selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<FlowInstance> selectList(Wrapper<FlowInstance> query) {
        return mapper.selectList(query);
    }

    public int updateById(FlowInstance entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
