// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.flow.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.flow.base.entity.FlowTriggerBinding;
import com.unique.unexamine.flow.base.mapper.FlowTriggerBindingMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class FlowTriggerBindingBaseService {
    private final FlowTriggerBindingMapper mapper;

    public FlowTriggerBindingBaseService(FlowTriggerBindingMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(FlowTriggerBinding entity) {
        return mapper.insert(entity);
    }

    public FlowTriggerBinding selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<FlowTriggerBinding> selectList(Wrapper<FlowTriggerBinding> query) {
        return mapper.selectList(query);
    }

    public int updateById(FlowTriggerBinding entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
