// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.flow.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.flow.base.entity.FlowInstanceVariable;
import com.unique.unexamine.flow.base.mapper.FlowInstanceVariableMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class FlowInstanceVariableBaseService {
    private final FlowInstanceVariableMapper mapper;

    public FlowInstanceVariableBaseService(FlowInstanceVariableMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(FlowInstanceVariable entity) {
        return mapper.insert(entity);
    }

    public FlowInstanceVariable selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<FlowInstanceVariable> selectList(Wrapper<FlowInstanceVariable> query) {
        return mapper.selectList(query);
    }

    public int updateById(FlowInstanceVariable entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
