// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.flow.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.flow.base.entity.FlowAction;
import com.unique.unexamine.flow.base.mapper.FlowActionMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class FlowActionBaseService {
    private final FlowActionMapper mapper;

    public FlowActionBaseService(FlowActionMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(FlowAction entity) {
        return mapper.insert(entity);
    }

    public FlowAction selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<FlowAction> selectList(Wrapper<FlowAction> query) {
        return mapper.selectList(query);
    }

    public int updateById(FlowAction entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
