// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.flow.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.flow.base.entity.FlowVersion;
import com.unique.unexamine.flow.base.mapper.FlowVersionMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class FlowVersionBaseService {
    private final FlowVersionMapper mapper;

    public FlowVersionBaseService(FlowVersionMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(FlowVersion entity) {
        return mapper.insert(entity);
    }

    public FlowVersion selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<FlowVersion> selectList(Wrapper<FlowVersion> query) {
        return mapper.selectList(query);
    }
}
