// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.dataexchange.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.dataexchange.base.entity.ExchangeImportRow;
import com.unique.unexamine.dataexchange.base.mapper.ExchangeImportRowMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class ExchangeImportRowBaseService {
    private final ExchangeImportRowMapper mapper;

    public ExchangeImportRowBaseService(ExchangeImportRowMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(ExchangeImportRow entity) {
        return mapper.insert(entity);
    }

    public ExchangeImportRow selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<ExchangeImportRow> selectList(Wrapper<ExchangeImportRow> query) {
        return mapper.selectList(query);
    }

    public int updateById(ExchangeImportRow entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
