// Generated by MyBatis-Plus Generator via Template Base. Do not edit.
package com.unique.unexamine.dataexchange.base.service;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.unique.unexamine.dataexchange.base.entity.ExchangeExportBatch;
import com.unique.unexamine.dataexchange.base.mapper.ExchangeExportBatchMapper;
import org.springframework.stereotype.Service;

import java.io.Serializable;
import java.util.List;

@Service
public class ExchangeExportBatchBaseService {
    private final ExchangeExportBatchMapper mapper;

    public ExchangeExportBatchBaseService(ExchangeExportBatchMapper mapper) {
        this.mapper = mapper;
    }

    public int insert(ExchangeExportBatch entity) {
        return mapper.insert(entity);
    }

    public ExchangeExportBatch selectById(Serializable id) {
        return mapper.selectById(id);
    }

    public List<ExchangeExportBatch> selectList(Wrapper<ExchangeExportBatch> query) {
        return mapper.selectList(query);
    }

    public int updateById(ExchangeExportBatch entity) {
        return mapper.updateById(entity);
    }

    public int deleteById(Serializable id) {
        return mapper.deleteById(id);
    }
}
