// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.messagelog.base.service;

import com.baomidou.mybatisplus.extension.service.IService;
import com.unique.examine.messagelog.base.entity.AuditLogExportTask;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

/**
 * Generated base service contract for AuditLogExportTask.
 */
public interface AuditLogExportTaskBaseService extends IService<AuditLogExportTask> {

    Optional<AuditLogExportTask> findById(Long id);

    List<AuditLogExportTask> findAll();

    AuditLogExportTask saveEntity(AuditLogExportTask entity);

    boolean deleteByIds(Collection<Long> ids);
}
