// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.messagelog.base.service;

import com.baomidou.mybatisplus.extension.service.IService;
import com.unique.examine.messagelog.base.entity.AuditBusinessLog;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

/**
 * Generated base service contract for AuditBusinessLog.
 */
public interface AuditBusinessLogBaseService extends IService<AuditBusinessLog> {

    Optional<AuditBusinessLog> findById(Long id);

    List<AuditBusinessLog> findAll();

    AuditBusinessLog saveEntity(AuditBusinessLog entity);

    boolean deleteByIds(Collection<Long> ids);
}
