// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.messagelog.base.service;

import com.baomidou.mybatisplus.extension.service.IService;
import com.unique.examine.messagelog.base.entity.MessageDeliveryLog;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

/**
 * Generated base service contract for MessageDeliveryLog.
 */
public interface MessageDeliveryLogBaseService extends IService<MessageDeliveryLog> {

    Optional<MessageDeliveryLog> findById(Long id);

    List<MessageDeliveryLog> findAll();

    MessageDeliveryLog saveEntity(MessageDeliveryLog entity);

    boolean deleteByIds(Collection<Long> ids);
}
