// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.messagelog.base.service;

import com.baomidou.mybatisplus.extension.service.IService;
import com.unique.examine.messagelog.base.entity.MessageTodo;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

/**
 * Generated base service contract for MessageTodo.
 */
public interface MessageTodoBaseService extends IService<MessageTodo> {

    Optional<MessageTodo> findById(Long id);

    List<MessageTodo> findAll();

    MessageTodo saveEntity(MessageTodo entity);

    boolean deleteByIds(Collection<Long> ids);
}
