// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.messagelog.base.service;

import com.baomidou.mybatisplus.extension.service.IService;
import com.unique.examine.messagelog.base.entity.MessageMessage;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

/**
 * Generated base service contract for MessageMessage.
 */
public interface MessageMessageBaseService extends IService<MessageMessage> {

    Optional<MessageMessage> findById(Long id);

    List<MessageMessage> findAll();

    MessageMessage saveEntity(MessageMessage entity);

    boolean deleteByIds(Collection<Long> ids);
}
