// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.app.base.service;

import com.baomidou.mybatisplus.extension.service.IService;
import com.unique.examine.app.base.entity.OpenapiApp;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

/**
 * Generated base service contract for OpenapiApp.
 */
public interface OpenapiAppBaseService extends IService<OpenapiApp> {

    Optional<OpenapiApp> findById(Long id);

    List<OpenapiApp> findAll();

    OpenapiApp saveEntity(OpenapiApp entity);

    boolean deleteByIds(Collection<Long> ids);
}
