// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.upload.base.service;

import com.baomidou.mybatisplus.extension.service.IService;
import com.unique.examine.upload.base.entity.UploadFile;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

/**
 * Generated base service contract for UploadFile.
 */
public interface UploadFileBaseService extends IService<UploadFile> {

    Optional<UploadFile> findById(Long id);

    List<UploadFile> findAll();

    UploadFile saveEntity(UploadFile entity);

    boolean deleteByIds(Collection<Long> ids);
}
