// <auto-generated>
// Generated from sql/init.sql by examine-generator. Do not hand edit.
// </auto-generated>
package com.unique.examine.upload.base.service;

import com.baomidou.mybatisplus.extension.service.IService;
import com.unique.examine.upload.base.entity.UploadFileVersion;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

/**
 * Generated base service contract for UploadFileVersion.
 */
public interface UploadFileVersionBaseService extends IService<UploadFileVersion> {

    Optional<UploadFileVersion> findById(Long id);

    List<UploadFileVersion> findAll();

    UploadFileVersion saveEntity(UploadFileVersion entity);

    boolean deleteByIds(Collection<Long> ids);
}
