// @generated by Template Base. Do not edit by hand.
package com.unique.unexamine;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class UnexamineApplication {
    public static void main(String[] args) {
        SpringApplication.run(UnexamineApplication.class, args);
    }
}
